import type { Difficulty, Explanation, Question, QuestionKind } from '../domain/models'

type OptionId = 'a' | 'b' | 'c' | 'd'

interface QuestionDraft {
  subtopic: string
  difficulty: Difficulty
  kind: QuestionKind
  prompt: string
  options: readonly [string, string, string, string]
  correct: OptionId
  explanation: Explanation
  section: string
  tags: string[]
  code?: string
  version?: Question['version']
}

function question(index: number, draft: QuestionDraft): Question {
  const id = `android-sdk-${String(index).padStart(3, '0')}`
  const optionIds: OptionId[] = ['a', 'b', 'c', 'd']

  return {
    id,
    topicId: 'android-sdk',
    subtopic: draft.subtopic,
    difficulty: draft.difficulty,
    kind: draft.kind,
    prompt: draft.prompt,
    ...(draft.code ? { code: { language: 'kotlin' as const, value: draft.code } } : {}),
    options: draft.options.map((text, optionIndex) => ({
      id: `${id}-${optionIds[optionIndex]}`,
      text,
    })),
    correctOptionId: `${id}-${draft.correct}`,
    explanation: draft.explanation,
    source: { file: '10-android-sdk-deep.md', section: draft.section },
    tags: draft.tags,
    ...(draft.version ? { version: draft.version } : {}),
  }
}

export const androidSdkQuestions: Question[] = [
  question(1, {
    subtopic: 'Модель приложения',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какое следствие компонентной модели Android важнее всего для инициализации приложения?',
    options: [
      'Система всегда сначала создаёт launcher Activity, поэтому общую инициализацию можно делать в ней',
      'Любой объявленный компонент может быть первой точкой входа в новом процессе, поэтому инициализация должна быть идемпотентной',
      'Application создаётся один раз на всё устройство, поэтому его состояние можно считать постоянным',
      'Компоненты создаются только после явного вызова функции main',
    ],
    correct: 'b',
    explanation: {
      summary: 'Android-приложение — набор независимо запускаемых системой компонентов, а не программа с гарантированной точкой входа.',
      mechanism: 'Система может создать Activity, Service, Receiver или Provider в новом процессе и в произвольном порядке. Общая инициализация должна корректно выполняться без предположения, что другой компонент уже запускался.',
      trap: 'Launcher Activity не является обязательной первой точкой входа: приложение могут поднять broadcast, provider или service.',
      example: 'ContentProvider библиотеки может быть создан ещё до Application.onCreate().',
    },
    section: '1.1. Что такое приложение с точки зрения системы',
    tags: ['components', 'process', 'initialization'],
  }),
  question(2, {
    subtopic: 'Application и процессы',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'После добавления android:process=":remote" аналитика стала инициализироваться дважды. Каково точное объяснение?',
    options: [
      'Application.onCreate() вызывается после каждого onResume()',
      'Удалённый компонент повторно использует Application из основного процесса',
      'Каждый процесс имеет собственные Application, DI-граф и синглтоны',
      'Zygote разделяет все Kotlin object между процессами',
    ],
    correct: 'c',
    explanation: {
      summary: 'Application создаётся один раз на процесс, а не один раз на установленное приложение.',
      mechanism: 'Процесс с суффиксом :remote имеет отдельную память. В нём заново создаются Application, DI-контейнеры и process-local синглтоны.',
      trap: 'Kotlin object гарантирует единственный экземпляр только внутри конкретного процесса.',
      verification: 'Запишите PID в Application.onCreate() и сравните логи основного и remote-процессов.',
    },
    section: '1.2. Процесс и Application',
    tags: ['application', 'multiprocess', 'zygote'],
  }),
  question(3, {
    subtopic: 'Manifest',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Что обязательно проверить у компонента с intent-filter при targetSdk 31+?',
    options: [
      'Явно заданный android:exported',
      'Наличие QUERY_ALL_PACKAGES',
      'android:process=":remote"',
      'Отключённый manifest merger',
    ],
    correct: 'a',
    explanation: {
      summary: 'Для компонента с intent-filter значение android:exported должно быть задано явно.',
      mechanism: 'Начиная с Android 12 при target API 31+ сборка/установка требует явного решения, доступен ли компонент другим приложениям. Экспортированный компонент становится внешней поверхностью атаки.',
      trap: 'Intent-filter сам по себе больше не должен неявно определять exported.',
      verification: 'Просмотрите merged manifest: библиотеки могут добавлять компоненты и разрешения.',
    },
    section: '1.3. Манифест как контракт',
    tags: ['manifest', 'exported', 'security'],
    version: { asOf: 'Android 12 / API 31', reviewAfter: 'При каждом повышении targetSdk' },
  }),
  question(4, {
    subtopic: 'Context',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'Почему обычный Dialog нельзя надёжно показать с application context?',
    options: [
      'Application context не умеет загружать ресурсы',
      'Диалогу нужен window token Activity, которого нет у application context',
      'Application context доступен только из Service',
      'Диалоги разрешены только из Fragment',
    ],
    correct: 'b',
    explanation: {
      summary: 'Обычному приложенческому окну нужен токен окна Activity.',
      mechanism: 'WindowManager прикрепляет Dialog к существующему окну по window token. У application context такого токена нет, поэтому типичный результат — BadTokenException.',
      trap: 'Утверждение «любое окно возможно только из Activity» слишком сильное: overlay-окна существуют, но требуют SYSTEM_ALERT_WINDOW и имеют другой режим.',
    },
    section: '2.1. Виды и время жизни',
    tags: ['context', 'dialog', 'window-token'],
  }),
  question(5, {
    subtopic: 'Activity lifecycle',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'На какой callback нельзя полагаться для критичного сохранения данных?',
    options: ['onStart()', 'onResume()', 'onPause()', 'onDestroy()'],
    correct: 'd',
    explanation: {
      summary: 'onDestroy() не гарантирован при убийстве процесса.',
      mechanism: 'Система может завершить процесс без финального callback Activity. Критичные данные нужно сохранять раньше и в устойчивое хранилище.',
      trap: 'onDestroy() подходит для освобождения ресурсов при штатном уничтожении экземпляра, но не является транзакционной гарантией.',
    },
    section: '3.1. Жизненный цикл',
    tags: ['activity', 'lifecycle', 'process-death'],
  }),
  question(6, {
    subtopic: 'Configuration change',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему ViewModel переживает поворот, но не переживает смерть процесса?',
    options: [
      'ViewModel сериализуется в Bundle только при повороте',
      'ViewModel хранится в системном Binder-сервисе',
      'ComponentActivity передаёт ViewModelStore новому экземпляру через non-configuration instance, а после смерти процесса передавать уже нечего',
      'ViewModel является глобальным singleton',
    ],
    correct: 'c',
    explanation: {
      summary: 'ViewModel удерживается механизмом non-configuration state внутри живого процесса.',
      mechanism: 'Старая ComponentActivity отдаёт ViewModelStore, а ActivityThread передаёт его новому экземпляру. При process death память и Store исчезают; восстановление опирается на SavedStateHandle и диск.',
      trap: 'ViewModel не сериализуется автоматически и не является process-persistent.',
    },
    section: '3.2. Поворот экрана: что происходит по шагам',
    tags: ['viewmodel', 'configuration-change', 'saved-state'],
  }),
  question(7, {
    subtopic: 'Process death',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Как корректно проверить восстановление именно после process death?',
    options: [
      'Включить Don’t keep activities и повернуть экран',
      'Убить пакет через adb shell am kill <pkg>, пока приложение в фоне, затем вернуться',
      'Вызвать Activity.recreate()',
      'Свернуть и сразу развернуть приложение',
    ],
    correct: 'b',
    explanation: {
      summary: 'Нужно завершить процесс, сохранив системную возможность восстановить задачу.',
      mechanism: 'am kill для фонового приложения уничтожает ViewModel, синглтоны и память процесса. Возврат проверяет восстановление из Bundle/SavedStateHandle и диска.',
      trap: 'Don’t keep activities уничтожает Activity, но оставляет процесс и process-level состояние живыми.',
      verification: 'Сравните PID до ухода в фон и после возврата.',
    },
    section: '3.3. Configuration change против process death',
    tags: ['process-death', 'testing', 'savedstatehandle'],
  }),
  question(8, {
    subtopic: 'Saved state',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Как исправить этот код сохранения состояния?',
    code: 'override fun onSaveInstanceState(outState: Bundle) {\n    outState.putParcelableArrayList("items", ArrayList(allItems))\n}',
    options: [
      'Сжать список в ByteArray и оставить в Bundle',
      'Разбить список между несколькими ключами Bundle',
      'Сохранить идентификатор/позицию, а данные повторно прочитать из репозитория или БД',
      'Перенести список в static поле',
    ],
    correct: 'c',
    explanation: {
      summary: 'В saved state сохраняют минимальное состояние навигации и ввода, а не наборы доменных данных.',
      mechanism: 'Bundle передаётся через общий ограниченный Binder-буфер. Большой список создаёт риск TransactionTooLargeException; устойчивые данные должны жить в БД или другом репозитории.',
      trap: 'Сжатие не даёт надёжной верхней границы и всё равно использует Binder-буфер.',
    },
    section: '15.2',
    tags: ['bundle', 'binder', 'code-review'],
  }),
  question(9, {
    subtopic: 'Tasks и launch modes',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Activity с launchMode="singleTask" уже находится в задаче, а над ней открыты два экрана. Что произойдёт при повторном запуске?',
    options: [
      'Всегда создастся второй экземпляр Activity',
      'Интент придёт в onNewIntent(), а экраны над Activity будут удалены из стека',
      'Интент будет проигнорирован',
      'Будет создана отдельная задача с singleInstance',
    ],
    correct: 'b',
    explanation: {
      summary: 'singleTask переиспользует экземпляр в задаче и очищает всё над ним.',
      mechanism: 'Повторный Intent доставляется через onNewIntent(). Если подходящей задачи нет, Activity становится корнем новой задачи.',
      trap: 'singleTop переиспользует Activity только тогда, когда она уже на вершине; он не очищает произвольные экраны над ней.',
    },
    section: '3.4. Задачи, back stack, launch modes',
    tags: ['activity', 'task', 'singleTask'],
  }),
  question(10, {
    subtopic: 'Activity Result API',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Какое преимущество Activity Result API связано с восстановлением компонента?',
    options: [
      'Контракт можно регистрировать после STARTED без ограничений',
      'Результат всегда хранится в ViewModel',
      'Регистрация до STARTED позволяет корректно доставить результат после пересоздания без ручных requestCode',
      'API отменяет необходимость runtime permissions',
    ],
    correct: 'c',
    explanation: {
      summary: 'Activity Result API связывает типизированный контракт с восстановленной регистрацией.',
      mechanism: 'Registry сохраняет необходимые сведения и после пересоздания доставляет результат зарегистрированному callback. Контракт регистрируют до STARTED.',
      trap: 'API не выдаёт разрешения автоматически и не делает результат частью ViewModel.',
    },
    section: '3.5. Activity Result API',
    tags: ['activity-result', 'lifecycle', 'contracts'],
  }),
  question(11, {
    subtopic: 'Fragment lifecycle',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Почему во Fragment следует наблюдать UI-состояние через viewLifecycleOwner?',
    code: 'viewModel.state.observe(this) { binding.render(it) }',
    options: [
      'Чтобы ViewModel очищалась в onDestroyView()',
      'Чтобы подписка завершалась вместе с View, пока сам Fragment может оставаться в back stack',
      'Чтобы Fragment всегда был RESUMED',
      'Чтобы LiveData работала в фоновом потоке',
    ],
    correct: 'b',
    explanation: {
      summary: 'У Fragment и его View разные жизненные циклы.',
      mechanism: 'После onDestroyView() экземпляр Fragment может продолжать жить. Подписка на lifecycle самого Fragment способна обновить уже уничтоженную View; viewLifecycleOwner ограничивает её временем жизни View.',
      trap: 'Binding также нужно обнулить в onDestroyView(), иначе Fragment удержит всю иерархию View.',
    },
    section: '4.1. Два жизненных цикла',
    tags: ['fragment', 'viewLifecycleOwner', 'binding'],
  }),
  question(12, {
    subtopic: 'Intent',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Что следует использовать для внутреннего запуска неэкспортированного компонента при target Android 14+?',
    options: [
      'Implicit Intent только с action',
      'Explicit Intent с конкретным component/class',
      'Любой broadcast с exported=true',
      'PendingIntent обязательно с FLAG_MUTABLE',
    ],
    correct: 'b',
    explanation: {
      summary: 'Для внутренней коммуникации нужен explicit Intent.',
      mechanism: 'Android 14 ужесточил доставку implicit Intent неэкспортированным компонентам. Явное указание компонента одновременно устраняет неоднозначность и уменьшает поверхность перехвата.',
      trap: 'Делать компонент exported ради внутреннего implicit Intent — ухудшение безопасности.',
    },
    section: '5.1. Explicit и implicit',
    tags: ['intent', 'explicit', 'android-14'],
    version: { asOf: 'Android 14 / API 34', reviewAfter: 'При повышении targetSdk выше API 34' },
  }),
  question(13, {
    subtopic: 'PendingIntent',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'В чём две проблемы этого PendingIntent для уведомлений?',
    code: 'PendingIntent.getActivity(context, 0, intent, 0)',
    options: [
      'Нельзя открывать Activity из уведомления и requestCode должен быть отрицательным',
      'Не задана явная мутабельность; одинаковые requestCode и filterEquals-интенты могут переиспользовать один токен',
      'Нужны только FLAG_MUTABLE и action=null',
      'PendingIntent работает лишь для Service',
    ],
    correct: 'b',
    explanation: {
      summary: 'Нужен безопасный флаг мутабельности и стабильная уникальность токена.',
      mechanism: 'При target API 31+ отсутствие FLAG_IMMUTABLE/FLAG_MUTABLE вызывает IllegalArgumentException. Равенство PendingIntent учитывает Intent.filterEquals и requestCode, но не extras, поэтому разные id только в extras могут коллидировать.',
      trap: 'FLAG_UPDATE_CURRENT обновляет extras уже существующего токена, но не делает два PendingIntent различными.',
      example: 'Используйте FLAG_IMMUTABLE и уникальный requestCode либо уникальный data URI.',
    },
    section: '15.3',
    tags: ['pendingintent', 'immutability', 'code-review'],
    version: { asOf: 'Android 12 / API 31', reviewAfter: 'При изменении правил PendingIntent' },
  }),
  question(14, {
    subtopic: 'App Links',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Что отличает Android App Link от обычного deep link?',
    options: [
      'App Link работает только с custom scheme',
      'App Link верифицирует связь HTTPS-домена с приложением через autoVerify и assetlinks.json',
      'App Link всегда требует FLAG_MUTABLE',
      'App Link не может открывать вложенный экран',
    ],
    correct: 'b',
    explanation: {
      summary: 'App Link — верифицированная HTTPS-ссылка, связанная с приложением владельцем домена.',
      mechanism: 'Intent-filter с android:autoVerify и файл assetlinks.json позволяют системе подтвердить владение. После успешной верификации ссылка открывается в приложении без chooser.',
      trap: 'Обычный deep link может вызвать выбор обработчика; верификация сама по себе не строит осмысленный back stack.',
      example: 'Для глубокого входа стек восстанавливают через TaskStackBuilder или навигационную модель приложения.',
    },
    section: '5.4. Deep links и App Links',
    tags: ['deep-link', 'app-link', 'assetlinks'],
  }),
  question(15, {
    subtopic: 'Background work',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Нужно гарантированно синхронизировать данные при появлении сети, пережив смерть процесса и перезагрузку. Что выбрать?',
    options: ['viewModelScope', 'WorkManager с network constraint', 'Точный AlarmManager каждую минуту', 'Непривязанный Thread'],
    correct: 'b',
    explanation: {
      summary: 'WorkManager предназначен для отложенной гарантированной работы с constraints.',
      mechanism: 'Запрос хранится в БД WorkManager и планируется через системные механизмы. Исполнение происходит в процессе приложения, когда условия выполнены.',
      trap: 'Гарантия не распространяется на force stop: остановленное приложение не получает фоновое исполнение до ручного запуска пользователем.',
    },
    section: '6.1. Матрица выбора',
    tags: ['workmanager', 'constraints', 'sync'],
  }),
  question(16, {
    subtopic: 'Foreground Service',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Какое утверждение о foreground service типа dataSync при target Android 15 верно?',
    options: [
      'Он может работать без ограничения, пока видно уведомление',
      'Он ограничен суммарно 6 часами в сутки; система вызывает Service.onTimeout()',
      'Его всегда можно стартовать из BOOT_COMPLETED',
      'Тип и разрешение foreground service необязательны',
    ],
    correct: 'b',
    explanation: {
      summary: 'Android 15 ввёл суточный лимит для dataSync и mediaProcessing FGS.',
      mechanism: 'По истечении 6 часов для соответствующего типа система вызывает onTimeout(), и сервис должен быстро остановиться. Ограничения запуска из фона и BOOT_COMPLETED также стали строже.',
      trap: 'Постоянное уведомление не превращает FGS в неограниченный демон; длительную отложенную работу следует перепроектировать под WorkManager.',
    },
    section: '6.2. Foreground Service: жёсткие правила',
    tags: ['fgs', 'dataSync', 'timeout'],
    version: { asOf: 'Android 15 / API 35', reviewAfter: 'При следующем повышении targetSdk' },
  }),
  question(17, {
    subtopic: 'WorkManager',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Как WorkManager ведёт себя с периодической работой?',
    options: [
      'Гарантирует запуск ровно по часам с минимальным интервалом 1 минута',
      'Копит каждый пропущенный интервал и запускает их подряд',
      'Минимальный интервал — 15 минут, время неточное, пропущенные интервалы не копятся',
      'Всегда выполняет Worker в отдельном системном процессе',
    ],
    correct: 'c',
    explanation: {
      summary: 'PeriodicWorkRequest — неточный механизм пакетной фоновой работы.',
      mechanism: 'Система учитывает constraints и энергополитику; минимальный период равен 15 минутам. Пропущенные окна не образуют очередь отдельных запусков.',
      trap: 'WorkManager выполняет Worker в процессе приложения; JobScheduler лишь планирует и будит его.',
    },
    section: '6.3. WorkManager',
    tags: ['workmanager', 'periodic-work', 'scheduler'],
  }),
  question(18, {
    subtopic: 'AlarmManager',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Приложению календаря действительно нужны точные пользовательские напоминания. Какой вариант наиболее корректен?',
    options: [
      'Поставить periodic WorkManager раз в минуту',
      'Использовать USE_EXACT_ALARM, если продукт соответствует допустимой категории и политике Play',
      'Всегда просить MANAGE_EXTERNAL_STORAGE',
      'Запустить бесконечный background Service',
    ],
    correct: 'b',
    explanation: {
      summary: 'Exact alarm — привилегия для продуктов, где точность является основной функцией.',
      mechanism: 'USE_EXACT_ALARM предназначен для узких категорий вроде будильников и календарей и контролируется Play. SCHEDULE_EXACT_ALARM для target Android 13+ по умолчанию не выдан.',
      trap: 'WorkManager не гарантирует точное время, а постоянный фоновый сервис нарушает ограничения платформы.',
    },
    section: '6.4. AlarmManager и точное время',
    tags: ['alarmmanager', 'exact-alarm', 'play-policy'],
    version: { asOf: 'Android 13 / API 33', reviewAfter: 'Перед публикацией новой версии в Google Play' },
  }),
  question(19, {
    subtopic: 'Doze и App Standby',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Чем Doze отличается от App Standby buckets?',
    options: [
      'Doze относится только к одному редко используемому приложению, buckets — ко всему устройству',
      'Doze группирует сеть и jobs при покое устройства, а bucket ограничивает конкретное приложение по частоте использования',
      'Оба механизма полностью отключаются foreground Activity',
      'Buckets управляют только разрешениями камеры',
    ],
    correct: 'b',
    explanation: {
      summary: 'Doze описывает состояние устройства, buckets — режим энергобюджета конкретного приложения.',
      mechanism: 'В Doze сеть и задачи переносятся в maintenance windows. App Standby относит приложение к active/working set/frequent/rare/restricted и меняет доступный бюджет jobs и alarms.',
      trap: 'Просьба отключить battery optimization как штатный путь — плохой UX и риск нарушения политики Play.',
    },
    section: '6.5. Doze, App Standby, ограничения фона',
    tags: ['doze', 'app-standby', 'battery'],
  }),
  question(20, {
    subtopic: 'BroadcastReceiver',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Что неправильно в этом onReceive()?',
    code: 'override fun onReceive(context: Context, intent: Intent) {\n    CoroutineScope(Dispatchers.IO).launch { repository.syncAll() }\n}',
    options: [
      'CoroutineScope нельзя создавать в Kotlin',
      'После возврата onReceive() процесс может быть убит; длительную работу нужно поставить в WorkManager',
      'Receiver всегда выполняется в отдельном процессе',
      'Нужно заменить IO на Main',
    ],
    correct: 'b',
    explanation: {
      summary: 'Жизнь произвольной корутины не привязана к гарантиям BroadcastReceiver.',
      mechanism: 'После завершения onReceive() компонент больше не удерживает процесс. Система вправе его завершить, оборвав синхронизацию.',
      trap: 'goAsync() позволяет ненадолго уйти с main thread, но не отменяет таймаут и требует finish(); для долгой работы он не заменяет WorkManager.',
    },
    section: '15.4',
    tags: ['broadcastreceiver', 'workmanager', 'code-review'],
  }),
  question(21, {
    subtopic: 'BroadcastReceiver',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Что требуется при динамической регистрации receiver для несистемного broadcast при target Android 14+?',
    options: [
      'Явно указать RECEIVER_EXPORTED или RECEIVER_NOT_EXPORTED',
      'Всегда объявить QUERY_ALL_PACKAGES',
      'Вызвать goAsync() до registerReceiver()',
      'Зарегистрировать receiver только в manifest',
    ],
    correct: 'a',
    explanation: {
      summary: 'Экспортируемость динамического receiver должна быть осознанно указана.',
      mechanism: 'ContextCompat.registerReceiver принимает RECEIVER_NOT_EXPORTED либо RECEIVER_EXPORTED. Для внутренних событий выбирают NOT_EXPORTED и симметрично снимают регистрацию.',
      trap: 'Широкие implicit broadcasts в manifest в основном ограничены ещё с Android 8.',
    },
    section: '7.1. Почему стал почти бесполезен',
    tags: ['receiver', 'exported', 'registration'],
    version: { asOf: 'Android 14 / API 34', reviewAfter: 'При повышении targetSdk выше API 34' },
  }),
  question(22, {
    subtopic: 'Main thread',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему операция на 20 мс в main thread уже способна вызвать jank на экране 60 Гц?',
    options: [
      'Looper запускает отдельный поток на каждый кадр',
      'Бюджет кадра около 16 мс, а сообщения main queue выполняются между кадрами',
      'Binder запрещает операции дольше 10 мс',
      'Choreographer блокирует все фоновые потоки',
    ],
    correct: 'b',
    explanation: {
      summary: 'Jank возникает, когда главный поток не успевает подготовить кадр к очередному vsync.',
      mechanism: 'Looper последовательно обрабатывает MessageQueue, а Choreographer планирует input, animation и draw. При 60 Гц между vsync около 16 мс, при 120 Гц — около 8 мс.',
      trap: 'Даже «не очень медленная» операция может пропустить кадр; важен не абстрактный runtime, а место в критическом пути main thread.',
    },
    section: '8.1. Как устроен главный поток',
    tags: ['looper', 'choreographer', 'jank'],
  }),
  question(23, {
    subtopic: 'ANR',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Что произойдёт, если после startForegroundService() не вызвать startForeground() примерно за 10 секунд?',
    options: [
      'Обычный input ANR через 5 секунд',
      'ForegroundServiceDidNotStartInTimeException и падение, а не ANR',
      'Система молча переведёт сервис в bound',
      'Только уведомление появится с задержкой',
    ],
    correct: 'b',
    explanation: {
      summary: 'Таймаут продвижения foreground service — отдельный crash-механизм.',
      mechanism: 'Если сервис не вызвал startForeground() вовремя, система выбрасывает ForegroundServiceDidNotStartInTimeException. Это не тот же механизм, что input, receiver, service-start или provider ANR.',
      trap: 'Фраза «на startForeground есть 10 секунд до ANR» технически неверна.',
    },
    section: '8.2. ANR',
    tags: ['anr', 'foreground-service', 'timeout'],
  }),
  question(24, {
    subtopic: 'Binder',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Почему большой Bundle может падать с TransactionTooLargeException, даже если он меньше примерно 1 МБ?',
    options: [
      'Лимит применяется отдельно к каждому полю Bundle и всегда равен 64 КБ',
      'Binder-буфер порядка 1 МБ разделяется всеми одновременными транзакциями процесса',
      'Bundle всегда преобразуется в JSON двойного размера',
      'Parcelable запрещён для списков',
    ],
    correct: 'b',
    explanation: {
      summary: 'Ориентир в 1 МБ — общий буфер процесса, а не гарантированный лимит одной транзакции.',
      mechanism: 'Несколько одновременно выполняющихся Binder-транзакций конкурируют за один ограниченный буфер. Поэтому безопасный payload должен быть существенно меньше теоретического максимума.',
      trap: 'Parcelable эффективнее Serializable, но не отменяет копирование и размер Binder-транзакции.',
    },
    section: '8.3. Binder',
    tags: ['binder', 'bundle', 'transaction-too-large'],
  }),
  question(25, {
    subtopic: 'Binder IPC',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'AIDL-сервис выполняет долгий блокирующий запрос прямо внутри входящего метода. Какой системный риск это создаёт?',
    options: [
      'Метод автоматически переносится в main thread клиента',
      'Занимаются потоки ограниченного Binder pool, и новые IPC-вызовы к процессу начинают ждать',
      'AIDL превращается в Messenger',
      'Система увеличивает Binder pool без ограничений',
    ],
    correct: 'b',
    explanation: {
      summary: 'Входящие Binder-транзакции обслуживает ограниченный пул потоков процесса.',
      mechanism: 'Если обработчики блокируются, пул порядка десятков потоков исчерпывается, и IPC к процессу встаёт в очередь. Метод должен быстро передать работу собственному executor.',
      trap: 'oneway возвращает клиенту управление без ожидания, но не делает тяжёлую серверную работу бесплатной и не допускает return/out-параметры.',
    },
    section: '8.3. Binder',
    tags: ['aidl', 'binder-pool', 'ipc'],
  }),
  question(26, {
    subtopic: 'ContentProvider',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'Как безопасно передать другому приложению файл из внутреннего каталога?',
    options: [
      'Передать file:// URI и chmod 777',
      'Использовать FileProvider, content:// URI и временный FLAG_GRANT_READ_URI_PERMISSION',
      'Скопировать путь в extras без URI',
      'Запросить QUERY_ALL_PACKAGES',
    ],
    correct: 'b',
    explanation: {
      summary: 'FileProvider выдаёт контролируемый content URI вместо раскрытия файлового пути.',
      mechanism: 'Получатель читает файл через ContentResolver, а временный URI grant даёт ровно необходимое право. file:// для межприложенческого обмена запрещён.',
      trap: 'Открывать глобальные файловые права ради одного share-сценария небезопасно.',
    },
    section: '8.4. ContentProvider и FileProvider',
    tags: ['fileprovider', 'content-uri', 'uri-permission'],
  }),
  question(27, {
    subtopic: 'Permissions',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой дизайн runtime permission считается корректным?',
    options: [
      'Запросить все dangerous permissions на первом экране',
      'Запросить в момент действия, объяснить цель и сохранить полезную деградацию при отказе',
      'Считать выданное разрешение постоянным до удаления приложения',
      'При отказе завершить приложение',
    ],
    correct: 'b',
    explanation: {
      summary: 'Разрешение запрашивают контекстно и не делают обязательным для несвязанных функций.',
      mechanism: 'Пользователь может отказать, выбрать приблизительную геолокацию, одноразовый доступ или потерять grant из-за auto-reset. Код проверяет право в момент использования.',
      trap: 'Background location запрашивается отдельным вторым шагом и дополнительно контролируется Play.',
    },
    section: '9.2. Правила работы с runtime-разрешениями',
    tags: ['permissions', 'rationale', 'privacy'],
  }),
  question(28, {
    subtopic: 'Privacy',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Пользователю нужно выбрать несколько фотографий для отправки. Какой подход предпочтителен?',
    options: [
      'Запросить MANAGE_EXTERNAL_STORAGE',
      'Запросить постоянный READ_MEDIA_IMAGES для всей галереи',
      'Использовать системный Photo Picker и получить доступ только к выбранным элементам',
      'Сканировать общий каталог напрямую',
    ],
    correct: 'c',
    explanation: {
      summary: 'Системный picker реализует принцип минимального доступа.',
      mechanism: 'Photo Picker возвращает выбранные пользователем URI без широкого media permission. Приложение не получает постоянный доступ ко всей библиотеке.',
      trap: 'READ_MEDIA_IMAGES технически шире необходимого и хуже соответствует современному privacy-дизайну.',
    },
    section: '9.3. Тренд: доступ к выборке вместо доступа ко всему',
    tags: ['photo-picker', 'privacy', 'media'],
  }),
  question(29, {
    subtopic: 'Storage',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой набор соответствий хранилищ корректен?',
    options: [
      'Настройки — Room; произвольный файл пользователя — cacheDir; общие фото — SharedPreferences',
      'Настройки — DataStore; структурированные данные — Room; общие медиа — MediaStore; произвольные документы — SAF',
      'Все данные — MANAGE_EXTERNAL_STORAGE',
      'Настройки — ContentProvider; база — Bundle; документы — ViewModel',
    ],
    correct: 'b',
    explanation: {
      summary: 'Инструмент выбирается по модели данных и владению файлом.',
      mechanism: 'DataStore даёт асинхронные транзакционные настройки, Room — запросы и схему, MediaStore — общие media collections, SAF — выбранные пользователем документы.',
      trap: 'cacheDir может быть очищен системой в любой момент; SharedPreferences имеет блокирующее первое чтение и не даёт полноценной транзакционной модели.',
    },
    section: '10.1. Что выбрать',
    tags: ['datastore', 'room', 'mediastore', 'saf'],
  }),
  question(30, {
    subtopic: 'Notifications',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Можно ли после создания notification channel программно повысить его importance и заменить звук?',
    options: [
      'Да, при каждом запуске createNotificationChannel перезаписывает настройки',
      'Да, если удалить канал и создать тот же id заново',
      'Нет; пользователь контролирует importance и звук, а система помнит настройки даже после пересоздания того же id',
      'Нет только на Android 13',
    ],
    correct: 'c',
    explanation: {
      summary: 'Поведенческие настройки канала после создания принадлежат пользователю.',
      mechanism: 'Приложение может обновлять имя, описание и группу, но не importance/звук. Удаление и создание того же id не сбрасывает сохранённые системные настройки.',
      trap: 'Новый id технически создаст новый канал, но пользователь потеряет прежние настройки; схему каналов нужно проектировать заранее.',
    },
    section: '11. Уведомления',
    tags: ['notifications', 'channels', 'importance'],
    version: { asOf: 'Android 8 / API 26', reviewAfter: 'При изменении notification UX' },
  }),
  question(31, {
    subtopic: 'Notifications',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Уведомление должно открыть экран приложения. Какая реализация соответствует современным ограничениям?',
    options: [
      'PendingIntent ведёт в BroadcastReceiver, который затем стартует Activity',
      'PendingIntent ведёт прямо в Activity и при необходимости реконструирует back stack',
      'Service получает click и вызывает startActivity без PendingIntent',
      'Уведомление всегда использует mutable PendingIntent',
    ],
    correct: 'b',
    explanation: {
      summary: 'Notification trampoline через receiver/service запрещён.',
      mechanism: 'С Android 12 запуск Activity из промежуточного BroadcastReceiver или Service блокируется. Content intent должен открывать Activity напрямую, обычно immutable PendingIntent.',
      trap: 'После Android 13 POST_NOTIFICATIONS является runtime permission, поэтому продукт обязан учитывать, что уведомление не будет показано.',
    },
    section: '11. Уведомления',
    tags: ['notification', 'trampoline', 'pendingintent'],
    version: { asOf: 'Android 12 / API 31; Android 13 / API 33', reviewAfter: 'При повышении targetSdk' },
  }),
  question(32, {
    subtopic: 'Edge-to-edge',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'При target API 36 нижняя кнопка оказалась под жестовой панелью. Каково правильное исправление?',
    code: 'override fun onCreate(savedInstanceState: Bundle?) {\n    super.onCreate(savedInstanceState)\n    setContentView(binding.root)\n}',
    options: [
      'Вернуть windowOptOutEdgeToEdgeEnforcement=true',
      'Добавить постоянный padding 48dp',
      'Обрабатывать WindowInsets для systemBars/ime/cutout и применять актуальные отступы',
      'Заблокировать портретную ориентацию',
    ],
    correct: 'c',
    explanation: {
      summary: 'При target API 36 edge-to-edge обязателен, поэтому UI должен реагировать на insets.',
      mechanism: 'Размеры системных областей меняются между режимами навигации, клавиатурой и вырезами. WindowInsetsCompat или Compose WindowInsets дают фактические значения.',
      trap: 'Фиксированный padding не покрывает разные устройства, а opt-out для API 36 больше не работает.',
    },
    section: '15.6',
    tags: ['edge-to-edge', 'window-insets', 'code-review'],
    version: { asOf: 'Android 16 / API 36', reviewAfter: 'При следующем обновлении window behavior' },
  }),
  question(33, {
    subtopic: 'Predictive back',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Callback predictive back зарегистрирован с enabled=false, затем пользователь ввёл несохранённый текст. Что нужно сделать?',
    options: [
      'Ничего: enabled автоматически наблюдает за ViewModel',
      'Обновить callback.isEnabled при изменении состояния',
      'Перехватить KEYCODE_BACK',
      'Переопределить только Activity.onBackPressed()',
    ],
    correct: 'b',
    explanation: {
      summary: 'enabled при регистрации — обычное значение, а не реактивная привязка.',
      mechanism: 'Создайте OnBackPressedCallback и меняйте isEnabled из наблюдения за состоянием. Это корректно интегрируется с dispatcher и predictive back.',
      trap: 'При target API 36 onBackPressed() и KEYCODE_BACK больше не являются надёжными точками перехвата.',
    },
    section: '12.2. Predictive back',
    tags: ['predictive-back', 'onbackpresseddispatcher', 'state'],
    version: { asOf: 'Android 16 / API 36', reviewAfter: 'При повышении targetSdk выше API 36' },
  }),
  question(34, {
    subtopic: 'Adaptive layouts',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Что произойдёт с screenOrientation="portrait" при target API 37 на экране sw600dp+?',
    options: [
      'Портрет всегда останется заблокирован',
      'Ограничение игнорируется, и opt-out адаптивности уже недоступен',
      'Activity завершится с SecurityException',
      'Правило действует только для игр',
    ],
    correct: 'b',
    explanation: {
      summary: 'На больших экранах адаптивность становится обязательной.',
      mechanism: 'Для target API 36 система игнорирует ограничения ориентации/aspect/resizability на sw600dp+ с временным opt-out. На API 37 этот opt-out отменён.',
      trap: 'Игры относятся к исключениям, а не к единственной затронутой категории.',
      example: 'Используйте WindowSizeClass, сохраняйте state при resize и тестируйте multi-window.',
    },
    section: '12.3. Ориентация и адаптивность: главное изменение последних версий',
    tags: ['adaptive', 'orientation', 'large-screens'],
    version: { asOf: 'Android 17 / API 37', reviewAfter: 'До финализации Android 17 behavior changes' },
  }),
  question(35, {
    subtopic: 'Multi-window',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'В split-screen две Activity одновременно находятся в RESUMED. По какому сигналу следует управлять эксклюзивной камерой?',
    options: [
      'Только onResume()/onPause()',
      'onTopResumedActivityChanged()',
      'Application.onLowMemory()',
      'BroadcastReceiver CONNECTIVITY_CHANGE',
    ],
    correct: 'b',
    explanation: {
      summary: 'RESUMED больше не означает, что Activity единственная и находится в настоящем фокусе.',
      mechanism: 'Multi-resume допускает несколько RESUMED Activity. onTopResumedActivityChanged() сообщает, какая из них получила top-resumed статус для эксклюзивных ресурсов.',
      trap: 'Захват камеры только в onResume() может конфликтовать со вторым видимым окном.',
    },
    section: '12.4. Multi-window и Picture-in-Picture',
    tags: ['multi-window', 'multi-resume', 'camera'],
  }),
  question(36, {
    subtopic: 'Picture-in-Picture',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой подход к PiP для видео предпочтителен на Android 12+?',
    options: [
      'Вручную вызывать enterPictureInPictureMode() только из onUserLeaveHint()',
      'Включить setAutoEnterEnabled(true), адаптировать UI в onPictureInPictureModeChanged() и не останавливать видео лишь из-за onPause()',
      'Рисовать собственные View-кнопки поверх PiP',
      'Остановить плеер при любом onPause()',
    ],
    correct: 'b',
    explanation: {
      summary: 'Auto-enter даёт плавный системный переход, а жизненный цикл PiP не равен полной невидимости.',
      mechanism: 'Activity остаётся видимой в маленьком окне. Управление скрывают при изменении PiP mode, а действия задают через ограниченный набор RemoteAction.',
      trap: 'onPause() не означает, что пользователь перестал видеть PiP; безусловная остановка ломает основной сценарий.',
    },
    section: '12.4. Multi-window и Picture-in-Picture',
    tags: ['pip', 'video', 'lifecycle'],
    version: { asOf: 'Android 12 / API 31', reviewAfter: 'При изменении PiP API' },
  }),
  question(37, {
    subtopic: 'SDK versions',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Как правильно соотносятся minSdk, targetSdk и compileSdk?',
    options: [
      'targetSdk задаёт минимальную установку, minSdk — behavior changes',
      'minSdk задаёт минимум установки, targetSdk принимает поведенческие изменения, compileSdk задаёт SDK компиляции и не должен быть ниже targetSdk',
      'compileSdk автоматически повышает minSdk',
      'Все три значения обязаны быть одинаковыми',
    ],
    correct: 'b',
    explanation: {
      summary: 'Три SDK-числа отвечают за разные границы совместимости.',
      mechanism: 'minSdk ограничивает установку, targetSdk включает target-gated behavior changes, compileSdk определяет доступные при компиляции API. Повышение targetSdk не повышает minSdk.',
      trap: 'Для совместимости предпочтительны AndroidX-обёртки, а не россыпь ручных SDK_INT-проверок.',
    },
    section: '13.1. Три числа',
    tags: ['minsdk', 'targetsdk', 'compilesdk'],
  }),
  question(38, {
    subtopic: 'Google Play',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'У приложения есть нативные .so и target Android 15+. Что важно для требования Google Play о 16 КБ страницах памяти?',
    options: [
      'Требование касается только Kotlin bytecode',
      'Достаточно повысить minSdk до 35',
      'Нужно проверить ELF LOAD alignment; типичный путь — AGP 8.5.1+ и NDK r28+ либо явные флаги для старых NDK',
      'Нужно перевести все Parcelable в Serializable',
    ],
    correct: 'c',
    explanation: {
      summary: 'Риск 16 КБ страниц находится в нативных библиотеках, включая зависимости SDK.',
      mechanism: 'AGP 8.5.1+ корректно упаковывает библиотеки, а NDK r28+ по умолчанию собирает совместимые .so. Для r27 включают flexible page sizes; ELF LOAD-сегменты должны иметь alignment 2**14.',
      trap: 'Чистые Kotlin/Java-приложения совместимы автоматически, но одна транзитивная .so меняет ситуацию.',
    },
    section: '13.2. Требования Google Play',
    tags: ['google-play', '16kb-pages', 'ndk'],
    version: { asOf: 'Требование Google Play с 1 ноября 2025', reviewAfter: 'Перед каждым релизом с обновлёнными native SDK' },
  }),
  question(39, {
    subtopic: 'Jetpack',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какова наиболее точная роль AndroidX в платформенном коде?',
    options: [
      'Это только набор UI-виджетов для новых Android',
      'Это слой согласованного поведения на разных версиях ОС, который инкапсулирует совместимость и многие SDK_INT-ветвления',
      'Он заменяет Android framework и Binder',
      'Он нужен только Compose-приложениям',
    ],
    correct: 'b',
    explanation: {
      summary: 'AndroidX предоставляет совместимые контракты поверх различий версий платформы.',
      mechanism: 'Lifecycle, Activity Result, SavedState, WorkManager, WindowInsetsCompat и другие библиотеки дают единые API и backport-поведение там, где это возможно.',
      trap: 'Jetpack не отменяет знание behavior changes: targetSdk всё равно может менять платформенную семантику.',
      example: 'ContextCompat и WindowInsetsCompat обычно лучше ручных веток Build.VERSION.SDK_INT.',
    },
    section: '14. Jetpack как часть SDK',
    tags: ['androidx', 'jetpack', 'compatibility'],
  }),
  question(40, {
    subtopic: 'Code review',
    difficulty: 'expert',
    kind: 'code',
    prompt: 'Какой главный набор проблем следует отметить на ревью этого Application?',
    code: 'class App : Application() {\n    override fun onCreate() {\n        super.onCreate()\n        Analytics.init(this)\n        Ads.init(this)\n        Maps.init(this)\n        prefs = getSharedPreferences("app", MODE_PRIVATE)\n    }\n}',
    options: [
      'Application.onCreate() выполняется после первого кадра, поэтому проблем нет',
      'Тяжёлые SDK и первое блокирующее чтение prefs удлиняют cold start; инициализацию следует сделать ленивой, настройки перенести в DataStore',
      'Нужно перенести всё в Activity.onResume() при каждом показе',
      'Нужно создать отдельный process для каждого SDK без других изменений',
    ],
    correct: 'b',
    explanation: {
      summary: 'Application.onCreate() находится на критическом пути холодного старта до первого кадра.',
      mechanism: 'Последовательная инициализация SDK и синхронная загрузка SharedPreferences увеличивают TTID и могут способствовать ANR. Оставляют только обязательный минимум, остальное запускают по требованию или контролируемо через androidx.startup; настройки читают асинхронно из DataStore.',
      trap: 'Безусловный перенос в onResume() создаст повторную работу и ухудшит каждый вход; отдельные процессы добавят память и повторную инициализацию Application.',
      verification: 'Измерьте cold start в Perfetto и включите StrictMode для дисковых операций на main thread.',
    },
    section: '15.1',
    tags: ['application', 'startup', 'code-review', 'datastore'],
  }),
]
