import type { Question } from '../domain/models'

export const composeQuestions: Question[] = [
  {
    id: 'compose-001',
    topicId: 'compose',
    subtopic: 'compiler-runtime',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Что точнее всего описывает преобразование обычной `@Composable`-функции Compose Compiler?',
    options: [
      { id: 'a', text: 'Она компилируется в подкласс Android `View` с методом `onDraw`' },
      { id: 'b', text: 'В неё добавляются служебные параметры вроде `Composer` и changed-масок, группы, проверки skipping и restart-лямбда' },
      { id: 'c', text: 'Она превращается только в `suspend`-функцию и всегда запускается в корутине' },
      { id: 'd', text: 'Её тело сохраняется как строка и интерпретируется runtime при каждом кадре' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Compose Compiler меняет соглашение вызова composable и встраивает протокол взаимодействия с runtime.',
      mechanism: 'Скрытый `Composer` сопоставляет текущее выполнение с прошлой Composition, changed/dirty-маски передают сведения об аргументах, а restart group и update scope позволяют повторно исполнить только инвалидированный участок.',
      trap: 'Сгенерированные имена и точный формат флагов — implementation detail; на них нельзя строить прикладной код.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '2.1. Как примерно преобразуется composable?' },
    tags: ['compiler', 'composer', 'dirty-flags', 'recomposition'],
  },
  {
    id: 'compose-002',
    topicId: 'compose',
    subtopic: 'compiler-runtime',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Как правильно разделены роли `Composer`, `Recomposer` и `Applier`?',
    options: [
      { id: 'a', text: '`Composer` планирует кадры, `Recomposer` рисует Canvas, `Applier` хранит `remember`' },
      { id: 'b', text: '`Composer` только сравнивает `equals`, а два остальных объекта нужны исключительно Preview' },
      { id: 'c', text: '`Composer` записывает группы и change list, `Recomposer` планирует invalidations и effects, `Applier` применяет операции к целевому дереву' },
      { id: 'd', text: 'Все три названия обозначают один объект на разных фазах кадра' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Это три разные части протокола Composition.',
      mechanism: '`Composer` ведёт группы, slots и зависимости; `Recomposer` получает invalidations, координируется с frame clock и запускает работу; `Applier` реализует операции вставки, удаления и перемещения узлов конкретного backend.',
      trap: 'Compose Runtime не привязан исключительно к Android View: целевое дерево определяется реализацией `Applier`.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '2.4. Что такое Composer, Recomposer и Applier?' },
    tags: ['composer', 'recomposer', 'applier', 'runtime'],
  },
  {
    id: 'compose-003',
    topicId: 'compose',
    subtopic: 'slot-table',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'К чему на самом деле привязано значение, созданное `remember`?',
    options: [
      { id: 'a', text: 'К имени локальной переменной в исходном Kotlin-коде' },
      { id: 'b', text: 'К классу Activity, где впервые была вызвана функция' },
      { id: 'c', text: 'К логической позиции group/slot в Composition' },
      { id: 'd', text: 'К имени composable-функции без учёта call site' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: '`remember` использует positional memoization в SlotTable.',
      mechanism: 'SlotTable хранит иерархию групп, ключи, anchors, remembered values и данные restart scopes. Runtime находит значение по логической позиции вызова, сформированной структурой групп.',
      trap: 'Перестановка однотипных вызовов без стабильного `key` может связать прежнее состояние с другой бизнес-сущностью.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '2.5. Что хранится в SlotTable?' },
    tags: ['slot-table', 'remember', 'positional-identity'],
  },
  {
    id: 'compose-004',
    topicId: 'compose',
    subtopic: 'identity',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'В цикле список карточек меняет порядок, а внутри каждой карточки есть `remember` и `LaunchedEffect`. Что обеспечивает корректное сохранение identity при reorder?',
    options: [
      { id: 'a', text: 'Обернуть карточку в `key(item.id) { ... }` со стабильным уникальным среди siblings ID' },
      { id: 'b', text: 'Использовать текущий индекс как `key`, потому что он всегда уникален' },
      { id: 'c', text: 'Создавать новый случайный UUID при каждой рекомпозиции' },
      { id: 'd', text: 'Пометить модель `@Stable`, не задавая key' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Стабильный business key добавляет data identity к positional identity.',
      mechanism: 'При reorder runtime может переместить группу вместе с remembered state, effect lifetime, restart scope и UI nodes, если узнаёт сущность по стабильному ключу.',
      trap: 'Индекс описывает позицию, а не сущность; случайный ключ, напротив, уничтожает identity при каждом выполнении.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '3.3. Для чего нужен key?' },
    tags: ['key', 'identity', 'effects', 'reorder'],
  },
  {
    id: 'compose-005',
    topicId: 'compose',
    subtopic: 'snapshots',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Как snapshot state связывает изменение значения с точечным обновлением UI?',
    options: [
      { id: 'a', text: 'Runtime каждый кадр рекурсивно сравнивает всё UI-дерево с model graph' },
      { id: 'b', text: 'Read observer регистрирует зависимость state от scope/фазы, а публикация записи инвалидирует зарегистрированных потребителей' },
      { id: 'c', text: 'Каждый `MutableState` хранит прямую ссылку на Activity и вызывает `recreate()`' },
      { id: 'd', text: 'Обновление возможно только после ручного вызова `notifyDataSetChanged()`' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Compose отслеживает чтения snapshot state, а не выполняет глобальный diff дерева.',
      mechanism: 'State records дают versioned view; read observer строит зависимости, mutation policy проверяет эквивалентность, а apply/write notifications инвалидируют только прочитавшие значение scope или фазу.',
      trap: 'Обычное изменяемое поле, не являющееся snapshot-aware state, такой зависимости не создаёт.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '4.2. Что такое snapshot?' },
    tags: ['snapshots', 'state-records', 'invalidation', 'mvcc'],
  },
  {
    id: 'compose-006',
    topicId: 'compose',
    subtopic: 'snapshots',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Что произойдёт при присваивании нового экземпляра в `mutableStateOf`, если его mutation policy считает старое и новое значения эквивалентными?',
    options: [
      { id: 'a', text: 'Наблюдаемого изменения и соответствующей invalidation не будет' },
      { id: 'b', text: 'Всегда произойдёт полная рекомпозиция от корня Activity' },
      { id: 'c', text: 'Значение применится только после поворота экрана' },
      { id: 'd', text: 'Runtime автоматически переключится на `neverEqualPolicy`' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Mutation policy определяет, считается ли запись изменением для наблюдателей.',
      mechanism: 'По умолчанию часто используется структурная эквивалентность; также доступны referential, never-equal и custom policy. Эквивалентная запись не требует уведомлять потребителей.',
      trap: 'Custom policy, игнорирующая значимое для UI поле, создаёт stale UI; `neverEqualPolicy` может порождать лишнюю работу.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '4.3. Mutation policies' },
    tags: ['snapshots', 'mutation-policy', 'state'],
  },
  {
    id: 'compose-007',
    topicId: 'compose',
    subtopic: 'state',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Почему после `users.value.add(newUser)` UI может не обновиться?',
    code: {
      language: 'kotlin',
      value: 'val users = mutableStateOf(mutableListOf<User>())\nusers.value.add(newUser)',
    },
    options: [
      { id: 'a', text: '`MutableState` запрещает хранить generic-типы' },
      { id: 'b', text: 'Изменился обычный `MutableList` внутри значения, но setter `value` и snapshot write не произошли' },
      { id: 'c', text: '`add` всегда выполняется асинхронно после draw' },
      { id: 'd', text: 'Для списков Compose обновляет UI только после process recreation' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Snapshot system не наблюдает внутреннюю мутацию произвольного mutable object.',
      mechanism: 'Нужно присвоить новую immutable-модель, например `users.value = users.value + newUser`, либо использовать `SnapshotStateList` с понятным owner, где операция коллекции сама является snapshot write.',
      trap: 'Обернуть `MutableList` в data class недостаточно: внутреннее изменение всё равно останется ненаблюдаемым.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '22.1. Почему UI не обновился?' },
    tags: ['state', 'mutable-list', 'snapshot-state-list', 'code-trap'],
  },
  {
    id: 'compose-008',
    topicId: 'compose',
    subtopic: 'phases',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Анимируется только визуальный сдвиг элемента, который не должен менять bounds соседей. Где лучше прочитать часто меняющийся offset?',
    options: [
      { id: 'a', text: 'В аргументе `Modifier.offset(x = offset.dp)`, чтобы читать его в composition' },
      { id: 'b', text: 'В `graphicsLayer { translationX = offset }`, чтобы ограничиться draw/compositing work' },
      { id: 'c', text: 'В `rememberSaveable`, чтобы каждый кадр писать offset в Bundle' },
      { id: 'd', text: 'В ViewModel с вызовом `Activity.recreate()` на каждом изменении' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Часто меняющийся state следует читать в самой поздней фазе, достаточной для требуемого поведения.',
      mechanism: 'Composition read вызывает recomposition, placement read — replace, draw/layer read — визуальное обновление. Для чистого transform `graphicsLayer` избегает перестройки структуры и remeasure.',
      trap: 'Draw transform не меняет layout bounds, hit geometry соседей и scroll range; если они должны измениться, нужна layout-фаза.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '9.2. Deferred state read' },
    tags: ['phases', 'deferred-read', 'graphics-layer', 'performance'],
  },
  {
    id: 'compose-009',
    topicId: 'compose',
    subtopic: 'recomposition',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Чем `restartable` composable отличается от `skippable`?',
    options: [
      { id: 'a', text: '`restartable` можно перезапустить с собственного scope, а `skippable` можно целиком не выполнять при неизменившихся входах' },
      { id: 'b', text: '`restartable` обязательно возвращает значение, а `skippable` обязательно возвращает `Unit`' },
      { id: 'c', text: '`restartable` работает только в Preview, а `skippable` — только на устройстве' },
      { id: 'd', text: 'Разницы нет: это два имени одной compiler-аннотации' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Restart и skip — независимые свойства generated composable.',
      mechanism: 'Restart group создаёт точку входа для recomposition. Skipping означает, что при достижении вызова runtime может пропустить тело, если dirty flags и stability/identity comparisons позволяют это.',
      trap: 'Non-skippable функция выполняется лишь если родитель дошёл до её вызова; это не означает полную рекомпозицию приложения.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '2.3. Restartable и skippable — одно и то же?' },
    tags: ['restartable', 'skippable', 'compiler', 'recomposition'],
  },
  {
    id: 'compose-010',
    topicId: 'compose',
    subtopic: 'stability',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Что изменяет strong skipping для composable с нестабильным параметром?',
    options: [
      { id: 'a', text: 'Делает сам тип immutable и наблюдает любые внутренние мутации' },
      { id: 'b', text: 'Позволяет restartable composable быть skippable, сравнивая unstable-параметр по identity, и автоматически memoizes многие лямбды' },
      { id: 'c', text: 'Запрещает передавать `List` в composable' },
      { id: 'd', text: 'Всегда сравнивает unstable-параметры глубоким `equals`' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Strong skipping меняет стратегию skipping, но не контракт модели.',
      mechanism: 'Stable-параметры обычно сравниваются по equality, unstable — по `===`. Поэтому тот же instance может позволить skip, а новый равный по содержимому `List` считается изменившимся.',
      trap: 'Внутренняя мутация того же объекта без observable state write может вообще не вызвать invalidation.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '6.4. Что делает strong skipping?' },
    tags: ['strong-skipping', 'stability', 'identity', 'compiler'],
    version: { asOf: '2026-08-17 (Kotlin 2.0.20+: strong skipping enabled by default)', reviewAfter: '2027-02-17' },
  },
  {
    id: 'compose-011',
    topicId: 'compose',
    subtopic: 'stability',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Каков главный риск этой модели?',
    code: {
      language: 'kotlin',
      value: '@Immutable\ndata class FeedState(val items: MutableList<Item>)',
    },
    options: [
      { id: 'a', text: 'Аннотация автоматически скопирует список при каждой записи' },
      { id: 'b', text: 'Код не скомпилируется, потому что `@Immutable` запрещён для data class' },
      { id: 'c', text: 'Аннотация ложно обещает неизменность, и skipping может скрыть внутреннюю мутацию от UI' },
      { id: 'd', text: 'Единственный риск — более медленная сериализация Parcelable' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Stability-аннотации — обещание разработчика, а не runtime-проверка.',
      mechanism: 'Compiler использует контракт для решений о skipping. Если публично значимое состояние меняется без snapshot notification, runtime вправе пропустить вызов и оставить старый UI.',
      trap: 'Ложный `@Immutable` опаснее лишней рекомпозиции: он создаёт correctness bug.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '22.11. Что не так с ложным @Immutable?' },
    tags: ['immutable', 'stability', 'code-trap', 'stale-ui'],
  },
  {
    id: 'compose-012',
    topicId: 'compose',
    subtopic: 'state',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Что произойдёт при изменении `initialText` после первого входа `Editor` в Composition?',
    code: {
      language: 'kotlin',
      value: '@Composable\nfun Editor(initialText: String) {\n    var text by remember { mutableStateOf(initialText) }\n}',
    },
    options: [
      { id: 'a', text: '`text` автоматически синхронизируется с каждым новым параметром' },
      { id: 'b', text: '`text` сохранит исходное значение, пока identity не покинет Composition или не будет явно сброшена' },
      { id: 'c', text: 'Runtime объединит обе строки через mutation policy' },
      { id: 'd', text: 'Произойдёт process recreation' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`remember` без ключа выполняет calculation только при первом входе данной identity.',
      mechanism: 'Контракт должен явно определить: это initial value, полностью controlled state от parent или state, сбрасываемый через `remember(entityId)`.',
      trap: 'Безусловная синхронизация effect-ом может перетирать пользовательский ввод; сначала определяют owner и семантику обновления.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '5.2. Почему remember { mutableStateOf(parameter) } часто ошибочен?' },
    tags: ['remember', 'state-owner', 'initial-value', 'code-trap'],
  },
  {
    id: 'compose-013',
    topicId: 'compose',
    subtopic: 'state-restoration',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Что уместнее всего хранить через `rememberSaveable`?',
    options: [
      { id: 'a', text: 'Большой список DTO и декодированные Bitmap' },
      { id: 'b', text: 'Ссылку на Repository и открытую сетевую сессию' },
      { id: 'c', text: 'Небольшой UI state: query, выбранный ID или позицию, при необходимости через `Saver`' },
      { id: 'd', text: 'Все бизнес-данные приложения как замену базе данных' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: '`rememberSaveable` сохраняет компактное UI-состояние через saved-state registry.',
      mechanism: 'Saveable-представление переживает configuration recreation и system-driven recreation при наличии Bundle. Несохраняемый тип преобразуется компактным `Saver`.',
      trap: 'Bundle ограничен; durable business data восстанавливают из repository/database по минимальному ключу.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '5.3. rememberSaveable' },
    tags: ['remember-saveable', 'saver', 'process-death', 'bundle'],
  },
  {
    id: 'compose-014',
    topicId: 'compose',
    subtopic: 'derived-state',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Когда `derivedStateOf` даёт содержательную пользу?',
    options: [
      { id: 'a', text: 'Когда snapshot dependency меняется часто, а наблюдаемый производный результат — редко, например scroll offset → пересечение порога' },
      { id: 'b', text: 'Для любой конкатенации двух обычных строковых параметров' },
      { id: 'c', text: 'Чтобы автоматически перенести тяжёлую сортировку на background thread' },
      { id: 'd', text: 'Чтобы сохранить значение после process death' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`derivedStateOf` уменьшает число downstream invalidations, если результат меняется реже входов.',
      mechanism: 'Он сам отслеживает snapshot reads и публикует производный `State`; канонический пример — `firstVisibleItemIndex > 0`.',
      trap: 'Для дешёвого результата, меняющегося с каждым входом, это лишний tracking overhead; обычные не-snapshot параметры без ключей могут дать stale value.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '5.6. derivedStateOf' },
    tags: ['derived-state', 'snapshots', 'scroll', 'performance'],
  },
  {
    id: 'compose-015',
    topicId: 'compose',
    subtopic: 'architecture',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Каков основной критерий выбора владельца state при state hoisting?',
    options: [
      { id: 'a', text: 'Всегда помещать любое состояние в Activity' },
      { id: 'b', text: 'Выбирать минимального общего владельца с нужными lifetime и ответственностью' },
      { id: 'c', text: 'Всегда хранить всё в локальном `remember`' },
      { id: 'd', text: 'Выбирать файл с наименьшим количеством строк кода' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'State поднимают до минимального общего owner, которому он нужен.',
      mechanism: 'Эфемерная механика компонента остаётся локально, screen/business state живёт в ViewModel, durable source of truth — в data layer. Stateless API получает value и intent callback.',
      trap: 'Правила «всё в ViewModel» и «всё в remember» одинаково игнорируют lifetime и ответственность.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '7. State hoisting, UDF и ViewModel' },
    tags: ['state-hoisting', 'udf', 'viewmodel', 'architecture'],
  },
  {
    id: 'compose-016',
    topicId: 'compose',
    subtopic: 'architecture',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Почему на Android-экране обычно предпочитают `collectAsStateWithLifecycle()` вместо `collectAsState()`?',
    options: [
      { id: 'a', text: 'Первый метод автоматически сохраняет весь Flow в Bundle' },
      { id: 'b', text: 'Первый собирает Flow только в подходящем Lifecycle-состоянии и не держит невидимый UI и upstream без необходимости' },
      { id: 'c', text: 'Второй работает только с `LiveData`' },
      { id: 'd', text: 'Первый всегда выполняет collection на IO dispatcher' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Lifecycle-aware collection согласует подписку с видимостью Android UI.',
      mechanism: 'Обычно collection активна начиная с `STARTED`; остановка UI отменяет/приостанавливает потребление согласно API и позволяет `WhileSubscribed` upstream завершить работу.',
      trap: '`collectAsState()` может быть правильным в platform-independent Compose или при lifetime, уже ограниченном другим владельцем.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '7.4. Почему collectAsStateWithLifecycle?' },
    tags: ['flow', 'lifecycle', 'collect-as-state', 'architecture'],
  },
  {
    id: 'compose-017',
    topicId: 'compose',
    subtopic: 'effects',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Как выбрать key для `LaunchedEffect`, который загружает данные конкретного пользователя?',
    options: [
      { id: 'a', text: 'Использовать `userId`, если смена пользователя должна отменить старую и запустить новую операцию' },
      { id: 'b', text: 'Всегда использовать случайный UUID' },
      { id: 'c', text: 'Всегда использовать `Unit`, даже если операция зависит от `userId`' },
      { id: 'd', text: 'Использовать весь новый mutable object graph независимо от его equality' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Effect key выражает identity операции.',
      mechanism: 'При смене key старая coroutine отменяется, затем запускается новая; при выходе call site из Composition coroutine также отменяется.',
      trap: 'Слишком широкий key вызывает лишние рестарты, слишком узкий оставляет effect со stale dependency. `Unit` означает lifetime call site, а не «один раз на приложение».',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '8.2. Как выбирать effect key?' },
    tags: ['launched-effect', 'keys', 'cancellation', 'lifecycle'],
  },
  {
    id: 'compose-018',
    topicId: 'compose',
    subtopic: 'effects',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Таймер не должен перезапускаться при смене callback, но должен вызвать его актуальную версию. Как исправить код?',
    code: {
      language: 'kotlin',
      value: 'LaunchedEffect(Unit) {\n    delay(3_000)\n    onTimeout()\n}',
    },
    options: [
      { id: 'a', text: 'Добавить `onTimeout` в key и всегда перезапускать задержку' },
      { id: 'b', text: 'Получить актуальный callback через `rememberUpdatedState(onTimeout)` и вызвать его внутри прежнего effect' },
      { id: 'c', text: 'Вызвать `onTimeout()` прямо во время composition' },
      { id: 'd', text: 'Сохранить callback через `rememberSaveable` в Bundle' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`rememberUpdatedState` обновляет ссылку для долгоживущего effect, не меняя его identity.',
      mechanism: 'Effect сохраняет lifetime call site, а чтение wrapper-state в момент завершения задержки даёт свежий callback.',
      trap: 'Это не замена key: если dependency меняет саму операцию, например `userId` подписки, старую работу нужно отменить.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '8.3. rememberUpdatedState' },
    tags: ['remember-updated-state', 'launched-effect', 'stale-capture', 'code-trap'],
  },
  {
    id: 'compose-019',
    topicId: 'compose',
    subtopic: 'effects',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой effect подходит для регистрации `LifecycleEventObserver`, который обязательно нужно удалить?',
    options: [
      { id: 'a', text: '`SideEffect`, потому что он предоставляет `onDispose`' },
      { id: 'b', text: '`DisposableEffect(lifecycleOwner)` с удалением observer в `onDispose`' },
      { id: 'c', text: '`derivedStateOf`, потому что он управляет ресурсами' },
      { id: 'd', text: '`rememberSaveable`, потому что observer сериализуем' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`DisposableEffect` задаёт симметричный lifecycle регистрации и cleanup.',
      mechanism: 'При входе или смене key ресурс регистрируется; перед перезапуском и при выходе из Composition вызывается `onDispose`.',
      trap: 'Все dependencies, меняющие регистрацию, должны быть keys либо безопасно читаться через `rememberUpdatedState`.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '8.4. DisposableEffect' },
    tags: ['disposable-effect', 'cleanup', 'lifecycle', 'observer'],
  },
  {
    id: 'compose-020',
    topicId: 'compose',
    subtopic: 'effects',
    difficulty: 'expert',
    kind: 'code',
    prompt: 'Что не так с двойным запуском coroutine?',
    code: {
      language: 'kotlin',
      value: 'val scope = rememberCoroutineScope()\nLaunchedEffect(userId) {\n    scope.launch { load(userId) }\n}',
    },
    options: [
      { id: 'a', text: 'Ничего: внутренняя coroutine гарантированно является дочерней `LaunchedEffect`' },
      { id: 'b', text: 'Внутренняя coroutine принадлежит remembered scope и не отменится при смене key самого effect; тело нужно запускать прямо в `LaunchedEffect`' },
      { id: 'c', text: '`rememberCoroutineScope` нельзя использовать в composable' },
      { id: 'd', text: '`LaunchedEffect` не умеет выполнять suspend-код' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Scope, созданный `rememberCoroutineScope`, живёт до выхода его call site, а не до завершения внешнего effect.',
      mechanism: 'При смене `userId` `LaunchedEffect` отменяется, но job, запущенный в другом scope, не является его дочерним и может продолжить старую работу.',
      trap: '`rememberCoroutineScope` предназначен прежде всего для запуска из event callbacks, например нажатия кнопки.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '22.14. Почему rememberCoroutineScope внутри LaunchedEffect ломает lifetime?' },
    tags: ['remember-coroutine-scope', 'launched-effect', 'structured-concurrency', 'code-trap'],
  },
  {
    id: 'compose-021',
    topicId: 'compose',
    subtopic: 'effects',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какое требование критично для блока `snapshotFlow { ... }`?',
    options: [
      { id: 'a', text: 'Он должен быть чистым: читать snapshot state и возвращать значение без side effects' },
      { id: 'b', text: 'Он обязан записывать хотя бы одно `MutableState` перед каждым emit' },
      { id: 'c', text: 'Он всегда должен выполняться на Main и блокировать кадр' },
      { id: 'd', text: 'Он должен создавать новый `LaunchedEffect` внутри блока' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`snapshotFlow` превращает отслеживаемые snapshot reads в cold Flow.',
      mechanism: 'Блок выполняется в read-only snapshot, зависимости отслеживаются автоматически, а новое неравное значение emit-ится после их изменения.',
      trap: 'Analytics или другой side effect выполняют в downstream collector, а не в блоке чтения.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '5.8. snapshotFlow' },
    tags: ['snapshot-flow', 'flow', 'analytics', 'effects'],
  },
  {
    id: 'compose-022',
    topicId: 'compose',
    subtopic: 'modifiers',
    difficulty: 'basic',
    kind: 'code',
    prompt: 'Как отличается результат двух цепочек modifiers?',
    code: {
      language: 'kotlin',
      value: 'Modifier.padding(16.dp).background(Color.Red)\nModifier.background(Color.Red).padding(16.dp)',
    },
    options: [
      { id: 'a', text: 'Они полностью эквивалентны: порядок modifiers не учитывается' },
      { id: 'b', text: 'В первой фон внутри padding, во второй фон включает padding area' },
      { id: 'c', text: 'В первой padding применяется дважды, во второй — ни разу' },
      { id: 'd', text: 'Разница проявляется только в Preview, но не на устройстве' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Modifier — упорядоченная цепочка обёрток, поэтому порядок является поведением.',
      mechanism: 'Каждый element действует относительно следующего в chain; то же относится к `clickable`, `clip`, `size`, `offset`, draw и semantics.',
      trap: 'Если внешний padding должен входить в hit area, `clickable` располагают до него в цепочке.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '10.1. Почему порядок modifiers важен?' },
    tags: ['modifier', 'order', 'padding', 'drawing'],
  },
  {
    id: 'compose-023',
    topicId: 'compose',
    subtopic: 'layout',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Можно ли в обычном layout pass вызвать `measure()` для одного и того же child дважды?',
    options: [
      { id: 'a', text: 'Да, любое число раз без ограничений' },
      { id: 'b', text: 'Нет; обычный measurement следует single-pass контракту, а специальные задачи требуют другого API' },
      { id: 'c', text: 'Можно только в release build' },
      { id: 'd', text: 'Можно, если child помечен `@Stable`' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Обычный Compose layout измеряет каждого ребёнка один раз за pass.',
      mechanism: 'Parent передаёт constraints, child возвращает допустимый `Placeable`, затем parent выбирает размер и placement. Для иной стратегии существуют intrinsics, `SubcomposeLayout`, lazy APIs и lookahead.',
      trap: 'Повторный `measure()` — не способ «уточнить» размер; runtime защищает single-pass контракт.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '11.3. Можно ли измерить child дважды?' },
    tags: ['layout', 'measurement', 'constraints', 'single-pass'],
  },
  {
    id: 'compose-024',
    topicId: 'compose',
    subtopic: 'layout',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Почему `BoxWithConstraints` в каждой ячейке большого списка может быть дорогим?',
    options: [
      { id: 'a', text: 'Он всегда декодирует изображения на main thread' },
      { id: 'b', text: 'Он использует subcomposition во время layout, добавляя composition work и усложняя skipping' },
      { id: 'c', text: 'Он отключает snapshot system во всём приложении' },
      { id: 'd', text: 'Он принудительно сохраняет каждую ячейку в Bundle' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Subcomposition позволяет строить content после получения constraints, но имеет заметную цену.',
      mechanism: '`SubcomposeLayout` нужен, когда структура действительно зависит от измерений; lazy containers тоже используют этот механизм. Для обычного расположения дешевле `Layout` или готовый primitive.',
      trap: 'Screen-level adaptive решение часто лучше строить на window/adaptive API, а не размножать `BoxWithConstraints` по items.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '11.7. SubcomposeLayout' },
    tags: ['subcompose-layout', 'box-with-constraints', 'layout', 'performance'],
  },
  {
    id: 'compose-025',
    topicId: 'compose',
    subtopic: 'modifiers',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему для нового custom modifier обычно предпочитают `Modifier.Node` вместо `Modifier.composed`?',
    options: [
      { id: 'a', text: '`Modifier.Node` создаёт отдельную Activity для каждого modifier' },
      { id: 'b', text: 'Node переиспользуется, имеет явный lifecycle и может инвалидировать конкретную фазу без composable-группы на каждый вызов' },
      { id: 'c', text: '`Modifier.composed` не поддерживает Kotlin' },
      { id: 'd', text: 'Node нужен только для изменения цвета темы' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`Modifier.Node` — долгоживущий объект в modifier tree с capability-интерфейсами.',
      mechanism: '`ModifierNodeElement` создаёт и обновляет node; node имеет attach/detach/reset lifecycle и может реализовать draw, layout, input или semantics capability с меньшим количеством аллокаций.',
      trap: 'Один экземпляр node нельзя одновременно вставлять в несколько chains; корректные `equals/hashCode` element важны для update.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '10.5. Почему Modifier.Node предпочтительнее Modifier.composed?' },
    tags: ['modifier-node', 'custom-modifier', 'allocations', 'lifecycle'],
  },
  {
    id: 'compose-026',
    topicId: 'compose',
    subtopic: 'lazy-lists',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Почему индекс — плохой `key` для элементов `LazyColumn`, если возможна вставка в начало?',
    options: [
      { id: 'a', text: 'Индекс нельзя преобразовать в `Any`' },
      { id: 'b', text: 'Индексы существующих элементов сдвинутся, и remembered state/animations могут сопоставиться с другими сущностями' },
      { id: 'c', text: 'Индекс всегда дублируется внутри одного списка' },
      { id: 'd', text: 'Compose запрещает числовые keys' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Lazy key должен описывать бизнес-сущность, а не её текущую позицию.',
      mechanism: 'Стабильный ID помогает сохранить remembered/saveable state, корректно обработать reorder, переиспользовать composition и анимировать placement.',
      trap: 'Key — часть correctness: ошибка проявляется как «переехавший» input, expanded state или effect, а не только как потеря производительности.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '12.2. Зачем key в items?' },
    tags: ['lazy-column', 'key', 'identity', 'state'],
  },
  {
    id: 'compose-027',
    topicId: 'compose',
    subtopic: 'lazy-lists',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Для чего `contentType` нужен в гетерогенной lazy-ленте?',
    options: [
      { id: 'a', text: 'Чтобы сериализовать каждый item в JSON' },
      { id: 'b', text: 'Чтобы runtime переиспользовал item composition между совместимыми структурами одного типа' },
      { id: 'c', text: 'Чтобы автоматически создать уникальный business key' },
      { id: 'd', text: 'Чтобы отключить prefetch для всех элементов' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`contentType` сообщает, какие item compositions структурно совместимы для reuse.',
      mechanism: 'В ленте статей, рекламы и заголовков runtime может выбирать подходящий reusable content вместо попытки переиспользовать несовместимую структуру.',
      trap: '`contentType` не заменяет `key`: первое описывает тип структуры, второе — identity конкретной сущности.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '12.3. Для чего contentType?' },
    tags: ['lazy-list', 'content-type', 'reuse', 'performance'],
  },
  {
    id: 'compose-028',
    topicId: 'compose',
    subtopic: 'performance',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Как наиболее доказательно расследовать jank при скролле lazy-списка?',
    options: [
      { id: 'a', text: 'Посчитать recompositions в debug и сразу добавить `remember` повсюду' },
      { id: 'b', text: 'Воспроизвести release/profileable scenario, измерить Macrobenchmark/frame timing, изучить Perfetto и проверить конкретную фазу, keys, allocations и decoding' },
      { id: 'c', text: 'Заменить все `val` на `var` и сравнить визуально' },
      { id: 'd', text: 'Ориентироваться только на FPS из Preview' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Оптимизацию начинают с пользовательской метрики и trace, а не с числа вызовов composable.',
      mechanism: 'Macrobenchmark фиксирует сценарий и frame timing, Perfetto локализует CPU/GPU/composition/layout/draw/I/O bottleneck; после одной локальной гипотезы benchmark повторяют.',
      trap: 'Debug build и Layout Inspector полезны для диагностики причины, но не доказывают влияние изменения на production frame time.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '22.13. Как диагностировать jank списка?' },
    tags: ['performance', 'macrobenchmark', 'perfetto', 'lazy-list'],
  },
  {
    id: 'compose-029',
    topicId: 'compose',
    subtopic: 'architecture',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Как лучше разделить `Route` и `Screen` в Compose-архитектуре?',
    options: [
      { id: 'a', text: '`Screen` получает ViewModel, NavController и DI container, а `Route` рисует только текст' },
      { id: 'b', text: '`Route` связывает ViewModel/lifecycle/navigation, а `Screen` получает UI state и intent callbacks' },
      { id: 'c', text: 'Оба слоя обязаны независимо собирать один Flow' },
      { id: 'd', text: 'Разделение означает, что оба composable должны хранить копию state' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Route — integration boundary, Screen — stateless или контролируемый UI.',
      mechanism: 'Route получает platform owners и собирает lifecycle-aware state; Screen отображает данные и сообщает намерения, поэтому легко запускается в Preview и component test.',
      trap: 'Два независимых sources of truth между Route и Screen создают рассинхронизацию.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '7.3. Route и Screen' },
    tags: ['route-screen', 'architecture', 'testability', 'viewmodel'],
  },
  {
    id: 'compose-030',
    topicId: 'compose',
    subtopic: 'architecture',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Результат действия нельзя потерять при configuration change и временном отсутствии collector. Как его надёжнее моделировать?',
    options: [
      { id: 'a', text: 'Только `SharedFlow(replay = 0)`, потому что он гарантирует доставку без subscriber' },
      { id: 'b', text: 'Как pending/durable state с идентификатором и идемпотентным подтверждением обработки' },
      { id: 'c', text: 'Как вызов callback прямо из composable body' },
      { id: 'd', text: 'Как случайный key у `LaunchedEffect`' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Гарантия доставки определяется семантикой, а не названием Flow-типа.',
      mechanism: '`SharedFlow(replay = 0)` теряет emit без активного subscriber; Channel имеет окно потери после receive при отмене collector. Критичный результат представляют state/durable domain result с acknowledgement.',
      trap: 'Навигация или snackbar могут быть допустимым transient command, но бизнес-результат, который пользователь обязан увидеть, event-ом без подтверждения быть не должен.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '7.8. UI state и one-off event' },
    tags: ['events', 'state', 'shared-flow', 'delivery'],
  },
  {
    id: 'compose-031',
    topicId: 'compose',
    subtopic: 'composition-local',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Как различается invalidation у `compositionLocalOf` и `staticCompositionLocalOf`?',
    options: [
      { id: 'a', text: 'Они идентичны во всех случаях' },
      { id: 'b', text: '`compositionLocalOf` отслеживает конкретных readers, а static-вариант при смене provider инвалидирует всё его subtree' },
      { id: 'c', text: 'Static-вариант инвалидирует только один случайный reader' },
      { id: 'd', text: '`compositionLocalOf` можно использовать только в unit tests' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Dynamic local платит за tracking readers, static local — за более широкую invalidation при редком изменении.',
      mechanism: '`staticCompositionLocalOf` подходит практически неизменяемым tree-scoped значениям; обычный local — значениям, где точечное отслеживание обновлений важно.',
      trap: 'CompositionLocal — скрытая dependency; screen data и business services без tree-scoped семантики лучше передавать явно.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '15. CompositionLocal, theming и design system' },
    tags: ['composition-local', 'invalidation', 'dependency'],
  },
  {
    id: 'compose-032',
    topicId: 'compose',
    subtopic: 'accessibility',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Почему `Modifier.graphicsLayer { alpha = 0f }` не является корректным способом полностью скрыть control от пользователя?',
    options: [
      { id: 'a', text: 'Alpha влияет только на drawing; node может остаться в layout, input и semantics для TalkBack' },
      { id: 'b', text: 'Alpha автоматически удаляет node из Composition, но оставляет Bitmap' },
      { id: 'c', text: 'TalkBack не поддерживает Compose ни при какой alpha' },
      { id: 'd', text: 'Значение alpha всегда округляется до 1f' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Визуальная прозрачность не меняет существование и accessibility-контракт узла.',
      mechanism: 'Для настоящего исчезновения используют conditional composition или `AnimatedVisibility`; отдельную semantics policy задают только если невидимый node намеренно должен оставаться.',
      trap: 'Оптимизация draw не должна оставлять невидимый кликабельный или озвучиваемый control.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '22.7. Почему alpha = 0f не скрывает control для TalkBack?' },
    tags: ['accessibility', 'semantics', 'alpha', 'code-trap'],
  },
  {
    id: 'compose-033',
    topicId: 'compose',
    subtopic: 'testing',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'На каком представлении UI взаимодействует Compose UI test?',
    options: [
      { id: 'a', text: 'Непосредственно вызывает локальные composable-функции по имени' },
      { id: 'b', text: 'Работает с semantics nodes; устойчивые пользовательские свойства предпочтительнее привязки к внутренней hierarchy' },
      { id: 'c', text: 'Всегда ищет Android `View` по `R.id`' },
      { id: 'd', text: 'Сравнивает только пиксели screenshot' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Semantics tree — общий контракт accessibility и Compose testing.',
      mechanism: 'Тесты ищут text, role, content description, semantic properties или, при отсутствии пользовательского признака, `testTag`; merged/unmerged tree выбирают по структуре control.',
      trap: 'Селектор, завязанный на внутреннюю hierarchy, ломается при безвредном рефакторинге реализации.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '19.2. Поиск nodes' },
    tags: ['testing', 'semantics', 'accessibility', 'test-tag'],
  },
  {
    id: 'compose-034',
    topicId: 'compose',
    subtopic: 'interop',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Как правильно распределить обязанности callbacks в `AndroidView`?',
    options: [
      { id: 'a', text: '`factory` создаёт View, `update` синхронизирует её со state, `onRelease` окончательно освобождает ресурсы' },
      { id: 'b', text: '`update` каждый раз обязан создавать новую View, а `factory` вызывается на каждом кадре' },
      { id: 'c', text: '`onRelease` обновляет state, а `factory` уничтожает View' },
      { id: 'd', text: 'Все callbacks эквивалентны и вызываются одновременно' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`AndroidView` отделяет создание legacy View, binding актуального state и release ресурсов.',
      mechanism: '`factory` вызывается для создания экземпляра, `update` может выполняться повторно с новыми входами, а `onRelease` закрывает player/map/WebView-подобные ресурсы.',
      trap: 'Не следует создавать View через `remember` вне `factory`; для reuse в lazy container нужен корректный reset item-specific listeners/state.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '18. View interoperability' },
    tags: ['android-view', 'interop', 'lifecycle', 'resources'],
  },
  {
    id: 'compose-035',
    topicId: 'compose',
    subtopic: 'interop',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какую disposal strategy обычно задают `ComposeView` внутри Fragment, чтобы Composition следовала lifecycle его View?',
    options: [
      { id: 'a', text: '`DisposeOnViewTreeLifecycleDestroyed`' },
      { id: 'b', text: 'Никогда не уничтожать Composition до завершения процесса' },
      { id: 'c', text: 'Уничтожать Composition после каждой recomposition' },
      { id: 'd', text: 'Связать Composition только с lifecycle Application' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Composition должна завершаться вместе с View hierarchy Fragment.',
      mechanism: '`DisposeOnViewTreeLifecycleDestroyed` использует lifecycle owner дерева View, поэтому при `onDestroyView` Composition освобождается, даже если сам Fragment остаётся в back stack.',
      trap: 'Привязка к более долгому lifecycle Fragment может удерживать уничтоженную View hierarchy и связанные ресурсы.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '18.3. ComposeView во Fragment' },
    tags: ['compose-view', 'fragment', 'interop', 'disposal'],
  },
  {
    id: 'compose-036',
    topicId: 'compose',
    subtopic: 'navigation',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Что лучше передавать в аргументах destination?',
    options: [
      { id: 'a', text: 'Целый mutable DTO со всеми вложенными изображениями' },
      { id: 'b', text: 'Минимальный устойчивый ID или небольшой primitive route argument, а актуальные данные загрузить в destination' },
      { id: 'c', text: 'Экземпляр Repository' },
      { id: 'd', text: 'Ссылку на текущую Activity' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Navigation boundary передаёт identity, а не снимок большого object graph.',
      mechanism: 'ID восстанавливается после process recreation, поддерживает deep link и позволяет destination загрузить актуальную сущность из source of truth.',
      trap: 'DTO может устареть, не существовать в external deep link и превысить ограничения Bundle.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '16.1. Что передавать между destinations?' },
    tags: ['navigation', 'route-arguments', 'process-death', 'deep-link'],
  },
  {
    id: 'compose-037',
    topicId: 'compose',
    subtopic: 'adaptive-ui',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'При переходе one-pane → list-detail stateful child переносится в другую условную ветку и теряет локальное состояние. Какое решение наиболее общее?',
    options: [
      { id: 'a', text: 'Каждый resize создавать случайный key' },
      { id: 'b', text: 'Hoist state выше adaptive structure или держать state holder в стабильном месте; перенос Composition применять только при особой необходимости' },
      { id: 'c', text: 'Хранить state в draw lambda' },
      { id: 'd', text: 'Отключить multi-window для приложения' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Смена ветки меняет positional identity, поэтому устойчивый owner state должен находиться выше изменяемой структуры.',
      mechanism: 'Scaffold с сохраняемой pane identity, stable keys или hoisted state holder переживают rearrangement. `movableContentOf` нужен лишь когда требуется переместить сам stateful subtree вместе с Composition.',
      trap: 'Adaptive решение принимается по текущим window size/posture, а не по постоянному ярлыку устройства.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '16.8. Как не потерять state при смене layout?' },
    tags: ['adaptive-ui', 'identity', 'state-hoisting', 'movable-content'],
  },
  {
    id: 'compose-038',
    topicId: 'compose',
    subtopic: 'performance',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему одного счётчика recompositions недостаточно для вывода о производительности?',
    options: [
      { id: 'a', text: 'Recomposition никогда не потребляет CPU' },
      { id: 'b', text: 'Количество не показывает стоимость: jank может быть в layout, draw, decoding, GC, I/O или одной тяжёлой операции' },
      { id: 'c', text: 'Счётчик всегда равен числу кадров в секунду' },
      { id: 'd', text: 'Compose всегда перерисовывает весь экран независимо от recomposition' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Оптимизируют frame deadline и пользовательский сценарий, а не сам факт recomposition.',
      mechanism: 'Нужно смотреть duration, skipped groups, layout/draw work, allocations, CPU/GPU trace и frame timing. Десять дешёвых recompositions могут стоить меньше одной сортировки списка.',
      trap: 'Compiler metrics и Layout Inspector полезны после того, как trace указывает на composition bottleneck.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '20.6. Recomposition counters' },
    tags: ['performance', 'recomposition', 'frame-time', 'profiling'],
  },
  {
    id: 'compose-039',
    topicId: 'compose',
    subtopic: 'state',
    difficulty: 'expert',
    kind: 'code',
    prompt: 'Какой риск создаёт запись в state сразу после его чтения в том же composable body?',
    code: {
      language: 'kotlin',
      value: 'Text("Count: $count")\ncount++',
    },
    options: [
      { id: 'a', text: 'Scope инвалидирует себя и может войти в бесконечный цикл recomposition' },
      { id: 'b', text: 'Значение автоматически откатывается к нулю без invalidation' },
      { id: 'c', text: 'Compiler переносит запись в `onClick`' },
      { id: 'd', text: 'Код гарантированно выполняется ровно один раз' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Backward write после tracked read может постоянно заново инвалидировать текущий scope.',
      mechanism: 'Composition читает старое значение и регистрирует dependency, затем запись публикует изменение и планирует новое выполнение того же scope.',
      trap: 'Записи выполняют в event callback, effect или state holder; похожий feedback loop возможен в layout через безусловную запись из `onGloballyPositioned`.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '4.8. Опасность backward write' },
    tags: ['backward-write', 'recomposition-loop', 'state', 'code-trap'],
  },
  {
    id: 'compose-040',
    topicId: 'compose',
    subtopic: 'graphics-layout',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Почему элемент, сдвинутый через `graphicsLayer`, может визуально наложиться на соседа?',
    code: {
      language: 'kotlin',
      value: 'Modifier.graphicsLayer {\n    translationX = animatedOffset\n}',
    },
    options: [
      { id: 'a', text: 'Transform меняет drawing, но parent и siblings продолжают использовать прежние layout bounds' },
      { id: 'b', text: '`graphicsLayer` всегда удаляет соседей из Composition' },
      { id: 'c', text: 'Translation изменяет только SlotTable, но не Canvas' },
      { id: 'd', text: 'Любой layer автоматически удваивает размер parent' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Layer transform не участвует в расчёте геометрии layout.',
      mechanism: 'Parent уже измерил и разместил siblings по старым bounds; translation/scale применяются позднее при drawing/compositing. Если соседи, hit bounds или scroll range должны измениться, анимируют layout size/placement.',
      trap: 'Более дешёвый draw transform неверен, если визуальная геометрия должна совпадать с input и accessibility geometry.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '22.8. Почему graphicsLayer наложил element на соседа?' },
    tags: ['graphics-layer', 'layout', 'drawing', 'code-trap'],
  },
  {
    id: 'compose-041',
    topicId: 'compose',
    subtopic: 'identity',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'В adaptive UI один stateful subtree должен переехать из `Column` в `Row`, сохранив локальные `remember`-значения и nodes. Какой API решает именно эту задачу?',
    options: [
      { id: 'a', text: '`movableContentOf`: он позволяет переместить identity subtree между местами Composition' },
      { id: 'b', text: '`rememberSaveable`: он всегда перемещает UI nodes между layout-контейнерами' },
      { id: 'c', text: '`derivedStateOf`: он переносит Composition при смене constraints' },
      { id: 'd', text: '`graphicsLayer`: он сохраняет identity при любом reorder' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`movableContentOf` сохраняет identity именно перемещаемой Composition-подветки.',
      mechanism: 'Обычная смена условной ветки уничтожает старую positional identity. Movable content позволяет вызвать тот же stateful content в новом месте, сохранив remembered state и nodes.',
      trap: 'Обычное решение для adaptive state — hoist state выше меняющейся структуры. `movableContentOf` нужен только когда переносить требуется сам subtree.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '3.7. Что такое movableContentOf?' },
    tags: ['movable-content', 'identity', 'adaptive-ui', 'remember'],
  },
  {
    id: 'compose-042',
    topicId: 'compose',
    subtopic: 'state-restoration',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Чем `retain` принципиально отличается от `rememberSaveable`?',
    options: [
      { id: 'a', text: '`retain` сериализует любой object graph в Bundle, а `rememberSaveable` — нет' },
      { id: 'b', text: '`retain` может пережить временный выход из hierarchy без сериализации, но не предназначен для process death' },
      { id: 'c', text: '`retain` заменяет ViewModel для screen business state' },
      { id: 'd', text: 'Это два названия одного API с одинаковым lifetime' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`retain` хранит короткоживущее retained state, а не durable saved state.',
      mechanism: 'Он дополняет `remember`, когда значение должно пережить временное удаление из hierarchy без Bundle-сериализации. Для восстановления после process death нужны saved state и durable data source.',
      trap: 'Доступность и точный контракт `retain` зависят от версии Compose Runtime проекта.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '3.8. Что такое retain?' },
    tags: ['retain', 'remember-saveable', 'lifetime', 'process-death'],
  },
  {
    id: 'compose-043',
    topicId: 'compose',
    subtopic: 'snapshots',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Два mutable snapshot параллельно изменили одно и то же snapshot state. Какое утверждение верно при `apply()`?',
    options: [
      { id: 'a', text: 'Второй `apply()` всегда молча затирает первое изменение' },
      { id: 'b', text: 'Несовместимые записи могут вызвать apply conflict; стратегию повтора нужно определить вызывающему коду' },
      { id: 'c', text: 'Compose автоматически пересоздаёт Activity и устраняет конфликт' },
      { id: 'd', text: 'Snapshot делает все внешние mutable-объекты thread-safe' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Mutable snapshot изолирует записи до публикации, но не отменяет конфликтующие изменения.',
      mechanism: 'State records предоставляют versioned view. При публикации runtime проверяет совместимость записей; конфликтующий `apply()` требует обработки, например повторного вычисления на свежем snapshot.',
      trap: 'Snapshot не заменяет синхронизацию внешних ресурсов и не делает произвольный object graph immutable.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '4.2. Что такое snapshot?' },
    tags: ['snapshots', 'concurrency', 'apply-conflict', 'state-records'],
  },
  {
    id: 'compose-044',
    topicId: 'compose',
    subtopic: 'state',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Почему эта операция способна обновить UI без `copy()` всей screen-модели?',
    code: {
      language: 'kotlin',
      value: 'val expandedIds = mutableStateMapOf<Long, Boolean>()\nexpandedIds[user.id] = true',
    },
    options: [
      { id: 'a', text: '`SnapshotStateMap` делает запись по ключу snapshot-aware mutation' },
      { id: 'b', text: 'Kotlin автоматически превращает любую `Map` в immutable-модель' },
      { id: 'c', text: 'Compose сканирует все `Map` после каждого кадра' },
      { id: 'd', text: '`mutableStateMapOf` доступен только в ViewModel и не имеет observer' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Snapshot-aware collections публикуют свои операции как observable state writes.',
      mechanism: 'Изменение `SnapshotStateMap` регистрируется runtime, поэтому прочитавшие значение потребители могут быть инвалидированы. Элементы внутри коллекции всё равно должны обновляться через immutable replacement или snapshot state.',
      trap: 'Для domain/ViewModel boundary обычно проще экспортировать immutable `Map`/`List`; локальный snapshot container требует ясного owner и очистки устаревших keys.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '4.6. Snapshot-aware коллекции' },
    tags: ['snapshot-state-map', 'state', 'collections', 'invalidation'],
  },
  {
    id: 'compose-045',
    topicId: 'compose',
    subtopic: 'state-restoration',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'В custom tabs content каждой вкладки временно уходит из Composition. Как сохранить её локальный `rememberSaveable` state между переключениями?',
    options: [
      { id: 'a', text: 'Использовать `SaveableStateHolder.SaveableStateProvider` со стабильным key вкладки' },
      { id: 'b', text: 'Поместить все локальные поля каждой вкладки в singleton object' },
      { id: 'c', text: 'Вызывать `Activity.recreate()` при каждом выборе вкладки' },
      { id: 'd', text: 'Использовать случайный UUID как key при каждой recomposition' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`SaveableStateHolder` удерживает saveable state динамически появляющегося content по identity.',
      mechanism: 'Provider связывает subtree с постоянным key, поэтому его `rememberSaveable` values возвращаются, когда вкладка снова появляется. State удаляют через `removeState`, если identity больше не вернётся.',
      trap: 'Нестабильный key не сохраняет, а сбрасывает state; отсутствие очистки permanently removed tabs удерживает ненужные данные.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '5.5. SaveableStateHolder' },
    tags: ['saveable-state-holder', 'tabs', 'state-restoration', 'keys'],
  },
  {
    id: 'compose-046',
    topicId: 'compose',
    subtopic: 'layout',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'В `Row` вертикальный divider должен быть высотой самого высокого текста, а не всего доступного parent. Какой подход корректен?',
    options: [
      { id: 'a', text: '`Row(Modifier.height(IntrinsicSize.Min))` и `VerticalDivider(Modifier.fillMaxHeight())`' },
      { id: 'b', text: 'Писать высоту divider в `onGloballyPositioned`, влияя на тот же layout' },
      { id: 'c', text: 'Всегда применять `fillMaxSize()` к divider' },
      { id: 'd', text: 'Измерить один Text дважды в обычном layout pass' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Intrinsic pass позволяет родителю запросить требуемую высоту детей до обычного measure.',
      mechanism: '`IntrinsicSize.Min` для `Row` выбирает нужную intrinsic-высоту, после чего divider получает ограничение этой высотой через `fillMaxHeight()`.',
      trap: 'Intrinsics добавляют работу; их не применяют как универсальное средство layout, а subcomposition-based containers не всегда могут дать точный ответ.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '11.5. Intrinsic measurements' },
    tags: ['intrinsics', 'layout', 'constraints', 'vertical-divider'],
  },
  {
    id: 'compose-047',
    topicId: 'compose',
    subtopic: 'layout',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Content B можно скомпоновать только после измерения content A, потому что constraints B зависят от ширины A. Какой API предназначен для такого алгоритма?',
    options: [
      { id: 'a', text: '`SubcomposeLayout`: измерить A, затем subcompose и измерить B с вычисленными constraints' },
      { id: 'b', text: 'Обычный `Layout`, измерив A дважды' },
      { id: 'c', text: '`graphicsLayer`, потому что он меняет constraints' },
      { id: 'd', text: '`rememberSaveable`, потому что B зависит от A' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`SubcomposeLayout` разрешает отложенно скомпоновать часть content после измерения другой части.',
      mechanism: 'Он сначала вызывает `subcompose` для первого slot и измеряет его, затем вычисляет constraints и создаёт второй slot. Так устроены многие сложные container APIs, включая lazy layouts.',
      trap: 'Это мощный, но дорогой API. Для простого layout, где все children уже известны, достаточно обычного `Layout`.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '11.7. SubcomposeLayout' },
    tags: ['subcompose-layout', 'measurement', 'constraints', 'custom-layout'],
  },
  {
    id: 'compose-048',
    topicId: 'compose',
    subtopic: 'layout',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Как корректно выровнять крупную сумму и маленький суффикс «руб.» по линии текста?',
    code: {
      language: 'kotlin',
      value: 'Row {\n    Text("12", Modifier.alignByBaseline())\n    Text("руб.", Modifier.alignByBaseline())\n}',
    },
    options: [
      { id: 'a', text: '`alignByBaseline()` использует alignment line текста вместо ручного подбора offset' },
      { id: 'b', text: 'Код выравнивает только ширины `Text`, но не влияет на высоту' },
      { id: 'c', text: 'Нужно заменить оба `Text` на `Canvas`, иначе baseline недоступен' },
      { id: 'd', text: 'Baseline можно получить только после `onGloballyPositioned`' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Alignment lines дают parent логическую геометрию child, например text baseline.',
      mechanism: '`Row` использует переданные alignment lines, поэтому элементы с разной внутренней высотой и typography располагаются по одной линии текста.',
      trap: 'Ручной offset ломается при другой typography, font scale, locale и fallback font; baseline alignment выражает нужную семантику layout напрямую.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '11.8. Alignment lines' },
    tags: ['alignment-lines', 'baseline', 'text', 'layout'],
  },
  {
    id: 'compose-049',
    topicId: 'compose',
    subtopic: 'layout',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Что даёт lookahead pass при structural layout transition?',
    options: [
      { id: 'a', text: 'Он заранее вычисляет будущие bounds, чтобы анимировать переход от текущей геометрии к целевой' },
      { id: 'b', text: 'Он отключает обычный measurement и рисует только Canvas' },
      { id: 'c', text: 'Он автоматически сериализует state между destinations' },
      { id: 'd', text: 'Он нужен для любой смены alpha' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Lookahead знает целевую layout-геометрию до завершения обычного transition.',
      mechanism: 'Предварительный measurement/placement даёт будущие bounds. API вроде `animateBounds` использует их для плавного изменения позиции и размера при смене структуры.',
      trap: 'Для простого visual transform достаточно draw/layer animation; lookahead усложняет layout и не должен быть default.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '11.9. Lookahead' },
    tags: ['lookahead', 'animate-bounds', 'layout-transition', 'animation'],
  },
  {
    id: 'compose-050',
    topicId: 'compose',
    subtopic: 'animation',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Нужно анимировать одновременно цвет и elevation одного selection-state так, чтобы значения всегда следовали одной transition. Что выбрать?',
    options: [
      { id: 'a', text: '`updateTransition` с несколькими animation properties' },
      { id: 'b', text: 'Несколько несвязанных `LaunchedEffect(Unit)`' },
      { id: 'c', text: '`rememberSaveable`, потому что оно синхронизирует animations' },
      { id: 'd', text: '`snapshotFlow`, потому что он рисует кадры' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`updateTransition` владеет несколькими согласованными animation values одного target state.',
      mechanism: 'Каждое свойство описывает target для одного и того же transition, поэтому смена selection coordinated и имеет единые interrupt semantics.',
      trap: 'Для одного независимого target value проще `animate*AsState`; для imperative drag, velocity и explicit cancellation используют `Animatable`.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '13.4. Как выбрать animation API?' },
    tags: ['animation', 'update-transition', 'state-machine', 'selection'],
  },
  {
    id: 'compose-051',
    topicId: 'compose',
    subtopic: 'animation',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'После drag элемент должен следовать за пальцем, а затем плавно вернуться, сохраняя скорость и отменяя старую анимацию при новом жесте. Какой инструмент подходит?',
    options: [
      { id: 'a', text: '`Animatable` с `snapTo` во время drag и `animateTo`/`animateDecay` после него' },
      { id: 'b', text: '`AnimatedVisibility`, потому что она всегда получает velocity жеста' },
      { id: 'c', text: '`rememberSaveable`, потому что оно управляет cancellation' },
      { id: 'd', text: 'Безусловно присваивать offset в composable body' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`Animatable` предназначен для imperative suspend-анимаций с velocity и cancellation.',
      mechanism: 'Новый вызов `snapTo`/`animateTo` отменяет текущую операцию этого `Animatable`; `snapTo` сразу отражает движение пальца, а последующая animation выполняется в event/effect coroutine.',
      trap: 'Анимацию нельзя стартовать прямо во время composition: управление должно идти из `LaunchedEffect` или callback через подходящий scope.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '13.5. Animatable' },
    tags: ['animatable', 'gesture', 'velocity', 'cancellation'],
  },
  {
    id: 'compose-052',
    topicId: 'compose',
    subtopic: 'architecture',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Когда plain custom state holder для composable действительно оправдан?',
    options: [
      { id: 'a', text: 'Когда есть несколько связанных UI state, сложные transitions или suspend-команды, и нужен отдельный тестируемый контракт' },
      { id: 'b', text: 'Для каждого единственного `Boolean` в любом компоненте' },
      { id: 'c', text: 'Чтобы заменить ViewModel для business state, переживающего configuration change' },
      { id: 'd', text: 'Только для хранения `Modifier` chain' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Plain state holder группирует связанное UI-состояние и операции, оставаясь owner-ом с composition lifetime.',
      mechanism: 'Он обычно создаётся через `remember`, инкапсулирует snapshot state и методы переходов, а значит тестируется без Composition. Для состояния, которое должно жить дольше экрана, owner-ом остаётся ViewModel/data layer.',
      trap: 'State holder для одного простого `remember { mutableStateOf(false) }` обычно создаёт только лишнюю косвенность. `@Stable` допустим лишь при честном observable контракте публичного state.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '21.6. Когда custom state holder оправдан?' },
    tags: ['state-holder', 'state-owner', 'architecture', 'testability'],
  },
  {
    id: 'compose-053',
    topicId: 'compose',
    subtopic: 'effects',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой API нужен, чтобы после каждой успешно применённой Composition синхронизировать небольшой внешний объект с актуальным Compose state?',
    options: [
      { id: 'a', text: '`SideEffect`' },
      { id: 'b', text: '`LaunchedEffect` с случайным key' },
      { id: 'c', text: '`rememberSaveable`' },
      { id: 'd', text: '`derivedStateOf`' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`SideEffect` публикует значение наружу только после успешного apply Composition.',
      mechanism: 'Он выполняется после каждой успешной recomposition, поэтому подходит для лёгкой синхронизации вроде установки user property в analytics SDK.',
      trap: 'Это не место для network/I/O и ресурсов с cleanup: для них нужны соответственно owner вне UI или `DisposableEffect`.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '8.5. SideEffect' },
    tags: ['side-effect', 'effects', 'composition', 'analytics'],
  },
  {
    id: 'compose-054',
    topicId: 'compose',
    subtopic: 'effects',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Есть callback-based API геолокации. Как адаптировать его к Compose `State` с обязательной отменой listener при выходе UI?',
    options: [
      { id: 'a', text: '`produceState` и `awaitDispose { unregisterListener() }`' },
      { id: 'b', text: 'Вызвать регистрацию прямо в composable body' },
      { id: 'c', text: 'Записать listener в `rememberSaveable`' },
      { id: 'd', text: 'Использовать `SideEffect`, потому что он автоматически отменяет listeners' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`produceState` связывает внешний async source с composition lifetime и предоставляет `State` UI.',
      mechanism: 'Producer устанавливает `value` при callback, а `awaitDispose` выполняет unregister при смене key или удалении composable из Composition.',
      trap: 'Если источник уже `Flow`, обычно проще и прозрачнее использовать `collectAsStateWithLifecycle` на Android.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '8.7. produceState' },
    tags: ['produce-state', 'await-dispose', 'callback-api', 'effects'],
  },
  {
    id: 'compose-055',
    topicId: 'compose',
    subtopic: 'stability',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Почему `MutableState<T>` считается stable, хотя его `value` можно менять?',
    options: [
      { id: 'a', text: 'Потому что изменение `value` — observable snapshot write и уведомляет Compose' },
      { id: 'b', text: 'Потому что compiler запрещает менять `value` после первой composition' },
      { id: 'c', text: 'Потому что `MutableState` всегда immutable внутри JVM' },
      { id: 'd', text: 'Потому что он автоматически сохраняется в Bundle' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Stable не означает immutable: значимые изменения должны быть наблюдаемы runtime.',
      mechanism: '`MutableState` публикует запись через snapshot system, которая инвалидирует прочитавшие scope или UI phase. Поэтому compiler может доверять его observable контракту.',
      trap: 'Обычный mutable object внутри stable-обёртки не становится observable автоматически.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '6.1. Что значит stable?' },
    tags: ['stability', 'mutable-state', 'snapshots', 'invalidation'],
  },
  {
    id: 'compose-056',
    topicId: 'compose',
    subtopic: 'stability',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Почему новый `List` с теми же элементами может помешать skip при strong skipping?',
    options: [
      { id: 'a', text: 'Стандартный `List` часто unstable, а strong skipping сравнивает unstable parameter по identity (`===`)' },
      { id: 'b', text: 'Compose всегда сортирует новый список перед skip' },
      { id: 'c', text: 'Любой `List` запрещён в параметрах composable' },
      { id: 'd', text: 'Strong skipping всегда делает глубокое сравнение элементов' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Strong skipping не делает стандартную коллекцию stable и не сравнивает её содержимое по умолчанию.',
      mechanism: 'Тот же instance unstable `List` может дать skip, но новый instance с равными данными считается изменившимся. Для честного immutable-контракта применяют persistent collections или проверяют необходимость по измерениям.',
      trap: 'Не стоит ставить `@Stable` на wrapper с mutable списком: это может скрыть UI update.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '6.3. Почему List<T> часто считается unstable?' },
    tags: ['strong-skipping', 'list', 'identity', 'stability'],
  },
  {
    id: 'compose-057',
    topicId: 'compose',
    subtopic: 'state-restoration',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какой принцип у хорошего `Saver` для сложного локального UI state?',
    options: [
      { id: 'a', text: 'Сохранить минимальное компактное представление, достаточное для восстановления' },
      { id: 'b', text: 'Сериализовать весь object graph, включая Repository, bitmap и открытые ресурсы' },
      { id: 'c', text: 'Хранить Saver только в ViewModel, не возвращая value' },
      { id: 'd', text: 'Использовать Saver для durable business database' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`Saver` преобразует local state в saveable Bundle-представление, а не в постоянное хранилище.',
      mechanism: 'Например, draft восстанавливается из пары строк и чисел через `Bundle`, `listSaver` или `mapSaver`; сам тяжёлый object graph пересоздаётся из минимальных данных.',
      trap: 'Размер Bundle ограничен. Полные DTO, списки и bitmap относятся к repository/database, а не к saved state.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '5.4. Saver, listSaver, mapSaver' },
    tags: ['saver', 'remember-saveable', 'bundle', 'state-restoration'],
  },
  {
    id: 'compose-058',
    topicId: 'compose',
    subtopic: 'animation',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему бесконечную animation следует останавливать или не создавать вне видимого UI?',
    options: [
      { id: 'a', text: 'Она продолжает тратить CPU/GPU и батарею, даже если user её не видит' },
      { id: 'b', text: 'Compose автоматически сохранит её каждый кадр в Bundle' },
      { id: 'c', text: 'Она всегда вызывает process death' },
      { id: 'd', text: 'Она запрещает TalkBack использовать экран' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Невидимая infinite animation остаётся работающей, пока её composable находится в Composition.',
      mechanism: 'Она может запрашивать кадры и GPU work без видимой пользы. UI также должен учитывать system animation scale и accessibility expectations.',
      trap: '`alpha = 0f` не удаляет элемент из Composition, input и semantics; для настоящего исчезновения используют conditional composition или `AnimatedVisibility`.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '13.7. Reduced motion' },
    tags: ['animation', 'reduced-motion', 'accessibility', 'performance'],
  },
  {
    id: 'compose-059',
    topicId: 'compose',
    subtopic: 'interop',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой callback `AndroidView` нужен в lazy container, чтобы очистить item-specific state и listeners до reuse View другой сущностью?',
    options: [
      { id: 'a', text: '`onReset`' },
      { id: 'b', text: '`onRelease`, потому что после него View продолжает использоваться' },
      { id: 'c', text: '`factory`, потому что она вызывается перед каждым reuse' },
      { id: 'd', text: '`SideEffect`' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`onReset` подготавливает reusable legacy View к новой item identity.',
      mechanism: 'В нём очищают item-specific listeners, playback position или binding, а `update` затем связывает View с новыми входами. `onRelease` освобождает ресурс окончательно.',
      trap: 'Это особенно важно для WebView, map, player и сложных custom Views: stale listener может удержать старую сущность.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '18.2. View reuse в lazy container' },
    tags: ['android-view', 'on-reset', 'lazy-list', 'interop'],
  },
  {
    id: 'compose-060',
    topicId: 'compose',
    subtopic: 'testing',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Как проверить, что локальный state на `rememberSaveable` реально восстанавливается?',
    options: [
      { id: 'a', text: 'Использовать `StateRestorationTester`: изменить UI state, выполнить save/restore и проверить восстановленный UI' },
      { id: 'b', text: 'Проверить только Preview в светлой теме' },
      { id: 'c', text: 'Поставить `Thread.sleep` после recomposition' },
      { id: 'd', text: 'Пересобрать приложение без запуска теста' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`StateRestorationTester` изолированно тестирует save/restore контракт Compose state.',
      mechanism: 'Тест создаёт content, меняет контролируемое значение, эмулирует restoration и проверяет semantics/UI. Критичный process-death flow дополнительно тестируют на уровне Activity, navigation и data restoration.',
      trap: 'Preview не является тестом, а `ViewModel` не переживает process death сам по себе.',
    },
    source: { file: 'Jetpack_Compose_Senior_Android_Guide.markdown', section: '19.4. State restoration testing' },
    tags: ['testing', 'state-restoration', 'remember-saveable', 'semantics'],
  },
]
