import type { Question } from '../domain/models'

export const coroutinesQuestions: Question[] = [
  {
    id: 'coroutines-001',
    topicId: 'coroutines',
    subtopic: 'Android scopes',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'В каком scope следует запускать загрузку данных, которая нужна только пока живёт ViewModel экрана?',
    options: [
      { id: 'a', text: 'viewModelScope' },
      { id: 'b', text: 'GlobalScope' },
      { id: 'c', text: 'Собственный process-wide scope' },
      { id: 'd', text: 'Scope внутри CoroutineWorker' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`viewModelScope` соответствует времени жизни ViewModel и отменяется в `onCleared()`.',
      mechanism: 'Дочерняя загрузка остаётся частью дерева ViewModel: при окончательном закрытии экрана отмена распространяется на неё автоматически.',
      trap: 'Process-wide и GlobalScope переживут экран без необходимости, а CoroutineWorker предназначен для гарантированной фоновой работы.',
      example: '`viewModelScope.launch { repository.loadFeed() }` подходит для состояния конкретного экрана.',
    },
    source: { file: '08-coroutines-android.md', section: '1.1. Какой scope выбрать' },
    tags: ['android', 'viewModelScope', 'lifecycle'],
  },
  {
    id: 'coroutines-002',
    topicId: 'coroutines',
    subtopic: 'Android scopes',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'Работа жёстко привязана к LifecycleOwner и должна отмениться при его уничтожении. Какой scope наиболее уместен?',
    options: [
      { id: 'a', text: 'rememberCoroutineScope()' },
      { id: 'b', text: 'lifecycleScope' },
      { id: 'c', text: 'GlobalScope' },
      { id: 'd', text: 'ApplicationScope' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`lifecycleScope` живёт до уничтожения соответствующего LifecycleOwner.',
      mechanism: 'Scope принадлежит Activity, Fragment или другому LifecycleOwner, поэтому уничтожение владельца отменяет его дочерние корутины.',
      trap: '`lifecycleScope` сам по себе не приостанавливает сбор Flow при STOPPED: для этого дополнительно нужен `repeatOnLifecycle`.',
      example: 'Разовая UI-работа Fragment может быть запущена через `viewLifecycleOwner.lifecycleScope`.',
    },
    source: { file: '08-coroutines-android.md', section: '1.1. Какой scope выбрать' },
    tags: ['android', 'lifecycleScope', 'lifecycle'],
  },
  {
    id: 'coroutines-003',
    topicId: 'coroutines',
    subtopic: 'Android scopes',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'Из обработчика нажатия Compose нужно запустить анимацию, существующую только пока composable находится в композиции. Что выбрать?',
    options: [
      { id: 'a', text: 'rememberCoroutineScope()' },
      { id: 'b', text: 'GlobalScope' },
      { id: 'c', text: 'CoroutineScope(Job()) в onClick' },
      { id: 'd', text: 'CoroutineWorker' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`rememberCoroutineScope()` предназначен для запуска корутин из UI-колбэков composable.',
      mechanism: 'Compose запоминает scope между рекомпозициями и отменяет его, когда composable покидает композицию.',
      trap: 'Созданный вручную scope в `onClick` не имеет владельца и не будет автоматически отменён.',
      example: '`val scope = rememberCoroutineScope(); Button(onClick = { scope.launch { animate() } })`.',
    },
    source: { file: '08-coroutines-android.md', section: '1.1. Какой scope выбрать' },
    tags: ['android', 'compose', 'rememberCoroutineScope'],
  },
  {
    id: 'coroutines-004',
    topicId: 'coroutines',
    subtopic: 'Android scopes',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему app-scoped CoroutineScope, предоставляемый singleton-компонентом DI, обычно создают с SupervisorJob?',
    options: [
      { id: 'a', text: 'Чтобы все задачи всегда выполнялись на Main' },
      { id: 'b', text: 'Чтобы ошибка одной фоновой задачи не отменила остальные задачи scope' },
      { id: 'c', text: 'Чтобы scope пережил смерть процесса' },
      { id: 'd', text: 'Чтобы delay использовал виртуальное время' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`SupervisorJob` изолирует сбой одной дочерней задачи от её siblings.',
      mechanism: 'Обычный Job распространяет неотменённое исключение ребёнка вверх и отменяет остальных детей; для долгоживущего app scope это может навсегда остановить независимые фоновые функции.',
      trap: 'Ни Job, ни SupervisorJob не переживают смерть процесса; для такой гарантии нужен WorkManager и персистентное состояние.',
      example: '`CoroutineScope(SupervisorJob() + Dispatchers.Default)` можно предоставить через DI как `@ApplicationScope`.',
    },
    source: { file: '08-coroutines-android.md', section: '1.1. Какой scope выбрать' },
    tags: ['android', 'SupervisorJob', 'dependency-injection'],
  },
  {
    id: 'coroutines-005',
    topicId: 'coroutines',
    subtopic: 'Durable work',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Сообщение должно гарантированно отправиться после ухода пользователя с экрана и по возможности после смерти процесса. Какая архитектура корректнее?',
    options: [
      { id: 'a', text: 'Запустить api.send() в viewModelScope' },
      { id: 'b', text: 'Запустить api.send() в GlobalScope' },
      { id: 'c', text: 'Записать PENDING в БД, поставить WorkManager и показывать статус из БД' },
      { id: 'd', text: 'Запустить api.send() в lifecycleScope без repeatOnLifecycle' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Гарантируемая работа требует персистентного источника истины и планировщика системной фоновой работы.',
      mechanism: 'Запись PENDING фиксирует намерение до сетевого вызова, WorkManager может возобновить задачу, а UI наблюдает устойчивый статус из БД.',
      trap: 'Любой in-process scope исчезает вместе с процессом; GlobalScope не превращает корутину в гарантированную доставку.',
      example: 'Экран сразу отображает локальное сообщение как PENDING, а worker переводит его в SENT или FAILED.',
    },
    source: { file: '08-coroutines-android.md', section: '1.2. Классическая ошибка: работа, которая должна пережить экран' },
    tags: ['android', 'WorkManager', 'durability'],
  },
  {
    id: 'coroutines-006',
    topicId: 'coroutines',
    subtopic: 'Lifecycle Flow collection',
    difficulty: 'basic',
    kind: 'code',
    prompt: 'Как безопаснее собирать Flow в View-системе только когда экран находится как минимум в STARTED?',
    options: [
      { id: 'a', text: 'lifecycleScope.launch { flow.collect(::render) }' },
      { id: 'b', text: 'GlobalScope.launch { flow.collect(::render) }' },
      { id: 'c', text: 'lifecycleScope.launch { repeatOnLifecycle(STARTED) { flow.collect(::render) } }' },
      { id: 'd', text: 'runBlocking { flow.collect(::render) }' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: '`repeatOnLifecycle(STARTED)` ограничивает активный collection видимым состоянием UI.',
      mechanism: 'Внешняя корутина живёт в lifecycleScope, а внутренний блок запускается при STARTED, отменяется при STOPPED и запускается снова при возвращении.',
      trap: 'Простой `collect` в lifecycleScope продолжает работу и трафик в фоне, хотя это не обязательно классическая утечка памяти.',
      example: 'В Compose эквивалентную lifecycle-aware интеграцию обычно даёт `collectAsStateWithLifecycle()`.',
    },
    source: { file: '08-coroutines-android.md', section: '1.3. Сбор Flow в UI' },
    tags: ['android', 'Flow', 'repeatOnLifecycle'],
  },
  {
    id: 'coroutines-007',
    topicId: 'coroutines',
    subtopic: 'Lifecycle Flow collection',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'После каждого возврата экрана из STOPPED в STARTED холодный Flow повторяет сетевой запрос. Почему?',
    options: [
      { id: 'a', text: 'repeatOnLifecycle отменяет и заново запускает collection, а cold upstream выполняется для каждого collector' },
      { id: 'b', text: 'StateFlow всегда удаляет последнее значение в STOPPED' },
      { id: 'c', text: 'lifecycleScope превращает любой Flow в Channel' },
      { id: 'd', text: 'Dispatchers.Main автоматически повторяет suspend-функции' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Перезапуск collection создаёт новое выполнение холодного upstream.',
      mechanism: '`repeatOnLifecycle` корректно отменяет блок при STOPPED и создаёт новый collector при STARTED; cold Flow является рецептом, выполняемым заново на каждой подписке.',
      trap: 'Убирать lifecycle-aware collection нельзя; если повтор нежелателен, upstream следует разделить через `stateIn` или `shareIn` в подходящем scope.',
      example: 'Сетевой Flow можно преобразовать в StateFlow во ViewModel с `WhileSubscribed(5_000)`.',
    },
    source: { file: '08-coroutines-android.md', section: '1.3. Сбор Flow в UI' },
    tags: ['android', 'cold-flow', 'repeatOnLifecycle', 'stateIn'],
  },
  {
    id: 'coroutines-008',
    topicId: 'coroutines',
    subtopic: 'Flow sharing',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Каков основной смысл SharingStarted.WhileSubscribed(5_000) для StateFlow экрана?',
    options: [
      { id: 'a', text: 'Задержать каждую эмиссию на пять секунд' },
      { id: 'b', text: 'Не останавливать upstream пять секунд после исчезновения последнего подписчика' },
      { id: 'c', text: 'Автоматически повторять упавший запрос каждые пять секунд' },
      { id: 'd', text: 'Хранить ровно пять последних значений' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Stop timeout сохраняет upstream активным короткое время без подписчиков.',
      mechanism: 'При повороте экрана старый collector исчезает, новый обычно появляется до истечения пяти секунд, поэтому upstream не перезапускается.',
      trap: '`Eagerly` держит upstream всегда, а `Lazily` запускает при первой подписке и затем не останавливает; это другие lifetime-политики.',
      example: '`stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), UiState.Loading)` сглаживает конфигурационные изменения.',
    },
    source: { file: '08-coroutines-android.md', section: '1.4. Почему WhileSubscribed(5000)' },
    tags: ['Flow', 'WhileSubscribed', 'stateIn'],
  },
  {
    id: 'coroutines-009',
    topicId: 'coroutines',
    subtopic: 'CoroutineWorker',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Что должен сделать CoroutineWorker, если во время doWork получен CancellationException?',
    options: [
      { id: 'a', text: 'Вернуть Result.retry()' },
      { id: 'b', text: 'Вернуть Result.failure()' },
      { id: 'c', text: 'Пробросить CancellationException дальше' },
      { id: 'd', text: 'Преобразовать её в IOException' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Системную отмену нельзя превращать в бизнес-ошибку или retry.',
      mechanism: 'WorkManager отменяет coroutine-контекст worker; повторный throw сохраняет кооперативную отмену и позволяет системе корректно завершить работу.',
      trap: 'Широкий `catch (Exception)` перехватит CancellationException, если не обработать её отдельно.',
      example: '`catch (e: CancellationException) { throw e }` должен предшествовать обработке IOException.',
    },
    source: { file: '08-coroutines-android.md', section: '1.5. CoroutineWorker' },
    tags: ['android', 'CoroutineWorker', 'cancellation'],
  },
  {
    id: 'coroutines-010',
    topicId: 'coroutines',
    subtopic: 'CoroutineWorker',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Worker получает IOException при синхронизации. Какая retry-политика наиболее корректна?',
    options: [
      { id: 'a', text: 'Всегда возвращать Result.retry() без лимита' },
      { id: 'b', text: 'Использовать runAttemptCount и после ограниченного числа попыток вернуть failure' },
      { id: 'c', text: 'Поймать Throwable и всегда вернуть success' },
      { id: 'd', text: 'Запустить новый GlobalScope worker' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Повторы transient-ошибки должны быть ограничены числом попыток.',
      mechanism: '`runAttemptCount` позволяет вернуть `Result.retry()` только пока бюджет не исчерпан, после чего работа завершается `Result.failure()`.',
      trap: 'Бесконечные повторы расходуют батарею и сеть; success скрывает недоставленную работу.',
      example: 'При `runAttemptCount < 5` вернуть retry, иначе failure.',
    },
    source: { file: '08-coroutines-android.md', section: '1.5. CoroutineWorker' },
    tags: ['android', 'CoroutineWorker', 'retry'],
  },
  {
    id: 'coroutines-011',
    topicId: 'coroutines',
    subtopic: 'Coroutine testing',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Что даёт runTest при проверке кода с delay?',
    options: [
      { id: 'a', text: 'Всегда переносит код на реальный Dispatchers.IO' },
      { id: 'b', text: 'Управляет виртуальным временем для TestDispatcher, делая задержки быстрыми и детерминированными' },
      { id: 'c', text: 'Заменяет все Thread.sleep на delay' },
      { id: 'd', text: 'Автоматически мокает сетевой API' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`runTest` предоставляет тестовый scheduler с виртуальным временем.',
      mechanism: 'Поддерживаемые `delay` на TestDispatcher не ждут wall-clock время: scheduler продвигает логические часы и выполняет запланированные continuation.',
      trap: 'Это не глобальная магия: реальные dispatcher и `Thread.sleep` виртуальным временем не управляются.',
      verification: 'Тест backoff на десятки секунд должен завершаться быстро без реального ожидания.',
    },
    source: { file: '08-coroutines-android.md', section: '2.1. runTest и виртуальное время' },
    tags: ['testing', 'runTest', 'virtual-time'],
  },
  {
    id: 'coroutines-012',
    topicId: 'coroutines',
    subtopic: 'Coroutine testing',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Почему delay(10.seconds) внутри withContext(Dispatchers.IO) может реально ждать десять секунд даже внутри runTest?',
    options: [
      { id: 'a', text: 'runTest ускоряет только delay короче секунды' },
      { id: 'b', text: 'Виртуальное время действует только на TestDispatcher, а Dispatchers.IO не был подменён' },
      { id: 'c', text: 'withContext всегда блокирует поток' },
      { id: 'd', text: 'delay на IO эквивалентен Thread.sleep' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Жёстко зашитый production dispatcher выходит из-под контроля тестового scheduler.',
      mechanism: '`runTest` управляет задачами, поставленными на связанные TestDispatcher; обычный `Dispatchers.IO` использует реальное планирование и реальные часы.',
      trap: '`delay` остаётся неблокирующим, но это не делает его виртуальным на любом dispatcher.',
      example: 'Инъецируйте IO dispatcher и в тесте передайте `StandardTestDispatcher(testScheduler)`.',
    },
    source: { file: '08-coroutines-android.md', section: '2.1. runTest и виртуальное время' },
    tags: ['testing', 'runTest', 'dispatcher-injection'],
  },
  {
    id: 'coroutines-013',
    topicId: 'coroutines',
    subtopic: 'Coroutine testing',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'runTest завершился UncompletedCoroutinesError. Что это чаще всего означает?',
    options: [
      { id: 'a', text: 'В тесте обязательно неверный assert' },
      { id: 'b', text: 'Тест оставил незавершённого ребёнка или ждёт бесконечный поток' },
      { id: 'c', text: 'MainDispatcherRule вызвал resetMain слишком рано' },
      { id: 'd', text: 'Turbine прочитал все события' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Тестовый scope ждёт завершения своих детей и сообщает о незавершённых корутинах.',
      mechanism: '`runTest` имеет таймаут и проверяет дочерние jobs; бесконечный collect в основном test scope не может естественно завершиться.',
      trap: 'Увеличение таймаута маскирует проблему владения корутиной, но не исправляет её.',
      verification: 'Проверьте запущенные `launch`, бесконечные collectors и ожидания каналов.',
    },
    source: { file: '08-coroutines-android.md', section: '2.1. runTest и виртуальное время' },
    tags: ['testing', 'runTest', 'UncompletedCoroutinesError'],
  },
  {
    id: 'coroutines-014',
    topicId: 'coroutines',
    subtopic: 'Coroutine testing',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Где запускать бесконечный collector StateFlow в runTest, если он нужен лишь на время теста?',
    options: [
      { id: 'a', text: 'В GlobalScope' },
      { id: 'b', text: 'Прямо через launch в основном TestScope и никогда не отменять' },
      { id: 'c', text: 'В backgroundScope, который автоматически отменится в конце теста' },
      { id: 'd', text: 'В runBlocking внутри runTest' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: '`backgroundScope` предназначен для фоновых задач, которые не обязаны завершиться самостоятельно.',
      mechanism: 'Его children работают на тестовом scheduler, но автоматически отменяются при завершении runTest и не удерживают тест до таймаута.',
      trap: 'GlobalScope теряет контроль и детерминизм, а ребёнок основного TestScope должен завершиться до выхода.',
      example: '`backgroundScope.launch { viewModel.state.collect() }` активирует горячую подписку.',
    },
    source: { file: '08-coroutines-android.md', section: '2.1. runTest и виртуальное время' },
    tags: ['testing', 'backgroundScope', 'StateFlow'],
  },
  {
    id: 'coroutines-015',
    topicId: 'coroutines',
    subtopic: 'Test dispatchers',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Как ведёт себя новая coroutine на StandardTestDispatcher?',
    options: [
      { id: 'a', text: 'Всегда выполняется полностью синхронно в момент launch' },
      { id: 'b', text: 'Ставится в очередь до уступки управления или явного продвижения scheduler' },
      { id: 'c', text: 'Всегда запускается на отдельном реальном потоке' },
      { id: 'd', text: 'Игнорирует advanceUntilIdle()' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`StandardTestDispatcher` даёт явный контроль над очередью выполнения.',
      mechanism: 'После `launch` задача готова, но не исполняется немедленно; тест уступает управление либо вызывает `runCurrent`, `advanceTimeBy` или `advanceUntilIdle`.',
      trap: 'Проверка состояния сразу после launch может выполняться раньше action, хотя к концу runTest scheduler будет дренирован.',
      example: 'Для промежуточного assert вызовите `runCurrent()` перед чтением состояния.',
    },
    source: { file: '08-coroutines-android.md', section: '2.2. StandardTestDispatcher vs UnconfinedTestDispatcher' },
    tags: ['testing', 'StandardTestDispatcher', 'scheduler'],
  },
  {
    id: 'coroutines-016',
    topicId: 'coroutines',
    subtopic: 'Test dispatchers',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Когда UnconfinedTestDispatcher особенно рискован?',
    options: [
      { id: 'a', text: 'Когда тесту важен порядок и реалистичная очередность выполнения' },
      { id: 'b', text: 'Когда тест вообще не использует корутины' },
      { id: 'c', text: 'Когда нужен только финальный результат без конкуренции' },
      { id: 'd', text: 'Когда StateFlow имеет initialValue' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`UnconfinedTestDispatcher` выполняет задачу немедленно до первой реальной приостановки и может менять порядок.',
      mechanism: 'Eager execution упрощает setup и финальные проверки, но отличается от production scheduling, поэтому race/order-тест может дать ложный успех или ложное падение.',
      trap: 'Использовать Unconfined только ради наблюдения промежуточных StateFlow-состояний хуже, чем подписаться Turbine до action.',
      example: 'По умолчанию используйте Standard; Unconfined выбирайте, когда порядок не является частью поведения.',
    },
    source: { file: '08-coroutines-android.md', section: '2.2. StandardTestDispatcher vs UnconfinedTestDispatcher' },
    tags: ['testing', 'UnconfinedTestDispatcher', 'ordering'],
  },
  {
    id: 'coroutines-017',
    topicId: 'coroutines',
    subtopic: 'Main dispatcher testing',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'JVM unit-тест ViewModel падает с сообщением “Module with the Main dispatcher had failed to initialize”. Что требуется?',
    options: [
      { id: 'a', text: 'Перенести тест в GlobalScope' },
      { id: 'b', text: 'В JUnit rule вызвать Dispatchers.setMain(TestDispatcher), а после теста resetMain()' },
      { id: 'c', text: 'Добавить Thread.sleep перед созданием ViewModel' },
      { id: 'd', text: 'Заменить runTest на runBlocking без других изменений' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'В обычном JVM-тесте Android Main dispatcher отсутствует и должен быть подменён.',
      mechanism: 'MainDispatcherRule устанавливает TestDispatcher до теста и обязательно возвращает глобальное состояние через `Dispatchers.resetMain()` после него.',
      trap: 'runTest сам по себе не устанавливает `Dispatchers.Main` для кода ViewModel.',
      example: 'Для init-блоков удобен Unconfined rule; тест порядка может явно передать Standard dispatcher.',
    },
    source: { file: '08-coroutines-android.md', section: '2.3. MainDispatcherRule' },
    tags: ['testing', 'Dispatchers.Main', 'MainDispatcherRule'],
  },
  {
    id: 'coroutines-018',
    topicId: 'coroutines',
    subtopic: 'Turbine',
    difficulty: 'basic',
    kind: 'code',
    prompt: 'Как Turbine позволяет проверить последовательность Loading → Content?',
    options: [
      { id: 'a', text: 'Дважды прочитать flow.value без подписки' },
      { id: 'b', text: 'В блоке test последовательно вызвать awaitItem() для обоих состояний' },
      { id: 'c', text: 'Вызвать только awaitComplete() у StateFlow' },
      { id: 'd', text: 'Использовать Thread.sleep между двумя assert' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Turbine превращает эмиссии Flow в упорядоченные события для suspend-проверок.',
      mechanism: 'Подписка создаётся до выполнения тела `test`, а каждый `awaitItem()` ожидает очередное значение в порядке поступления.',
      trap: 'StateFlow обычно не завершается, поэтому `awaitComplete()` для него без отмены будет ждать бесконечно.',
      example: 'После чтения ожидаемых значений вызовите `cancelAndIgnoreRemainingEvents()` при бесконечном потоке.',
    },
    source: { file: '08-coroutines-android.md', section: '2.4. Turbine' },
    tags: ['testing', 'Turbine', 'Flow'],
  },
  {
    id: 'coroutines-019',
    topicId: 'coroutines',
    subtopic: 'Turbine',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему Turbine по умолчанию падает, если после теста остались непрочитанные эмиссии?',
    options: [
      { id: 'a', text: 'Это ограничение только Android Main thread' },
      { id: 'b', text: 'Так он выявляет неожиданные лишние состояния или ошибки в контракте потока' },
      { id: 'c', text: 'Потому что Flow обязан иметь ровно одну эмиссию' },
      { id: 'd', text: 'Потому что awaitItem автоматически завершает upstream' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Непрочитанные события считаются значимым расхождением между ожидаемым и фактическим поведением.',
      mechanism: 'Turbine ведёт очередь событий и при завершении валидации сообщает, что тест не подтвердил все полученные items/errors/completion.',
      trap: 'Не следует бездумно игнорировать остаток: `cancelAndIgnoreRemainingEvents()` уместен, только когда дальнейшие события действительно вне проверяемого контракта.',
      verification: 'Лишнее состояние Error после Content должно сделать тест красным, если оно не ожидается.',
    },
    source: { file: '08-coroutines-android.md', section: '2.4. Turbine' },
    tags: ['testing', 'Turbine', 'emissions'],
  },
  {
    id: 'coroutines-020',
    topicId: 'coroutines',
    subtopic: 'StateFlow testing',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Почему тест StateFlow иногда видит только Content, хотя код быстро установил Loading, затем Content?',
    options: [
      { id: 'a', text: 'StateFlow конфлейтит быстрые обновления, и медленный collector может пропустить промежуточное значение' },
      { id: 'b', text: 'Loading запрещён как initial state' },
      { id: 'c', text: 'StateFlow хранит все значения, но выдаёт их в обратном порядке' },
      { id: 'd', text: 'runTest удаляет первую эмиссию любого Flow' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`StateFlow` хранит актуальное состояние, а не журнал каждого перехода.',
      mechanism: 'Если producer обновляет value быстрее, чем collector возобновляется, collector получает новейшее равное по контракту состояние, а промежуточное может быть сконфлейчено.',
      trap: 'Это не доказательство отсутствия Loading в коде; тест должен подписаться до action или проверять холодный Flow под StateFlow.',
      example: 'Turbine-подписка до вызова `load()` лучше фиксирует ожидаемую последовательность.',
    },
    source: { file: '08-coroutines-android.md', section: '2.5. Ловушка с StateFlow' },
    tags: ['testing', 'StateFlow', 'conflation'],
  },
  {
    id: 'coroutines-021',
    topicId: 'coroutines',
    subtopic: 'StateFlow testing',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Тест StateFlow, созданного через stateIn(WhileSubscribed), навсегда видит только initialValue. Какова наиболее вероятная причина?',
    options: [
      { id: 'a', text: 'WhileSubscribed не запускает upstream без активного подписчика' },
      { id: 'b', text: 'stateIn запрещён в unit-тестах' },
      { id: 'c', text: 'initialValue всегда блокирует последующие эмиссии' },
      { id: 'd', text: 'StandardTestDispatcher не поддерживает StateFlow' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Политика WhileSubscribed активирует upstream только при наличии подписчиков.',
      mechanism: 'Одного чтения `.value` недостаточно: оно не создаёт collector и не увеличивает subscription count.',
      trap: 'Можно ошибочно чинить scheduler, хотя отсутствует сама подписка.',
      example: 'Подпишитесь через Turbine либо запустите `state.collect()` в `backgroundScope` на TestDispatcher.',
    },
    source: { file: '08-coroutines-android.md', section: '2.5. Ловушка с StateFlow' },
    tags: ['testing', 'StateFlow', 'WhileSubscribed'],
  },
  {
    id: 'coroutines-022',
    topicId: 'coroutines',
    subtopic: 'Dispatcher injection',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Зачем репозиторию принимать CoroutineDispatcher через конструктор вместо жёсткого Dispatchers.IO?',
    options: [
      { id: 'a', text: 'Только чтобы сократить число импортов' },
      { id: 'b', text: 'Чтобы тест мог передать TestDispatcher с общим testScheduler и контролировать время' },
      { id: 'c', text: 'Чтобы withContext стал блокирующим' },
      { id: 'd', text: 'Чтобы автоматически создать SupervisorJob' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Инъекция dispatcher делает планирование частью заменяемой зависимости.',
      mechanism: 'Production default может оставаться IO, а тест передаёт `StandardTestDispatcher(testScheduler)`, сохраняя весь код под одним виртуальным scheduler.',
      trap: 'Подмена только Main не контролирует задержки внутри жёстко зашитого IO.',
      example: '`class Repo(..., private val io: CoroutineDispatcher = Dispatchers.IO)`.',
    },
    source: { file: '08-coroutines-android.md', section: '2.6. Инъекция диспетчеров' },
    tags: ['testing', 'dispatcher-injection', 'testability'],
  },
  {
    id: 'coroutines-023',
    topicId: 'coroutines',
    subtopic: 'Callback bridges',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'Какой primitive подходит для преобразования callback API с одним будущим результатом в suspend-функцию?',
    options: [
      { id: 'a', text: 'callbackFlow' },
      { id: 'b', text: 'suspendCancellableCoroutine' },
      { id: 'c', text: 'MutableSharedFlow с бесконечным replay' },
      { id: 'd', text: 'GlobalScope.async' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`suspendCancellableCoroutine` адаптирует одноразовый callback к одному suspend-результату.',
      mechanism: 'Успешный callback вызывает `resume`, ошибка — `resumeWithException`, а cancellation handler освобождает underlying operation.',
      trap: '`callbackFlow` нужен для последовательности событий, а не для одного ответа.',
      example: 'Получение последней геопозиции через Task API естественно представить suspend-функцией.',
    },
    source: { file: '08-coroutines-android.md', section: '3.1. suspendCancellableCoroutine — для одноразового результата' },
    tags: ['callbacks', 'suspendCancellableCoroutine', 'interop'],
  },
  {
    id: 'coroutines-024',
    topicId: 'coroutines',
    subtopic: 'Callback bridges',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему при адаптации отменяемого callback API suspendCoroutine хуже suspendCancellableCoroutine?',
    options: [
      { id: 'a', text: 'suspendCoroutine всегда создаёт новый поток' },
      { id: 'b', text: 'suspendCoroutine не реагирует на отмену родителя и может ждать callback после отмены' },
      { id: 'c', text: 'suspendCoroutine поддерживает только Flow' },
      { id: 'd', text: 'suspendCancellableCoroutine запрещает исключения' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Cancellable-вариант связывает lifecycle внешней операции с отменой coroutine.',
      mechanism: '`invokeOnCancellation` позволяет снять listener или отменить запрос; без него continuation может оставаться подвешенным до позднего callback.',
      trap: 'Нужно также учитывать гонку callback с cancellation и пользоваться безопасным контрактом конкретного API.',
      example: 'При закрытии экрана location request должен быть отменён, а не продолжать держать ресурсы.',
    },
    source: { file: '08-coroutines-android.md', section: '3.1. suspendCancellableCoroutine — для одноразового результата' },
    tags: ['callbacks', 'cancellation', 'suspendCancellableCoroutine'],
  },
  {
    id: 'coroutines-025',
    topicId: 'coroutines',
    subtopic: 'Callback bridges',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Какой обязательный элемент обычно завершает регистрацию listener внутри callbackFlow?',
    options: [
      { id: 'a', text: 'awaitClose { unregister(listener) }' },
      { id: 'b', text: 'runBlocking { listener.join() }' },
      { id: 'c', text: 'withContext(NonCancellable) { awaitCancellation() } без cleanup' },
      { id: 'd', text: 'GlobalScope.launch { unregister(listener) }' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`awaitClose` удерживает producer до закрытия канала и выполняет симметричный cleanup.',
      mechanism: 'Когда collector отменяется или channel закрывается, callbackFlow вызывает cleanup-блок, где listener снимается.',
      trap: 'Без `awaitClose` builder сообщает об ошибке, а зарегистрированный listener может стать реальной утечкой.',
      example: 'Connectivity callback регистрируется перед `awaitClose`, а внутри него вызывается `unregisterNetworkCallback`.',
    },
    source: { file: '08-coroutines-android.md', section: '3.2. callbackFlow — для потока событий' },
    tags: ['callbacks', 'callbackFlow', 'awaitClose'],
  },
  {
    id: 'coroutines-026',
    topicId: 'coroutines',
    subtopic: 'Callback bridges',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Как точнее различить callbackFlow и channelFlow?',
    options: [
      { id: 'a', text: 'callbackFlow — адаптер callback/listener API с awaitClose; channelFlow — общий builder для эмиссии из нескольких корутин' },
      { id: 'b', text: 'callbackFlow горячий, а channelFlow всегда StateFlow' },
      { id: 'c', text: 'channelFlow разрешён только в Android Service' },
      { id: 'd', text: 'Между ними нет различий в назначении и cleanup-контракте' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Оба builder используют channel, но выражают разные типовые задачи.',
      mechanism: '`callbackFlow` акцентирует безопасную регистрацию внешнего callback и требует ожидания закрытия; `channelFlow` позволяет нескольким дочерним корутинам конкурентно send-ить значения.',
      trap: 'Обычный `flow {}` сохраняет контекст и не разрешает произвольный emit из другой coroutine.',
      example: 'Listener сети — callbackFlow; объединение результатов нескольких concurrently launched producers — channelFlow.',
    },
    source: { file: '08-coroutines-android.md', section: '3.2. callbackFlow — для потока событий' },
    tags: ['callbacks', 'callbackFlow', 'channelFlow'],
  },
  {
    id: 'coroutines-027',
    topicId: 'coroutines',
    subtopic: 'Retry',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'В retryWithBackoff параметр times означает общее число попыток. Сколько раз максимум вызовется block при times = 3?',
    options: [
      { id: 'a', text: '2' },
      { id: 'b', text: '3' },
      { id: 'c', text: '4' },
      { id: 'd', text: 'Бесконечно' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`times = 3` означает первую попытку и максимум два повтора.',
      mechanism: 'Реализация делает `repeat(times - 1)` попыток с обработкой ошибок, а затем один финальный вызов block.',
      trap: 'Название times часто ошибочно трактуют как число ретраев, что даёт off-by-one.',
      verification: 'Нужны отдельные тесты успешной третьей попытки и полного исчерпания бюджета.',
    },
    source: { file: '08-coroutines-android.md', section: '4.1. Retry с экспоненциальным backoff и джиттером' },
    tags: ['retry', 'backoff', 'off-by-one'],
  },
  {
    id: 'coroutines-028',
    topicId: 'coroutines',
    subtopic: 'Retry',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему retry-функция должна отдельно пробрасывать CancellationException?',
    options: [
      { id: 'a', text: 'Чтобы увеличить backoff' },
      { id: 'b', text: 'Чтобы не повторять отменённую операцию и не ломать structured concurrency' },
      { id: 'c', text: 'Потому что CancellationException никогда не является Throwable' },
      { id: 'd', text: 'Чтобы перевести выполнение на Main' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Отмена — управляющий сигнал, а не transient failure.',
      mechanism: 'Широкий catch перехватывает CancellationException; если цикл продолжит retry, дочерняя операция проигнорирует отмену своего владельца.',
      trap: '`shouldRetry` не должен случайно считать отмену обычной сетевой ошибкой.',
      example: 'Сначала `catch (e: CancellationException) { throw e }`, затем обработка остальных Throwable.',
    },
    source: { file: '08-coroutines-android.md', section: '4.1. Retry с экспоненциальным backoff и джиттером' },
    tags: ['retry', 'cancellation', 'structured-concurrency'],
  },
  {
    id: 'coroutines-029',
    topicId: 'coroutines',
    subtopic: 'Retry',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Какой набор граничных условий корректен для retry с backoff и jitter?',
    options: [
      { id: 'a', text: 'times может быть 0; initialDelay не ограничивается; nextLong(0) безопасен' },
      { id: 'b', text: 'times >= 1; initialDelay ограничивается maxDelay; нулевой диапазон jitter не передаётся в nextLong' },
      { id: 'c', text: 'Ретраятся все Throwable, включая cancellation; maxDelay не нужен' },
      { id: 'd', text: 'Jitter применим только после успешной попытки' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Корректная реализация явно валидирует бюджет и безопасно ограничивает задержки.',
      mechanism: '`require(times >= 1)` фиксирует семантику; `coerceAtMost(maxDelay)` ограничивает первую и последующие задержки; очень малый delay требует jitter 0 вместо `Random.nextLong(0)`.',
      trap: 'Ограничивать только результат умножения недостаточно, если initialDelay уже превышает maxDelay.',
      example: 'При delayMs < 2 можно выбрать jitter = 0L.',
    },
    source: { file: '08-coroutines-android.md', section: '4.1. Retry с экспоненциальным backoff и джиттером' },
    tags: ['retry', 'jitter', 'edge-cases'],
  },
  {
    id: 'coroutines-030',
    topicId: 'coroutines',
    subtopic: 'Parallel mapping',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Как ограничить число одновременно выполняющихся transform в mapParallel, сохранив порядок результата?',
    options: [
      { id: 'a', text: 'Создать async для каждого элемента, обернуть transform в Semaphore.withPermit и вызвать awaitAll()' },
      { id: 'b', text: 'Вызывать transform последовательно внутри обычного map без async' },
      { id: 'c', text: 'Создавать новый GlobalScope на каждый элемент' },
      { id: 'd', text: 'Использовать Thread.sleep между запусками' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Semaphore ограничивает число логических операций, а awaitAll возвращает результаты в порядке списка Deferred.',
      mechanism: 'Все children создаются структурированно, но только `concurrency` из них одновременно удерживают permit и выполняют transform.',
      trap: 'Нужно валидировать положительное значение concurrency; новый независимый scope разрушит владение и отмену.',
      example: '`map { async { semaphore.withPermit { transform(it) } } }.awaitAll()`.',
    },
    source: { file: '08-coroutines-android.md', section: '4.2. Параллельная обработка с ограничением' },
    tags: ['parallelism', 'Semaphore', 'awaitAll'],
  },
  {
    id: 'coroutines-031',
    topicId: 'coroutines',
    subtopic: 'Parallel mapping',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему mapParallel следует строить внутри coroutineScope, а не CoroutineScope(Dispatchers.Default)?',
    options: [
      { id: 'a', text: 'coroutineScope ждёт детей и связывает их ошибки и отмену с вызывающим кодом' },
      { id: 'b', text: 'CoroutineScope нельзя создавать в Kotlin' },
      { id: 'c', text: 'coroutineScope всегда запускает всё на Main' },
      { id: 'd', text: 'CoroutineScope автоматически делает операции последовательными' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`coroutineScope` сохраняет structured concurrency.',
      mechanism: 'Suspend-функция не возвращается до завершения дочерних async; ошибка ребёнка отменяет siblings и передаётся caller, а отмена caller отменяет всю обработку.',
      trap: 'Новый CoroutineScope создаёт независимое дерево и допускает работу после возврата или отмены вызывающего.',
      example: 'Сигнатура `suspend fun ... = coroutineScope { ... }` явно выражает владение.',
    },
    source: { file: '08-coroutines-android.md', section: '4.2. Параллельная обработка с ограничением' },
    tags: ['parallelism', 'coroutineScope', 'structured-concurrency'],
  },
  {
    id: 'coroutines-032',
    topicId: 'coroutines',
    subtopic: 'Parallel mapping',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Чем Semaphore(concurrency) концептуально отличается от Dispatchers.IO.limitedParallelism(n)?',
    options: [
      { id: 'a', text: 'Semaphore ограничивает логические критические операции, limitedParallelism — параллелизм выполнения на dispatcher' },
      { id: 'b', text: 'Semaphore создаёт процессы ОС, limitedParallelism — Android Service' },
      { id: 'c', text: 'limitedParallelism гарантирует порядок результатов, Semaphore никогда' },
      { id: 'd', text: 'Они оба автоматически делают retry' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Это ограничения на разных уровнях.',
      mechanism: 'Permit охватывает явно выбранный suspend-блок как логическую задачу; limited dispatcher ограничивает число одновременно исполняемых задач/потоков в своей view.',
      trap: 'Ограниченный dispatcher не заменяет доменный лимит на запросы, если операция переключает контекст или имеет иной lifecycle.',
      example: 'Для лимита “не больше пяти HTTP-запросов” Semaphore выражает намерение напрямую.',
    },
    source: { file: '08-coroutines-android.md', section: '4.2. Параллельная обработка с ограничением' },
    tags: ['parallelism', 'Semaphore', 'limitedParallelism'],
  },
  {
    id: 'coroutines-033',
    topicId: 'coroutines',
    subtopic: 'Single-flight',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Пять запросов одновременно получили 401 и требуют refresh одного токена. Как single-flight предотвращает пять refresh-вызовов?',
    options: [
      { id: 'a', text: 'Под mutex хранит один Deferred на ключ и все callers await тот же Deferred' },
      { id: 'b', text: 'Последовательно делает пять refresh под delay' },
      { id: 'c', text: 'Отменяет четыре запроса без результата' },
      { id: 'd', text: 'Использует distinctUntilChanged над исключениями' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Single-flight дедуплицирует только одновременно выполняющиеся операции одного ключа.',
      mechanism: 'Короткая mutex-секция атомарно находит существующий Deferred либо создаёт и кладёт новый; после lock все callers ждут общий результат без удержания mutex.',
      trap: 'Сам `block()` нельзя выполнять под mutex: это сериализует несвязанные ключи и удерживает lock на долгой операции.',
      example: 'Ключом может быть accountId, а Deferred представляет текущий token refresh.',
    },
    source: { file: '08-coroutines-android.md', section: '4.3. Дедупликация одновременных запросов (single-flight)' },
    tags: ['single-flight', 'Mutex', 'Deferred'],
  },
  {
    id: 'coroutines-034',
    topicId: 'coroutines',
    subtopic: 'Single-flight',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Почему удаление Deferred из inFlight в finally оборачивают в withContext(NonCancellable)?',
    options: [
      { id: 'a', text: 'Чтобы cleanup мог дождаться mutex даже после отмены caller' },
      { id: 'b', text: 'Чтобы block нельзя было отменить до результата' },
      { id: 'c', text: 'Чтобы превратить Deferred в StateFlow' },
      { id: 'd', text: 'Чтобы mutex стал reentrant' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Обязательный cleanup должен завершиться, даже если ожидавший caller уже отменён.',
      mechanism: 'Обычный cancellable `withLock` может приостановиться на занятом mutex и сразу выбросить CancellationException; NonCancellable позволяет атомарно убрать именно тот Deferred.',
      trap: 'Без identity-проверки старый finally может удалить более новый Deferred того же ключа.',
      example: '`if (inFlight[key] === deferred) inFlight.remove(key)` защищает новую операцию.',
    },
    source: { file: '08-coroutines-android.md', section: '4.3. Дедупликация одновременных запросов (single-flight)' },
    tags: ['single-flight', 'NonCancellable', 'cleanup'],
  },
  {
    id: 'coroutines-035',
    topicId: 'coroutines',
    subtopic: 'Single-flight',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Какое требование важно для внешнего scope, в котором SingleFlight создаёт scope.async?',
    options: [
      { id: 'a', text: 'Он должен использовать SupervisorJob, чтобы ошибка одной операции не уничтожила весь долгоживущий scope' },
      { id: 'b', text: 'Он обязан быть GlobalScope' },
      { id: 'c', text: 'Он обязан использовать только Dispatchers.Main.immediate' },
      { id: 'd', text: 'Он должен создаваться заново для каждого await' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Независимые single-flight операции не должны взаимно уничтожать общий lifetime.',
      mechanism: 'При обычном Job исключение child async отменяет родительский scope; последующие операции затем стартуют в уже отменённом scope.',
      trap: 'Общий supervised scope означает и осознанную семантику: отмена одного caller не отменяет разделяемую операцию для остальных.',
      example: 'App-level token refresher может получить DI scope с SupervisorJob.',
    },
    source: { file: '08-coroutines-android.md', section: '4.3. Дедупликация одновременных запросов (single-flight)' },
    tags: ['single-flight', 'SupervisorJob', 'cancellation'],
  },
  {
    id: 'coroutines-036',
    topicId: 'coroutines',
    subtopic: 'Search',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой оператор гарантирует, что медленный результат старого поискового запроса не перезапишет результат нового query?',
    options: [
      { id: 'a', text: 'flatMapLatest' },
      { id: 'b', text: 'flatMapMerge' },
      { id: 'c', text: 'onEach' },
      { id: 'd', text: 'buffer' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`flatMapLatest` отменяет предыдущий inner Flow при появлении нового query.',
      mechanism: 'Каждый нормализованный запрос создаёт новый search Flow; latest-семантика прекращает сбор предыдущего и принимает состояния только актуального.',
      trap: '`flatMapMerge` выполняет запросы конкурентно, поэтому старый ответ может прийти позже нового.',
      example: 'Обычно перед ним ставят `debounce`, trim/filter и `distinctUntilChanged`, а после — `stateIn`.',
    },
    source: { file: '08-coroutines-android.md', section: '4.4. Поиск с дебаунсом' },
    tags: ['search', 'flatMapLatest', 'debounce'],
  },
  {
    id: 'coroutines-037',
    topicId: 'coroutines',
    subtopic: 'Concurrent state',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Почему `_state.update { it.copy(...) }` безопаснее конкурентного `_state.value = _state.value.copy(...)`?',
    options: [
      { id: 'a', text: 'update выполняет атомарный compare-and-set цикл и повторяет transform при гонке' },
      { id: 'b', text: 'update автоматически переносит код на IO' },
      { id: 'c', text: 'value нельзя читать у MutableStateFlow' },
      { id: 'd', text: 'update сохраняет историю всех состояний' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`update` предотвращает lost update при конкурирующих read-modify-write операциях.',
      mechanism: 'CAS сравнивает исходное значение с текущим; если другой writer успел обновить state, transform вычисляется заново относительно нового состояния.',
      trap: 'Раздельное чтение и присваивание не образуют атомарную операцию и могут потерять одно из добавлений.',
      example: 'Два параллельных `addItem` должны сохранить оба item, а не последний записавшийся snapshot.',
    },
    source: { file: '08-coroutines-android.md', section: '4.5. Потокобезопасное состояние' },
    tags: ['StateFlow', 'atomicity', 'update'],
  },
  {
    id: 'coroutines-038',
    topicId: 'coroutines',
    subtopic: 'TTL cache',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Какие два design-review замечания верны для простого TTL cache, вызывающего loader внутри mutex.withLock?',
    options: [
      { id: 'a', text: 'Loader под mutex сериализует даже разные ключи; Clock следует инъецировать для детерминированных тестов' },
      { id: 'b', text: 'Mutex делает loader параллельным; системные часы автоматически виртуальны в runTest' },
      { id: 'c', text: 'TTL исключает необходимость синхронизации; Clock нельзя подменять' },
      { id: 'd', text: 'Истёкшие записи автоматически удаляются Kotlin runtime; loader никогда не suspend' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Наивная корректность достигается ценой глобальной сериализации, а время должно быть управляемой зависимостью.',
      mechanism: 'Один mutex удерживается на всей suspend-загрузке, поэтому miss ключа A блокирует miss ключа B; injected Clock позволяет без ожидания поставить время до и после expiresAt.',
      trap: 'Вынос loader из lock без single-flight создаст дублирующие одновременные загрузки одного ключа.',
      example: 'Можно совместить короткую mutex-секцию с per-key Deferred и single-flight.',
    },
    source: { file: '08-coroutines-android.md', section: '4.6. Кэш с TTL' },
    tags: ['cache', 'TTL', 'Mutex', 'testing'],
  },
  {
    id: 'coroutines-039',
    topicId: 'coroutines',
    subtopic: 'Code review',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Что не так с кодом `val a = async { loadA() }.await(); val b = async { loadB() }.await()`?',
    options: [
      { id: 'a', text: 'Немедленный await первого async не даёт запустить второй до завершения первого, поэтому параллелизма нет' },
      { id: 'b', text: 'async нельзя вызывать для suspend-функций' },
      { id: 'c', text: 'await всегда блокирует поток ОС' },
      { id: 'd', text: 'loadA и loadB обязательно выполнятся дважды' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Последовательность “async + сразу await” эквивалентна последовательному ожиданию.',
      mechanism: 'Выполнение приостанавливается на первом await, и строка создания второго Deferred достигается только после завершения loadA.',
      trap: 'Само наличие `async` не гарантирует параллелизм.',
      example: 'Сначала создайте `val a = async {...}` и `val b = async {...}`, затем вызовите `awaitAll(a, b)`.',
    },
    source: { file: '08-coroutines-android.md', section: '5.2' },
    tags: ['code-review', 'async', 'parallelism'],
  },
  {
    id: 'coroutines-040',
    topicId: 'coroutines',
    subtopic: 'Code review',
    difficulty: 'expert',
    kind: 'code',
    prompt: 'Какой вариант code review полностью корректно описывает четыре ловушки: `catch (Exception)`, `withContext(IO) { emit(...) }` внутри `flow {}`, `Thread.sleep` в suspend-коде и `CoroutineScope(IO)` без владельца?',
    options: [
      { id: 'a', text: 'Нужно пробрасывать cancellation; использовать flowOn; заменить sleep на delay; передать владельцу suspend API или явно управляемый scope' },
      { id: 'b', text: 'Все четыре фрагмента корректны, потому что корутины автоматически управляют lifecycle' },
      { id: 'c', text: 'Достаточно заменить IO на Main во всех четырёх местах' },
      { id: 'd', text: 'Нужно заменить всё на GlobalScope и runBlocking' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Каждая ловушка нарушает отдельный контракт: отмену, context preservation, неблокирующее ожидание или владение lifetime.',
      mechanism: 'Широкий catch поглощает CancellationException; emit из другого context нарушает invariant Flow; Thread.sleep занимает поток и игнорирует отмену; бесхозный scope продолжает работу без точки отмены.',
      trap: 'Механическая замена dispatcher не исправляет ни structured concurrency, ни блокировку, ни Flow invariant.',
      example: 'Ловите конкретные ошибки, применяйте `flowOn(IO)`, используйте `delay` и предпочитайте `suspend fun`, чтобы scope выбирал caller.',
      verification: 'При review отдельно проверьте распространение отмены, контекст emit, блокирующие вызовы и владельца каждого scope.',
    },
    source: { file: '08-coroutines-android.md', section: '5. «Что не так с этим кодом»' },
    tags: ['code-review', 'cancellation', 'flowOn', 'structured-concurrency'],
  },
]
