import type { Question } from '../domain/models'

export const dependencyInjectionQuestions: Question[] = [
  {
    id: 'dependency-injection-001',
    topicId: 'dependency-injection',
    subtopic: 'DI graph',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Что в DI называют графом зависимостей?',
    options: [
      { id: 'a', text: 'Ориентированный граф, где узлы — типы, а ребро A → B означает, что A нужна B' },
      { id: 'b', text: 'Список Gradle-модулей, упорядоченный по времени компиляции' },
      { id: 'c', text: 'Дерево Android-компонентов, построенное только по lifecycle' },
      { id: 'd', text: 'Рантайм-реестр всех созданных объектов, независимо от DI-подхода' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Граф описывает, какие типы нужны для построения других типов.',
      mechanism: 'DI-контейнер начинает с запрошенного узла и проходит по рёбрам до конструкторов, провайдеров или переданных извне значений. Compile-time решения проверяют возможность такого построения при компиляции, runtime-контейнеры — при регистрации или первом разрешении.',
      trap: 'Граф DI не совпадает с графом Gradle-модулей: модули могут влиять на видимость биндингов, но узлами DI-графа остаются ключи зависимостей.',
      verification: 'Попробуйте удалить биндинг транзитивной зависимости: Dagger сообщит MissingBinding и покажет путь от точки запроса.',
    },
    source: { file: '13-di-build-deep.md', section: '1. Зачем DI и что такое граф' },
    tags: ['di', 'graph', 'compile-time', 'runtime'],
  },
  {
    id: 'dependency-injection-002',
    topicId: 'dependency-injection',
    subtopic: 'Dagger code generation',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какая строка верно сопоставляет объявление биндинга и код, генерируемый Dagger?',
    options: [
      { id: 'a', text: '@Inject constructor → MembersInjector; @Binds → отдельная Factory' },
      { id: 'b', text: '@Inject constructor → Foo_Factory; @Provides → метод компонента без фабрики; @Binds → рефлексия' },
      { id: 'c', text: '@Inject constructor → Foo_Factory; @Provides → M_BarFactory; @Binds → отдельный класс-фабрика не нужен' },
      { id: 'd', text: 'Все три формы превращаются в один рефлексивный контейнер' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Конструктор и @Provides получают фабрики, а простой @Binds переписывает ключ на провайдер реализации.',
      mechanism: 'Foo_Factory вызывает @Inject-конструктор, M_BarFactory вызывает метод модуля, а DaggerAppComponent соединяет провайдеры. Для @Binds нет тела, которое нужно вызывать, поэтому отдельный класс-фабрика не создаётся.',
      trap: 'Foo_MembersInjector относится к инъекции полей, а не к @Inject-конструктору. Dagger не использует рефлексию.',
      verification: 'Сгенерированные классы можно открыть в build/generated и сравнить с объявлениями в исходниках.',
    },
    source: { file: '13-di-build-deep.md', section: '2.1. Что генерируется' },
    tags: ['dagger', 'codegen', 'inject', 'provides', 'binds'],
  },
  {
    id: 'dependency-injection-003',
    topicId: 'dependency-injection',
    subtopic: 'Dagger fastInit',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'После включения fastInit старт улучшился, но утёк один Provider из большого компонента. Какое последствие наиболее точно?',
    options: [
      { id: 'a', text: 'Утечёт только фабрика непосредственной зависимости Provider' },
      { id: 'b', text: 'Provider может удержать SwitchingProvider и через него весь компонент со скоупнутыми объектами' },
      { id: 'c', text: 'Ничего не утечёт: fastInit хранит только числовой id без ссылок' },
      { id: 'd', text: 'Утечёт только последний созданный unscoped-объект' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'В fastInit утечка Provider может быть эквивалентна утечке всего компонента.',
      mechanism: 'SwitchingProvider объединяет создание многих типов в switch по id и держит ссылку на компонент. Это сокращает число классов, загружаемых при инициализации, но расширяет поверхность удержания.',
      trap: 'Компромисс fastInit — не доказанное замедление каждого get(), а старт против более опасного удержания компонента.',
      verification: 'В сгенерированном компоненте найдите SwitchingProvider и проверьте, что он обращается к полям компонента.',
    },
    source: { file: '13-di-build-deep.md', section: '2.3. `fastInit` и `SwitchingProvider`' },
    tags: ['dagger', 'fastInit', 'SwitchingProvider', 'leak', 'startup'],
    version: { asOf: 'Dagger 2.60.1, 2026-06', reviewAfter: '2027-01' },
  },
  {
    id: 'dependency-injection-004',
    topicId: 'dependency-injection',
    subtopic: 'Binding graph validation',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой дефект Dagger обязан превратить в ошибку компиляции при проверке полного графа?',
    options: [
      { id: 'a', text: 'Медленный сетевой запрос внутри @Provides' },
      { id: 'b', text: 'Утечку Activity через статическое поле сторонней библиотеки' },
      { id: 'c', text: 'Отсутствующий биндинг или цикл обычных constructor-зависимостей' },
      { id: 'd', text: 'Неправильное бизнес-значение, возвращённое фабрикой' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Структурные дефекты графа — MissingBinding, дубликаты, циклы и конфликты скоупов — проверяются при компиляции.',
      mechanism: 'Процессор строит модель достижимых биндингов до генерации компонента. Он проверяет наличие ключей, уникальность, циклы и допустимость размещения скоупнутых биндингов.',
      trap: 'Dagger проверяет структуру, но не исполняет пользовательский код @Provides и не доказывает отсутствие произвольных утечек.',
      verification: 'Диагностики содержат метки вроде [Dagger/MissingBinding] и [Dagger/DependencyCycle].',
    },
    source: { file: '13-di-build-deep.md', section: '2.4. Что реально означает «граф проверяется на компиляции»' },
    tags: ['dagger', 'validation', 'MissingBinding', 'DependencyCycle'],
  },
  {
    id: 'dependency-injection-005',
    topicId: 'dependency-injection',
    subtopic: 'Bindings',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Для простого связывания интерфейса с реализацией какой вариант предпочтителен?',
    code: {
      language: 'kotlin',
      value: 'class UserRepositoryImpl @Inject constructor() : UserRepository',
    },
    options: [
      { id: 'a', text: '@Provides fun repo() = UserRepositoryImpl()' },
      { id: 'b', text: '@Binds fun bind(impl: UserRepositoryImpl): UserRepository в abstract/interface-модуле' },
      { id: 'c', text: '@BindsInstance fun bind(impl: UserRepositoryImpl): UserRepository' },
      { id: 'd', text: '@IntoSet fun bind(impl: UserRepositoryImpl): UserRepository' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '@Binds выражает перенаправление «интерфейс → реализация» без вызова метода-провайдера.',
      mechanism: 'Абстрактный метод принимает ровно одну присваиваемую реализацию и возвращает интерфейс. Dagger использует провайдер реализации для запросов интерфейса, не создавая фабрику для тела @Provides.',
      trap: '@BindsInstance передаёт уже существующее значение при создании компонента, а не связывает типы внутри модуля.',
      example: 'Скоуп и квалификатор при необходимости ставятся на метод @Binds.',
    },
    source: { file: '13-di-build-deep.md', section: '3.3. `@Binds` — когда нужно только «интерфейс → реализация»' },
    tags: ['dagger', 'binds', 'provides', 'binding'],
  },
  {
    id: 'dependency-injection-006',
    topicId: 'dependency-injection',
    subtopic: 'Qualifiers',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'В графе есть обычный и авторизованный OkHttpClient. Как надёжнее выбрать авторизованный?',
    options: [
      { id: 'a', text: 'Положиться на порядок методов @Provides' },
      { id: 'b', text: 'Пометить биндинг и место инъекции типизированным пользовательским @Qualifier' },
      { id: 'c', text: 'Поставить @Singleton только на авторизованный клиент' },
      { id: 'd', text: 'Назвать параметр конструктора authorizedClient' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Квалификатор становится частью ключа биндинга и устраняет неоднозначность одинаковых типов.',
      mechanism: 'Одна и та же аннотация @Qualifier должна стоять на предоставлении и запросе. Пользовательский квалификатор проверяется компилятором и безопаснее строкового @Named.',
      trap: 'Скоуп определяет кэширование, а имя Kotlin-параметра не участвует в разрешении ключа Dagger.',
      example: '@AuthorizedClient annotation class AuthorizedClient и @AuthorizedClient client: OkHttpClient.',
    },
    source: { file: '13-di-build-deep.md', section: '3.4. Квалификаторы: два объекта одного типа' },
    tags: ['dagger', 'qualifier', 'Named', 'binding-key'],
  },
  {
    id: 'dependency-injection-007',
    topicId: 'dependency-injection',
    subtopic: 'BindsInstance',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Компоненту нужен Application, который Dagger не должен создавать. Как передать его с обязательной проверкой при создании?',
    options: [
      { id: 'a', text: 'Через @Component.Factory.create(@BindsInstance application: Application)' },
      { id: 'b', text: 'Через @Inject constructor у Application' },
      { id: 'c', text: 'Через @Multibinds Set<Application>' },
      { id: 'd', text: 'Через lateinit-поле в сгенерированном компоненте' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '@BindsInstance вводит в граф значение, известное только при создании компонента.',
      mechanism: 'Фабрика компонента принимает все параметры одним вызовом, поэтому обязательное значение нельзя забыть. Builder удобнее, только когда нужны отдельные сеттеры или опциональная настройка.',
      trap: 'Application создаёт Android, а не Dagger; попытка представить его обычным constructor-биндингом неверна.',
      example: 'DaggerAppComponent.factory().create(application).',
    },
    source: { file: '13-di-build-deep.md', section: '3.5. `@BindsInstance`: как в граф попадает то, чего в графе нет' },
    tags: ['dagger', 'BindsInstance', 'component-factory', 'runtime-value'],
  },
  {
    id: 'dependency-injection-008',
    topicId: 'dependency-injection',
    subtopic: 'Lazy and Provider',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Как верно различить dagger.Lazy<Foo> и Provider<Foo> для unscoped-биндинга?',
    options: [
      { id: 'a', text: 'Lazy создаёт Foo при каждом get(), Provider мемоизирует первый результат' },
      { id: 'b', text: 'Оба всегда возвращают один объект на компонент' },
      { id: 'c', text: 'Lazy мемоизирует внутри данного Lazy, Provider повторяет запрос к графу при каждом get()' },
      { id: 'd', text: 'Provider работает только со скоупнутыми биндингами' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Lazy откладывает и запоминает один результат, Provider повторяет разрешение зависимости.',
      mechanism: 'Для unscoped @Inject-конструктора повторный Provider.get() создаёт новый объект. Для scoped-биндинга Provider всё равно получает закэшированный объект компонента.',
      trap: 'Lazy не является скоупом: два независимо инжектнутых Lazy могут мемоизировать два разных unscoped-экземпляра.',
      example: 'dagger.Lazy использует get(), тогда как kotlin.Lazy — value; неверный импорт ломает код.',
    },
    source: { file: '13-di-build-deep.md', section: '3.6. `Lazy`, `Provider` и разрыв циклов' },
    tags: ['dagger', 'Lazy', 'Provider', 'scope'],
  },
  {
    id: 'dependency-injection-009',
    topicId: 'dependency-injection',
    subtopic: 'Dependency cycles',
    difficulty: 'expert',
    kind: 'code',
    prompt: 'Как корректно разорвать цикл A → B → A?',
    code: {
      language: 'kotlin',
      value: 'class A @Inject constructor(val b: B)\nclass B @Inject constructor(/* dependency on A */)',
    },
    options: [
      { id: 'a', text: 'Передать в B Provider<A> и вызывать get() только при фактическом использовании' },
      { id: 'b', text: 'Передать в B Provider<A> и вызвать get() в init-блоке B' },
      { id: 'c', text: 'Добавить @Singleton на A и B без изменения зависимостей' },
      { id: 'd', text: 'Заменить @Inject на @Provides, сохранив прямой цикл' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Provider или Lazy откладывает один край цикла, пока конструирование текущей цепочки не закончено.',
      mechanism: 'При создании B передаётся оболочка, а не готовый A. Вызов get() позже начинает новый запрос уже после завершения исходной конструкции.',
      trap: 'get() в конструкторе или init немедленно восстанавливает цикл и для scoped-графа может привести к reentrantCheck-исключению DoubleCheck.',
      verification: 'Прямой цикл даёт [Dagger/DependencyCycle]; отложенный край должен исчезнуть из цепочки немедленного создания.',
    },
    source: { file: '13-di-build-deep.md', section: '3.6. `Lazy`, `Provider` и разрыв циклов' },
    tags: ['dagger', 'cycle', 'Provider', 'Lazy', 'DoubleCheck'],
  },
  {
    id: 'dependency-injection-010',
    topicId: 'dependency-injection',
    subtopic: 'Multibindings',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Фича может не внести ни одного AppInitializer, но Set<AppInitializer> всё равно должен разрешаться. Что нужно?',
    options: [
      { id: 'a', text: 'Абстрактное объявление Set<AppInitializer> с @Multibinds' },
      { id: 'b', text: '@ElementsIntoSet, возвращающий null' },
      { id: 'c', text: '@IntoSet на @Inject-конструкторе' },
      { id: 'd', text: '@BindsOptionalOf для Set<AppInitializer>' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '@Multibinds заранее объявляет коллекционный биндинг, который может остаться пустым.',
      mechanism: 'Без единого вклада Set<T> отсутствует в графе и запрос завершится MissingBinding. Абстрактный @Multibinds-метод не вызывается — он сообщает генератору о допустимой пустой коллекции.',
      trap: '@ElementsIntoSet вносит элементы существующего Set, а мультибиндинг-аннотации нельзя ставить на @Inject-конструктор.',
      example: 'Полезно для вариантов сборки, где модуль с @IntoSet-вкладами отключён.',
    },
    source: { file: '13-di-build-deep.md', section: '3.7. Мультибиндинги' },
    tags: ['dagger', 'multibindings', 'Multibinds', 'IntoSet'],
  },
  {
    id: 'dependency-injection-011',
    topicId: 'dependency-injection',
    subtopic: 'Map multibindings',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Большая Map<Class<*>, Handler> не должна загружать все классы-ключи при построении. Какой механизм предназначен для этого?',
    options: [
      { id: 'a', text: '@ClassKey вместе с eager Provider.get() для всех значений' },
      { id: 'b', text: '@LazyClassKey, не вызывая keySet()/entrySet() без необходимости' },
      { id: 'c', text: '@StringKey с Class.forName() для каждого элемента на старте' },
      { id: 'd', text: '@ElementsIntoSet вместо карты' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '@LazyClassKey откладывает загрузку class-ключа до обращения к конкретной записи.',
      mechanism: 'Под капотом Dagger строит представление со строковыми ключами и загружает класс точечно. Перебор keySet или entrySet вынуждает загрузить всё и уничтожает преимущество.',
      trap: '@LazyClassKey нельзя смешивать с @ClassKey для того же типа карты.',
      example: 'Отдельно от ключей Map<K, Provider<V>> откладывает создание значений.',
    },
    source: { file: '13-di-build-deep.md', section: '3.7. Мультибиндинги' },
    tags: ['dagger', 'multibindings', 'LazyClassKey', 'ClassKey', 'startup'],
    version: { asOf: 'Dagger 2.60.1, 2026-06', reviewAfter: '2027-01' },
  },
  {
    id: 'dependency-injection-012',
    topicId: 'dependency-injection',
    subtopic: 'Assisted injection',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'ReportGenerator зависит от ReportRepository из графа и reportId, известного только при клике. Как смоделировать создание?',
    options: [
      { id: 'a', text: '@AssistedInject-конструктор, @Assisted reportId и инъекция @AssistedFactory' },
      { id: 'b', text: '@Singleton на ReportGenerator и изменение reportId через var' },
      { id: 'c', text: '@BindsInstance reportId при создании SingletonComponent приложения' },
      { id: 'd', text: 'Прямая инъекция ReportGenerator без фабрики' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Assisted injection разделяет зависимости конструктора на графовые и передаваемые вызывающим кодом.',
      mechanism: 'Dagger генерирует реализацию @AssistedFactory; её create принимает все @Assisted-параметры, а обычные параметры получает из графа.',
      trap: 'Сам @AssistedInject-тип нельзя инжектить и нельзя скоупить: инжектируется только его фабрика.',
      example: 'Для однотипных assisted-параметров метка @Assisted("name") должна совпадать в конструкторе и фабрике.',
    },
    source: { file: '13-di-build-deep.md', section: '3.9. Assisted-инъекция: часть параметров из графа, часть с места вызова' },
    tags: ['dagger', 'assisted-injection', 'AssistedFactory', 'runtime-arguments'],
  },
  {
    id: 'dependency-injection-013',
    topicId: 'dependency-injection',
    subtopic: 'Scopes',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Что фактически делает @Scope в Dagger?',
    options: [
      { id: 'a', text: 'Создаёт глобальный runtime-реестр объектов по имени аннотации' },
      { id: 'b', text: 'На компиляции включает проверку совместимости и генерацию кэша в экземпляре компонента' },
      { id: 'c', text: 'Автоматически подписывает объект на Android lifecycle' },
      { id: 'd', text: 'Запрещает сборщику мусора освобождать объект до завершения процесса' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Скоуп — compile-time метка, по которой Dagger валидирует граф и генерирует кэширование.',
      mechanism: 'Скоупнутый провайдер хранится в поле компонента и мемоизирует значение. Время жизни определяется временем жизни экземпляра компонента, а не самой аннотацией.',
      trap: 'Пользовательский @ActivityScope ничего не знает об Activity: связать создание и отпускание компонента с lifecycle обязан владелец.',
      verification: 'В сгенерированном коде нет карты аннотаций скоупов — есть поля провайдеров.',
    },
    source: { file: '13-di-build-deep.md', section: '4.1. `@Scope` — это метка для компилятора, а не механизм рантайма' },
    tags: ['dagger', 'scope', 'component', 'codegen'],
  },
  {
    id: 'dependency-injection-014',
    topicId: 'dependency-injection',
    subtopic: 'DoubleCheck',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Зачем DoubleCheck после первого успешного создания присваивает provider = null?',
    options: [
      { id: 'a', text: 'Чтобы следующий get() обязательно создал новый объект' },
      { id: 'b', text: 'Чтобы освободить фабрику и удерживаемые только ею зависимости для GC' },
      { id: 'c', text: 'Чтобы снять volatile-семантику с поля instance' },
      { id: 'd', text: 'Чтобы удалить биндинг из графа Dagger' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'После мемоизации результата исходная фабрика больше не нужна и её ссылку можно отпустить.',
      mechanism: 'DoubleCheck хранит volatile instance и создаёт его под synchronized со второй проверкой. Последующие get() идут по быстрому пути и возвращают instance, поэтому provider можно обнулить.',
      trap: 'Обнуление provider не отменяет кэш: сам instance остаётся полем DoubleCheck.',
      verification: 'Двойная проверка вместе с volatile гарантирует безопасную публикацию и один scoped-результат при конкурентных запросах.',
    },
    source: { file: '13-di-build-deep.md', section: '4.2. Что генерируется для скоупнутого биндинга: `DoubleCheck`' },
    tags: ['dagger', 'DoubleCheck', 'thread-safety', 'gc', 'scope'],
  },
  {
    id: 'dependency-injection-015',
    topicId: 'dependency-injection',
    subtopic: 'Scope lifetime',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'Приложение создало два экземпляра @Singleton AppComponent. Сколько экземпляров одного @Singleton-биндинга возможно?',
    options: [
      { id: 'a', text: 'Ровно один на процесс' },
      { id: 'b', text: 'До двух: по одному на каждый экземпляр компонента' },
      { id: 'c', text: 'Ни одного, потому что @Singleton запрещает второй компонент' },
      { id: 'd', text: 'Число определяется только количеством потоков' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '@Singleton означает один экземпляр биндинга на экземпляр компонента, а не на процесс.',
      mechanism: 'Каждый сгенерированный компонент имеет собственное поле DoubleCheck и собственный кэш. Аннотация не координирует независимые объекты компонентов.',
      trap: 'Имя Singleton исторически вводит в заблуждение; глобальность появляется только если приложение само создаёт и удерживает единственный AppComponent.',
      example: 'Выход из скоупа — отпустить все ссылки на компонент; component.destroy() не существует.',
    },
    source: { file: '13-di-build-deep.md', section: '4.3. Главное следствие: скоуп — это время жизни экземпляра компонента' },
    tags: ['dagger', 'Singleton', 'component', 'lifetime'],
  },
  {
    id: 'dependency-injection-016',
    topicId: 'dependency-injection',
    subtopic: 'Reusable scope',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Для какого объекта @Reusable наиболее уместен?',
    options: [
      { id: 'a', text: 'Изменяемый счётчик, который обязан быть единственным во всех потоках' },
      { id: 'b', text: 'Соединение с БД, которое нельзя создать дважды' },
      { id: 'c', text: 'Stateless JsonParser, который дёшево продублировать, но не хочется создавать на каждый запрос' },
      { id: 'd', text: 'Activity, которую нужно удерживать до конца процесса' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: '@Reusable разрешает, но не гарантирует переиспользование и подходит stateless-объектам.',
      mechanism: 'Dagger применяет SingleCheck: использующий компонент может закэшировать значение, однако конкурентные запросы способны создать два экземпляра. Кэш может различаться между независимыми сабкомпонентами.',
      trap: '@Reusable не даёт строгой идентичности и потому опасен для состояния, ресурсов и соединений.',
      verification: 'В отличие от обычного скоупа, валидатор межкомпонентных скоупов @Reusable пропускает.',
    },
    source: { file: '13-di-build-deep.md', section: '4.4. Без скоупа и `@Reusable`' },
    tags: ['dagger', 'Reusable', 'SingleCheck', 'scope'],
  },
  {
    id: 'dependency-injection-017',
    topicId: 'dependency-injection',
    subtopic: 'Scope validation',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Какая конфигурация скоупов допустима для сабкомпонентов?',
    options: [
      { id: 'a', text: 'Родитель и его прямой ребёнок оба @Singleton' },
      { id: 'b', text: 'Два sibling-экранных сабкомпонента оба @ScreenScope' },
      { id: 'c', text: 'Unscoped-компонент с транзитивным @Singleton-биндингом' },
      { id: 'd', text: '@ActivityScope-биндинг внутри компонента, помеченного только @Singleton' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Сиблинги могут использовать одну аннотацию скоупа, потому что не достижимы друг из друга.',
      mechanism: 'Каждый sibling-компонент имеет отдельное поле-кэш и отдельный экземпляр «того же» скоупа. Предок и потомок с одной аннотацией запрещены: было бы неоднозначно, где кэшировать биндинг.',
      trap: 'Одинаковое имя аннотации не объединяет независимые компоненты в общий runtime-скоуп.',
      verification: 'Конфликт предка и потомка диагностируется как has conflicting scopes.',
    },
    source: { file: '13-di-build-deep.md', section: '4.5. Правила скоупов, которые знает компилятор' },
    tags: ['dagger', 'scope-validation', 'subcomponent', 'siblings'],
  },
  {
    id: 'dependency-injection-018',
    topicId: 'dependency-injection',
    subtopic: 'Custom scopes',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Что обязательно кроме объявления @FeatureScope, чтобы его время жизни действительно совпало с жизнью фичи в чистом Dagger?',
    options: [
      { id: 'a', text: 'Только поставить @FeatureScope на класс; Dagger сам найдёт lifecycle' },
      { id: 'b', text: 'Создать scoped-компонент и явно удерживать/отпускать его в границах фичи' },
      { id: 'c', text: 'Добавить component.destroy(), который Dagger сгенерирует автоматически' },
      { id: 'd', text: 'Сделать все зависимости компонента @Singleton' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Аннотация задаёт правила кэша, но жизненным циклом экземпляра компонента управляет приложение.',
      mechanism: 'Нужны компонент или сабкомпонент с тем же скоупом, установка его фабрики в родителя и holder, который создаёт компонент при входе и теряет ссылку при выходе.',
      trap: 'Забытый close у holder удерживает компонент и все его scoped-поля; отдельного destroy API нет.',
      example: 'Скоуп лучше называть по времени жизни — @ScreenScope, а не по бизнес-задаче.',
    },
    source: { file: '13-di-build-deep.md', section: '4.6. Свой скоуп: как сделать' },
    tags: ['dagger', 'custom-scope', 'subcomponent', 'lifetime', 'leak'],
  },
  {
    id: 'dependency-injection-019',
    topicId: 'dependency-injection',
    subtopic: 'Component relationships',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Фича в отдельном Gradle-модуле должна видеть только явный контракт app-компонента. Какую связь выбрать?',
    options: [
      { id: 'a', text: '@Subcomponent, потому что он скрывает весь родительский граф' },
      { id: 'b', text: '@Component(dependencies = [AppDependencies::class]) с явными provision-методами' },
      { id: 'c', text: 'Одинаковый @Singleton на двух независимых компонентах без связи' },
      { id: 'd', text: '@BindsInstance для передачи самого Gradle-проекта' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Component dependency даёт изоляцию через интерфейс: доступно только явно выставленное.',
      mechanism: 'Зависимый компонент компилируется против контракта и может находиться в отдельном модуле. Сабкомпонент генерируется внутри родителя и видит весь его граф, что создаёт более жёсткую связь.',
      trap: 'Сабкомпонент компактнее и удобен внутри одного модуля, но не обеспечивает требуемую границу видимости.',
      example: 'У component dependencies собственные правила иерархии скоупов; нельзя переносить на них упрощённое правило сабкомпонентов.',
    },
    source: { file: '13-di-build-deep.md', section: '4.7. Сабкомпонент против зависимости компонентов' },
    tags: ['dagger', 'component-dependency', 'subcomponent', 'modularity'],
  },
  {
    id: 'dependency-injection-020',
    topicId: 'dependency-injection',
    subtopic: 'Hilt components',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Почему ActivityRetainedComponent переживает configuration change?',
    options: [
      { id: 'a', text: 'Он хранится в статическом поле Hilt' },
      { id: 'b', text: 'Его держит ViewModel в ViewModelStore Activity до окончательного уничтожения' },
      { id: 'c', text: 'Его сериализует SavedStateHandle' },
      { id: 'd', text: 'ActivityComponent никогда не уничтожается при повороте' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Hilt использует существующий механизм ViewModelStore, а не отдельную магию lifecycle.',
      mechanism: 'ActivityRetainedComponentViewModel хранит компонент в поле. При повороте ViewModelStore сохраняется, а при окончательном уходе Activity вызывается onCleared и компонент становится доступен для освобождения.',
      trap: 'ActivityComponent привязан к конкретному экземпляру Activity и при пересоздании создаётся заново.',
      example: '@ActivityRetainedScoped живёт дольше @ActivityScoped, но короче @Singleton.',
    },
    source: { file: '13-di-build-deep.md', section: '4.8. Скоупы Hilt: что физически держит компонент' },
    tags: ['hilt', 'ActivityRetainedComponent', 'ViewModelStore', 'lifecycle'],
  },
  {
    id: 'dependency-injection-021',
    topicId: 'dependency-injection',
    subtopic: 'Hilt custom components',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Какое ограничение действует для собственного Hilt-компонента с @DefineComponent?',
    options: [
      { id: 'a', text: 'Его можно вставить между ActivityComponent и FragmentComponent' },
      { id: 'b', text: 'Он может иметь несколько родителей и образовывать ромб' },
      { id: 'c', text: 'Доступ к биндингам организуют через @EntryPoint, а жизнью экземпляра управляет приложение' },
      { id: 'd', text: 'Методы provision следует объявлять прямо на интерфейсе @DefineComponent' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Custom Hilt component расширяет иерархию, но не получает автоматического владельца lifecycle.',
      mechanism: 'Компонент должен быть потомком SingletonComponent, иметь одного родителя, builder и точки доступа @EntryPoint. Создание, хранение и отпускание экземпляра остаются обязанностью кода приложения.',
      trap: 'Нельзя вставлять свой компонент между стандартными Hilt-компонентами или объявлять методы доступа прямо на @DefineComponent.',
      example: 'Компонент оправдан, когда есть чёткая граница жизни и вклады из нескольких модулей.',
    },
    source: { file: '13-di-build-deep.md', section: '4.9. Свой компонент в Hilt: `@DefineComponent`' },
    tags: ['hilt', 'DefineComponent', 'EntryPoint', 'custom-scope'],
  },
  {
    id: 'dependency-injection-022',
    topicId: 'dependency-injection',
    subtopic: 'Scope leaks',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой пример является DI-утечкой из-за неверного соотношения времён жизни?',
    options: [
      { id: 'a', text: '@Singleton хранит Activity Context' },
      { id: 'b', text: '@ActivityScoped объект хранит @Singleton API' },
      { id: 'c', text: 'Unscoped use case получает stateless @Reusable parser' },
      { id: 'd', text: 'ViewModel получает SavedStateHandle' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Долгоживущий объект не должен удерживать зависимость с более коротким временем жизни.',
      mechanism: 'Singleton лежит в поле SingletonComponent до конца процесса. Если он ссылается на Activity, цепочка от Application-компонента не даёт старому экземпляру Activity освободиться.',
      trap: 'Обратное направление нормально: короткоживущий объект может ссылаться на более долгоживущий.',
      verification: 'Ищите GC root, затем владельца компонента и scoped-поле; Hilt блокирует многие такие связи compile-time.',
    },
    source: { file: '13-di-build-deep.md', section: '4.10. Утечка скоупа (вопрос 77)' },
    tags: ['di', 'scope', 'memory-leak', 'Context', 'hilt'],
  },
  {
    id: 'dependency-injection-023',
    topicId: 'dependency-injection',
    subtopic: 'Hilt testing',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Нужно заменить NetworkModule на FakeNetworkModule для всего набора Hilt-тестов. Что использовать?',
    options: [
      { id: 'a', text: '@TestInstallIn(components = [...], replaces = [NetworkModule::class])' },
      { id: 'b', text: '@BindValue в production Application' },
      { id: 'c', text: '@UninstallModules в каждом тестовом методе' },
      { id: 'd', text: 'Широкое R8 keep-правило для FakeNetworkModule' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '@TestInstallIn декларативно заменяет production-модуль тестовым для набора тестов.',
      mechanism: 'Тестовый модуль устанавливается в указанные Hilt-компоненты и перечисляет заменяемые модули. Для единичного значения в одном тесте предназначен @BindValue.',
      trap: '@UninstallModules на каждом тесте создаёт повторение и больше уникальных тестовых компонентов.',
      example: 'Fake API можно предоставить обычным @Provides внутри @TestInstallIn-модуля.',
    },
    source: { file: '13-di-build-deep.md', section: '5. Hilt в тестах' },
    tags: ['hilt', 'testing', 'TestInstallIn', 'BindValue'],
  },
  {
    id: 'dependency-injection-024',
    topicId: 'dependency-injection',
    subtopic: 'Hilt test generation',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Почему @EntryPoint-методы в Hilt-тестах должны быть публичными и уникально названными при стандартной конфигурации?',
    options: [
      { id: 'a', text: 'Потому что Hilt по умолчанию может переиспользовать общий сгенерированный тестовый компонент в другом пакете' },
      { id: 'b', text: 'Потому что JVM запрещает перегрузку методов в тестах' },
      { id: 'c', text: 'Потому что R8 всегда обфусцирует тестовые entry points' },
      { id: 'd', text: 'Потому что каждый тест обязательно получает отдельный процесс' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Shared test components сокращают кодогенерацию, но требуют доступного и непротиворечивого API.',
      mechanism: 'Тесты без @BindValue и вложенных модулей могут использовать один компонент. Он генерируется отдельно, поэтому package-private доступ недостаточен, а одинаковые имена методов разных entry point создают конфликт.',
      trap: 'Флаг отключения shared components существует, но обычно правильнее исправить видимость и имена.',
      verification: 'Уникальный @BindValue или nested module заставляет Hilt генерировать специальный компонент для теста.',
    },
    source: { file: '13-di-build-deep.md', section: '5. Hilt в тестах' },
    tags: ['hilt', 'testing', 'codegen', 'EntryPoint'],
    version: { asOf: 'Dagger/Hilt 2.60.1, 2026-06', reviewAfter: '2027-01' },
  },
  {
    id: 'dependency-injection-025',
    topicId: 'dependency-injection',
    subtopic: 'KSP and KAPT',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Проект перевёл Dagger с KAPT на KSP, но оставил один другой KAPT-процессор в каждом модуле. Почему ускорение может быть небольшим?',
    options: [
      { id: 'a', text: 'KSP всё равно всегда вызывает javac дважды' },
      { id: 'b', text: 'Оставшийся KAPT сохраняет генерацию Java-стабов для Kotlin-кода' },
      { id: 'c', text: 'Dagger на KSP автоматически отключает incremental compilation' },
      { id: 'd', text: 'KAPT быстрее KSP только для @Inject-конструкторов' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Основная экономия появляется после удаления последнего KAPT-процессора из модуля.',
      mechanism: 'KAPT должен представить Kotlin-код Java annotation processors через сгенерированные stubs. Пока хоть один такой процессор остаётся, дорогой этап никуда не исчезает; KSP читает Kotlin-модель напрямую.',
      trap: 'Миграция одного процессора не гарантирует исчезновения общей инфраструктурной стоимости KAPT.',
      verification: 'Проверьте build scan и список kapt-задач после миграции последнего процессора.',
    },
    source: { file: '13-di-build-deep.md', section: '6. Цена Dagger на сборке' },
    tags: ['dagger', 'KSP', 'KAPT', 'build-performance', 'stubs'],
  },
  {
    id: 'dependency-injection-026',
    topicId: 'dependency-injection',
    subtopic: 'Hilt compatibility',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Какая пара требований свежих версий Hilt указана верно?',
    options: [
      { id: 'a', text: 'Hilt Gradle plugin 2.58 требует AGP 9; начиная с Hilt 2.60 minSdk — 23' },
      { id: 'b', text: 'Hilt 2.58 требует minSdk 35; Hilt 2.60 требует AGP 7' },
      { id: 'c', text: 'Hilt 2.60 добавил поддержку Kotlin/Native и снизил minSdk до 14' },
      { id: 'd', text: 'Hilt 2.58 отключил кодогенерацию и перешёл на runtime reflection' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Обновление Hilt нужно проверять вместе с версиями AGP и минимальным Android API.',
      mechanism: 'Gradle-плагин Hilt 2.58 требует AGP 9, а с 2.60 минимальный API Hilt равен 23 и поддержка multidex из Hilt удалена.',
      trap: 'Это быстро устаревающие ограничения; перед миграцией их нужно сверять с release notes, а не переносить из старого проекта.',
      verification: 'Проверяйте version matrix до обновления dependency и Gradle plugin.',
    },
    source: { file: '13-di-build-deep.md', section: '6. Цена Dagger на сборке' },
    tags: ['hilt', 'AGP', 'minSdk', 'compatibility', 'version'],
    version: { asOf: 'Hilt 2.60.1, AGP 9, 2026-06', reviewAfter: '2026-12' },
  },
  {
    id: 'dependency-injection-027',
    topicId: 'dependency-injection',
    subtopic: 'DI alternatives',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Команда выбирает между Dagger/Hilt, compiler-plugin DI и runtime-контейнером. Какой критерий сравнения наиболее содержателен?',
    options: [
      { id: 'a', text: 'Только количество аннотаций в README' },
      { id: 'b', text: 'Когда обнаруживаются ошибки графа и чем платят: сборкой, стартом, сложностью и ограничениями платформ' },
      { id: 'c', text: 'Какой фреймворк чаще упоминается в вакансиях' },
      { id: 'd', text: 'Есть ли у библиотеки аннотация @Singleton с таким именем' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Выбор DI — это обмен времени и места обнаружения ошибок на стоимость сборки, старта и внедрения.',
      mechanism: 'Dagger проверяет и генерирует код до запуска, runtime-контейнер резолвит в приложении, а compiler plugin пытается сохранить compile-time проверки без отдельного прохода генерации исходников.',
      trap: 'Нельзя сводить сравнение к «compile-time всегда лучше»: небольшой KMP-проект может выиграть от ручного DI или другого подхода.',
      example: 'Нужно отдельно оценить ABI-изменения, cold start, KMP, размер графа и компетенции команды.',
    },
    source: { file: '13-di-build-deep.md', section: '7.1. Три подхода' },
    tags: ['di', 'dagger', 'hilt', 'koin', 'compiler-plugin', 'tradeoffs'],
  },
  {
    id: 'dependency-injection-028',
    topicId: 'dependency-injection',
    subtopic: 'Runtime DI performance',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Есть подозрение, что регистрация 500 Koin-биндингов ухудшает cold start. Как проверить гипотезу?',
    options: [
      { id: 'a', text: 'Посчитать строки DSL и умножить на фиксированную стоимость биндинга' },
      { id: 'b', text: 'Обернуть startKoin trace-секцией и сравнить Macrobenchmark cold start с пустым/полным графом' },
      { id: 'c', text: 'Измерить только clean build Gradle' },
      { id: 'd', text: 'Проверить размер mapping.txt' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Стоимость runtime-контейнера нужно измерять в процессе запуска, а не оценивать по размеру DSL.',
      mechanism: 'Trace показывает регистрацию, Macrobenchmark — влияние на пользовательский cold start. Сравнение CompilationMode.None/Full и контрольного пустого модуля отделяет контейнер от компиляции и остальной инициализации.',
      trap: 'Build time и startup time — разные метрики; быстрый Gradle ничего не доказывает о регистрации runtime-графа.',
      example: 'Если дорого, лениво загружайте модули, уменьшайте стартовый граф и откладывайте тяжёлые объекты.',
    },
    source: { file: '13-di-build-deep.md', section: '7.3. Стоимость Koin на старте (follow-up к вопросу 76)' },
    tags: ['koin', 'runtime-di', 'startup', 'Macrobenchmark', 'measurement'],
  },
  {
    id: 'dependency-injection-029',
    topicId: 'dependency-injection',
    subtopic: 'ViewModel DI',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'OrderViewModel нужен orderId, являющийся частью навигационного состояния и обязанный пережить process death. Какой путь предпочтителен?',
    options: [
      { id: 'a', text: 'Инжектить Activity и читать Intent при каждом обращении' },
      { id: 'b', text: 'Получать orderId из SavedStateHandle в @HiltViewModel' },
      { id: 'c', text: 'Хранить orderId в @Singleton mutable property' },
      { id: 'd', text: 'Всегда использовать assisted-аргумент без сохранения' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Навигационное состояние следует получать через SavedStateHandle, чтобы оно восстанавливалось после смерти процесса.',
      mechanism: '@HiltViewModel создаётся через ViewModelProvider и получает SavedStateHandle из ViewModelComponent. Assisted creation уместнее для данных, которые не требуется восстанавливать.',
      trap: 'ViewModel переживает конкретный Activity instance, поэтому ссылка на Activity или UI Context нарушает времена жизни.',
      example: 'Для старого Dagger-подхода применяли Map<Class<out ViewModel>, Provider<ViewModel>> и общую factory.',
    },
    source: { file: '13-di-build-deep.md', section: '7.5. Как давать зависимости ViewModel (вопрос 75)' },
    tags: ['hilt', 'ViewModel', 'SavedStateHandle', 'assisted-injection', 'lifecycle'],
  },
  {
    id: 'dependency-injection-030',
    topicId: 'dependency-injection',
    subtopic: 'Build performance',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему запрос «ускорить сборку» недостаточно конкретен?',
    options: [
      { id: 'a', text: 'Потому что Gradle умеет оптимизировать только clean build' },
      { id: 'b', text: 'Нужно различать clean, incremental с ABI-изменением, incremental без ABI-изменения и configuration phase' },
      { id: 'c', text: 'Потому что скорость сборки полностью определяется CPU' },
      { id: 'd', text: 'Потому что build scan работает только в CI' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'У разных фаз и сценариев разные узкие места и способы оптимизации.',
      mechanism: 'ABI-изменение распространяет перекомпиляцию на потребителей, изменение тела часто локально, clean исключает reuse, а configuration phase зависит от скриптов и configuration cache.',
      trap: 'Одна средняя цифра может скрыть регрессию ежедневной incremental-сборки за улучшением редкого clean build.',
      verification: 'Сначала фиксируют сценарий и смотрят build scan, Build Analyzer или --profile.',
    },
    source: { file: '13-di-build-deep.md', section: '8.1. Сначала измерить' },
    tags: ['gradle', 'build-performance', 'ABI', 'profiling'],
  },
  {
    id: 'dependency-injection-031',
    topicId: 'dependency-injection',
    subtopic: 'Gradle caches',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Чем build cache принципиально отличается от configuration cache?',
    options: [
      { id: 'a', text: 'Build cache хранит результаты задач, configuration cache — результат конфигурации task graph' },
      { id: 'b', text: 'Build cache хранит только зависимости, configuration cache — APK' },
      { id: 'c', text: 'Configuration cache переиспользует скомпилированные class-файлы, build cache — build.gradle' },
      { id: 'd', text: 'Разницы нет: это два имени одного механизма' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Кэши устраняют работу на разных фазах: выполнение задач и конфигурацию сборки.',
      mechanism: 'Build cache восстанавливает outputs кэшируемых задач локально или удалённо. Configuration cache сохраняет модель настроенной сборки, не выполняя build.gradle заново при совместимом повторном запуске.',
      trap: 'Configuration cache не включён автоматически и требует, чтобы задачи не обращались к Project во время execution.',
      example: 'Удалённый build cache особенно ценен после git pull и в CI, где артефакты делятся между машинами.',
    },
    source: { file: '13-di-build-deep.md', section: '8.2. Кэши' },
    tags: ['gradle', 'build-cache', 'configuration-cache', 'CI'],
  },
  {
    id: 'dependency-injection-032',
    topicId: 'dependency-injection',
    subtopic: 'Convention plugins',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Где предпочтительно хранить convention plugins большого мультимодульного проекта?',
    options: [
      { id: 'a', text: 'Копировать в build.gradle.kts каждого модуля' },
      { id: 'b', text: 'В отдельном included build, например build-logic' },
      { id: 'c', text: 'В AndroidManifest.xml app-модуля' },
      { id: 'd', text: 'Только в settings локальной Android Studio' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Included build централизует соглашения без широкой инвалидации, характерной для buildSrc.',
      mechanism: 'Convention plugin настраивает compileSdk, Compose, тесты, анализ и общие зависимости одним id. Отдельный build-logic имеет явные границы и лучше масштабируется инкрементально.',
      trap: 'buildSrc удобен для старта, но любое его изменение инвалидирует всю сборку проекта.',
      example: 'Version catalog решает централизацию версий, а convention plugin — централизацию поведения сборки.',
    },
    source: { file: '13-di-build-deep.md', section: '8.3. Version catalogs и convention plugins (вопрос 79)' },
    tags: ['gradle', 'convention-plugins', 'build-logic', 'buildSrc', 'version-catalog'],
  },
  {
    id: 'dependency-injection-033',
    topicId: 'dependency-injection',
    subtopic: 'Incremental builds',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какое изменение обычно уменьшает каскадную перекомпиляцию мультимодульного проекта?',
    options: [
      { id: 'a', text: 'Заменить implementation на api для всех зависимостей' },
      { id: 'b', text: 'Использовать implementation вместо api там, где типы не являются публичным контрактом' },
      { id: 'c', text: 'Включить R8 для каждой debug-сборки' },
      { id: 'd', text: 'Объединить все модули в один плоский модуль независимо от измерений' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'implementation скрывает зависимость от потребителей и сужает область ABI-инвалидации.',
      mechanism: 'Если зависимость не экспортируется, изменения её API не обязаны перекомпилировать всех транзитивных потребителей текущего модуля. Это одновременно ускорение и архитектурная граница.',
      trap: 'api нужен, когда тип реально присутствует в публичном контракте; механическая замена без проверки сломает компиляцию потребителей.',
      example: 'Также важны высота графа модулей, полный отказ от KAPT и отключённый R8 в debug.',
    },
    source: { file: '13-di-build-deep.md', section: '8.4. Остальное, что реально помогает' },
    tags: ['gradle', 'implementation', 'api', 'incremental-build', 'ABI'],
  },
  {
    id: 'dependency-injection-034',
    topicId: 'dependency-injection',
    subtopic: 'Build variants',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Как образуются Android build variants?',
    options: [
      { id: 'a', text: 'Только из product flavors; build types на варианты не влияют' },
      { id: 'b', text: 'Как произведение build types и product flavors, поэтому число вариантов растёт мультипликативно' },
      { id: 'c', text: 'Только из ABI устройства при установке' },
      { id: 'd', text: 'Как сумма Gradle-модулей и unit-тестов' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Build type отвечает за способ сборки, flavor — за продуктовую разновидность; комбинация образует variant.',
      mechanism: 'debug/release задают минификацию, debug-флаги и подпись, а free/paid или dev/prod — окружение и набор возможностей. Каждая комбинация создаёт отдельные задачи и потенциальную матрицу CI.',
      trap: 'Добавление одной dimension может умножить, а не просто прибавить объём сборки и тестирования.',
      example: 'freeDebug и paidRelease — два варианта из произведения осей.',
    },
    source: { file: '13-di-build-deep.md', section: '9. Варианты сборки и поставка' },
    tags: ['android', 'build-types', 'product-flavors', 'variants', 'CI'],
  },
  {
    id: 'dependency-injection-035',
    topicId: 'dependency-injection',
    subtopic: 'App Bundle',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Как App Bundle меняет стратегию проверки релиза?',
    options: [
      { id: 'a', text: 'Достаточно протестировать локальный universal APK: Play загрузит его без изменений' },
      { id: 'b', text: 'Нужно проверять APK, которые Play/bundletool генерирует под устройства, потому что финальный APK формирует Play' },
      { id: 'c', text: 'AAB исключает необходимость тестировать разные ABI и языки' },
      { id: 'd', text: 'AAB отключает Play App Signing' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Разработчик публикует AAB, а устройство получает оптимизированный APK, собранный инфраструктурой Play.',
      mechanism: 'Play выбирает density, ABI и language splits, затем подписывает итоговый артефакт ключом приложения. Поэтому локальный APK не является точным представителем поставки.',
      trap: 'Меньший размер загрузки не означает меньшую тестовую матрицу: split-конфигурации добавляют риски упаковки.',
      verification: 'Используйте bundletool и internal track для проверки реально доставляемых наборов APK.',
    },
    source: { file: '13-di-build-deep.md', section: '9. Варианты сборки и поставка' },
    tags: ['android', 'App-Bundle', 'bundletool', 'Play-App-Signing', 'release'],
    version: { asOf: 'Google Play requirements, 2026-06', reviewAfter: '2027-01' },
  },
  {
    id: 'dependency-injection-036',
    topicId: 'dependency-injection',
    subtopic: 'R8',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Какие четыре преобразования выполняет R8 в Android toolchain?',
    options: [
      { id: 'a', text: 'Shrinking, optimization, obfuscation и desugaring' },
      { id: 'b', text: 'Компиляция ресурсов, подпись, публикация и staged rollout' },
      { id: 'c', text: 'DI codegen, KSP, KAPT и lint' },
      { id: 'd', text: 'Только переименование классов и создание mapping.txt' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'R8 удаляет недостижимое, оптимизирует, переименовывает и преобразует новые языковые конструкции.',
      mechanism: 'Один движок выполняет shrinking, optimization, obfuscation и desugaring, учитывая статическую достижимость и keep-правила.',
      trap: 'R8 совместим с форматом правил ProGuard, но не является самим ProGuard и не ограничивается обфускацией.',
      example: 'Минификацию обычно включают для release, иначе debug-итерация неоправданно замедляется.',
    },
    source: { file: '13-di-build-deep.md', section: '10.1. Что делает' },
    tags: ['android', 'R8', 'shrinking', 'optimization', 'obfuscation', 'desugaring'],
  },
  {
    id: 'dependency-injection-037',
    topicId: 'dependency-injection',
    subtopic: 'R8 keep rules',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'После подключения современной библиотеки команда хочет добавить `-keep class androidx.** { *; }` «на всякий случай». Как оценить решение?',
    options: [
      { id: 'a', text: 'Правильно: широкие keep-правила всегда улучшают совместимость без цены' },
      { id: 'b', text: 'Нежелательно: consumer rules часто уже поставляются библиотекой, а широкий keep блокирует shrinking и optimization' },
      { id: 'c', text: 'Обязательно только для debug, где R8 всегда включён' },
      { id: 'd', text: 'Правило влияет лишь на имена в mapping.txt, но не на оптимизацию' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Keep-правила должны быть минимальными и подтверждёнными недоступным статическому анализу использованием.',
      mechanism: 'R8 не видит рефлексию, JNI, создание по имени и некоторые формы сериализации — для них нужны точечные правила. Consumer rules библиотеки добавляются из артефакта автоматически.',
      trap: 'Широкий -keep маскирует проблему ценой размера и производительности, запрещая оптимизацию больших пространств имён.',
      verification: 'Начните без ручного правила, воспроизведите release-сбой и сузьте keep до реально используемых членов.',
    },
    source: { file: '13-di-build-deep.md', section: '10.2. Keep-правила и главная современная ошибка' },
    tags: ['android', 'R8', 'keep-rules', 'consumer-rules', 'reflection'],
  },
  {
    id: 'dependency-injection-038',
    topicId: 'dependency-injection',
    subtopic: 'R8 artifacts and startup',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой релизный артефакт нужно сохранять и загружать в crash reporting для читаемых обфусцированных стектрейсов?',
    options: [
      { id: 'a', text: 'Только build.gradle.kts' },
      { id: 'b', text: 'mapping.txt именно от этой сборки' },
      { id: 'c', text: 'Список KSP-процессоров' },
      { id: 'd', text: 'Universal debug APK' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'mapping.txt связывает обфусцированные имена с исходными и уникален для конкретной сборки.',
      mechanism: 'Crash reporter применяет mapping к стектрейсу, а retrace позволяет сделать это вручную. Другая версия mapping не восстановит исходные символы корректно.',
      trap: 'Потерянный mapping невозможно пересоздать из APK с гарантией идентичности; артефакт должен быть частью release pipeline.',
      example: 'R8 также связан со стартом: Startup Profiles управляют DEX-layout только при включённой минификации.',
    },
    source: { file: '13-di-build-deep.md', section: '10.3. `mapping.txt`' },
    tags: ['android', 'R8', 'mapping', 'retrace', 'crash-reporting', 'startup-profile'],
  },
  {
    id: 'dependency-injection-039',
    topicId: 'dependency-injection',
    subtopic: 'CI pipeline',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Как рационально упорядочить проверки PR-пайплайна?',
    options: [
      { id: 'a', text: 'Сначала полный набор instrumented tests, затем компиляция' },
      { id: 'b', text: 'Компиляция и static analysis → unit → JVM screenshot → сокращённые instrumented tests' },
      { id: 'c', text: 'Все стадии запускать последовательно в случайном порядке' },
      { id: 'd', text: 'На PR запускать только release upload, тесты оставить разработчикам' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Дешёвые и информативные проверки должны быстро отсекать дефект до дорогих стадий.',
      mechanism: 'Компиляция, lint и detekt дают раннюю обратную связь; unit и JVM screenshot tests дешевле device tests. Полный долгий instrumented-набор можно вынести в nightly, сохранив критичный smoke-набор на PR.',
      trap: 'Полный набор на каждый push может увеличить latency настолько, что команда начнёт обходить процесс или укрупнять PR.',
      verification: 'Отслеживайте p50/p95 pipeline duration и время до первого полезного failure.',
    },
    source: { file: '13-di-build-deep.md', section: '11. CI/CD' },
    tags: ['CI', 'pipeline', 'testing', 'static-analysis', 'feedback'],
  },
  {
    id: 'dependency-injection-040',
    topicId: 'dependency-injection',
    subtopic: 'Release engineering',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какая практика лучше всего снижает риск распространения дефектного мобильного релиза?',
    options: [
      { id: 'a', text: 'Мгновенно раскатывать 100% пользователей и ждать отзывов' },
      { id: 'b', text: 'Staged rollout с мониторингом crash/ANR и заранее проверенным откатом' },
      { id: 'c', text: 'Игнорировать flaky tests и автоматически перезапускать до успеха' },
      { id: 'd', text: 'Не связывать версию приложения с commit, чтобы упростить changelog' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Постепенная раскатка ограничивает blast radius и даёт время остановить релиз по объективным сигналам.',
      mechanism: 'Доля пользователей увеличивается этапами при нормальных crash/ANR и бизнес-метриках. Откат или halt должен быть отрепетирован, а версия — однозначно связана с исходным commit и артефактами.',
      trap: 'Автоперезапуск flaky test скрывает потерю доверия к gate; flake нужно считать блокирующим дефектом тестовой системы.',
      example: 'Регулярные release trains уменьшают давление добавить непроверенную фичу в последний момент.',
    },
    source: { file: '13-di-build-deep.md', section: '11. CI/CD' },
    tags: ['CI/CD', 'staged-rollout', 'ANR', 'crash', 'rollback', 'flaky-tests'],
  },
]
