import type { Question } from '../domain/models'

const sourceFile = '09-jvm-memory-deep.md'
const currentVersion = { asOf: '2026-08-17', reviewAfter: '2027-02-17' }

type QuestionInput = Omit<Question, 'topicId' | 'options' | 'source'> & {
  options: [string, string, string, string]
  section: string
}

const question = ({ options, section, ...input }: QuestionInput): Question => ({
  ...input,
  topicId: 'jvm-memory',
  options: options.map((text, index) => ({ id: String.fromCharCode(97 + index), text })),
  source: { file: sourceFile, section },
})

export const jvmMemoryQuestions: Question[] = [
  question({
    id: 'jvm-memory-001',
    subtopic: 'ART vs HotSpot',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Какое утверждение точнее всего описывает путь Kotlin-кода в Android release-сборке?',
    options: [
      'Kotlin компилируется в JVM bytecode, затем R8 выполняет shrink/optimize/obfuscate, desugaring и dexing',
      'D8 всегда создаёт DEX, после чего R8 оптимизирует уже готовый DEX',
      'ART непосредственно исполняет JVM class-файлы без преобразования',
      'dex2oat запускается Gradle на машине разработчика до упаковки APK',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'В release-пайплайне R8 заменяет D8, а не запускается после него.',
      mechanism: 'Kotlin выдаёт JVM bytecode; R8 одним проходом обрабатывает class-файлы и создаёт DEX. На устройстве ART может скомпилировать выбранный код через dex2oat.',
      trap: 'Популярная, но неверная схема — «D8, затем R8». D8 обычно используется там, где shrink не нужен, например в debug.',
    },
    section: '1.1. ART — это не HotSpot',
    tags: ['art', 'dex', 'r8', 'd8'],
  }),
  question({
    id: 'jvm-memory-002',
    subtopic: 'ART vs HotSpot',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему описание Android-приложения как обычного процесса HotSpot JVM технически неверно?',
    options: [
      'ART исполняет DEX, использует системные heap-лимиты и не предлагает приложению выбор G1/ZGC',
      'ART не использует сборку мусора и освобождает только память, выделенную вручную',
      'ART всегда компилирует весь код AOT и никогда не интерпретирует его',
      'ART запускает отдельную HotSpot JVM для каждого Android-компонента',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Android-приложение работает в ART с DEX и платформенными политиками памяти.',
      mechanism: 'Вместо привычного `-Xmx` лимит определяет устройство; выбрать G1 или ZGC нельзя. Классы и код mmap-ятся, а процесс форкается из Zygote и разделяет неизменённые страницы через copy-on-write.',
      trap: 'Термин «JVM» допустим как упрощение языка, но перенос настроек и устройства HotSpot на ART приводит к неверным выводам.',
    },
    section: '1.1. ART — это не HotSpot',
    tags: ['art', 'hotspot', 'zygote', 'heap-limit'],
  }),
  question({
    id: 'jvm-memory-003',
    subtopic: 'Memory areas',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'Java heap стабилен, но `dumpsys meminfo` показывает устойчивый рост памяти процесса. Куда смотреть прежде всего?',
    options: [
      'В native heap и Graphics, потому что GC Java heap их напрямую не контролирует',
      'Только в стеки Java-методов, потому что весь рост обязан находиться там',
      'В PermGen, потому что Android хранит там Bitmap',
      'Только в число загруженных class-файлов HotSpot',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Рост процесса не обязан отражаться на графике Java heap.',
      mechanism: 'В процессе отдельно учитываются Java heap, native heap, стеки, mmap-код, Graphics и shared buffers. NDK, Skia, пиксели современных Bitmap и GPU-ресурсы могут расти при ровном Java heap.',
      verification: 'Сначала сравните строки Java Heap, Native Heap, Code и Graphics в `adb shell dumpsys meminfo <package>`.',
    },
    section: '1.2. Из чего состоит память процесса',
    tags: ['memory-areas', 'native', 'graphics', 'dumpsys'],
  }),
  question({
    id: 'jvm-memory-004',
    subtopic: 'PSS/RSS/USS',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какая пара «метрика — смысл» указана верно?',
    options: [
      'PSS — пропорциональная доля shared-страниц; USS — приватные страницы процесса',
      'RSS — только приватные страницы; USS — shared-страницы целиком',
      'PSS — виртуальное адресное пространство; RSS — лимит Java heap',
      'USS — сумма Java heap и стека без native heap',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'PSS справедливо делит общую память, USS показывает уникальную память процесса.',
      mechanism: 'RSS считает все резидентные страницы целиком, включая shared. PSS делит стоимость shared-страницы между использующими её процессами. USS включает только private pages — примерно столько освободится при убийстве процесса.',
      trap: 'Нельзя сравнивать числа из разных инструментов, не выяснив, один ли показатель они выводят.',
    },
    section: '1.3. PSS, RSS, USS',
    tags: ['pss', 'rss', 'uss', 'metrics'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-005',
    subtopic: 'Heap limits',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Команда предлагает включить `android:largeHeap="true"` как исправление утечки. Какова корректная оценка?',
    options: [
      'Это лишь увеличит доступный heap, может удлинить GC и повысить риск выбора процесса LMK, не устранив утечку',
      'Это заставит GC игнорировать все strong references и собирать утёкшие Activity',
      'Это перенесёт все Java-объекты в native heap и исключит OOM',
      'Это включит ZGC и гарантирует паузы менее миллисекунды',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`largeHeap` не меняет достижимость объектов и не лечит утечки.',
      mechanism: 'Флаг поднимает device-specific лимит до `largeMemoryClass`. Больший процесс остаётся в той же LMK-группе, но может стать самым крупным кандидатом на убийство.',
      example: 'Флаг оправдан для редактора изображений или карт, если большой рабочий набор — реальное требование продукта.',
    },
    section: '1.4. Лимит heap и `largeHeap`',
    tags: ['largeHeap', 'oom', 'lmk', 'heap-limit'],
  }),
  question({
    id: 'jvm-memory-006',
    subtopic: 'GC roots',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'При каком условии ART может собрать объект?',
    options: [
      'Когда от любого GC root до объекта не существует пути сильной достижимости',
      'Когда на объект ссылается не более одного другого объекта',
      'Когда объект участвует в цикле ссылок',
      'Сразу после выхода конструктора объекта',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'GC основан на достижимости, а не на подсчёте ссылок.',
      mechanism: 'Корнями служат, среди прочего, стеки живых потоков, static-поля, JNI references, живые Thread и удерживаемые мониторы. Недостижимый цикл целиком будет собран.',
      trap: 'Фраза «объект собирается, когда на него нет ссылок» неточна: ссылки внутри недостижимого графа могут оставаться.',
    },
    section: '2.1. Reachability и GC roots',
    tags: ['gc', 'gc-roots', 'reachability'],
  }),
  question({
    id: 'jvm-memory-007',
    subtopic: 'GC roots',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Два объекта ссылаются друг на друга, но путь от GC roots к ним отсутствует. Что произойдёт?',
    options: [
      'Оба объекта могут быть собраны, потому что цикл сам по себе не является корнем',
      'Они останутся навсегда из-за взаимного счётчика ссылок',
      'Соберётся только объект, созданный позже',
      'Они будут перемещены в PermGen и больше не проверяться',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Циклические ссылки не мешают tracing GC.',
      mechanism: 'ART начинает обход от корней и маркирует достижимый граф. Если весь цикл не отмечен, его элементы считаются мусором независимо от внутренних связей.',
      trap: 'Проблемой цикл становится только тогда, когда один из его объектов всё ещё достижим от корня.',
    },
    section: '2.1. Reachability и GC roots',
    tags: ['gc', 'cycles', 'reachability'],
  }),
  question({
    id: 'jvm-memory-008',
    subtopic: 'GC evolution',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Какая последовательность эволюции сборщиков Android указана корректно?',
    options: [
      'Dalvik mark-sweep → ART CMS → Concurrent Copying → Generational CC → CMC',
      'ZGC → G1 → Shenandoah → CMS → Epsilon',
      'Dalvik reference counting → HotSpot Parallel GC → CMC',
      'CMS → Dalvik mark-sweep → G1 → Concurrent Copying',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'ART прошёл путь от некомпактирующей STW-сборки к конкурентной компакции.',
      mechanism: 'Dalvik страдал от пауз и фрагментации; CMS компактизировал ограниченно; CC с Android 8 копирует и компактирует конкурентно; Android 10 добавил поколения; CMC использует компактирование на месте и userfaultfd.',
      trap: 'Сборщики HotSpot G1/ZGC не являются выбираемыми сборщиками Android-приложения.',
    },
    section: '2.2. История сборщиков ART',
    tags: ['gc', 'cc', 'cmc', 'cms'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-009',
    subtopic: 'GC barriers',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Зачем Concurrent Copying использует Baker-style read barrier?',
    options: [
      'Чтобы при чтении ссылки мутатор видел согласованный объект во время конкурентного перемещения',
      'Чтобы запретить запись ссылок old → young',
      'Чтобы считать PSS без обхода shared-страниц',
      'Чтобы синхронно вызывать `finalize()` при каждом чтении поля',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Read barrier согласует чтения приложения с конкурентным копированием объектов.',
      mechanism: 'Небольшая проверка при чтении heap-reference направляет мутатор к корректной версии перемещаемого объекта. Это уменьшает паузы, но добавляет overhead обычному исполнению.',
      trap: 'Card marking — это write barrier с другой задачей; смешивать две барьерные механики нельзя.',
    },
    section: '2.3. Барьеры',
    tags: ['gc', 'read-barrier', 'concurrent-copying'],
  }),
  question({
    id: 'jvm-memory-010',
    subtopic: 'GC barriers',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Что делает write barrier с card marking в генерационном GC?',
    options: [
      'Отмечает изменённую область кучи, чтобы учитывать ссылки old → young без полного сканирования old generation',
      'Приостанавливает все потоки при каждой записи поля',
      'Переносит любой записанный объект сразу в old generation',
      'Освобождает объект при присваивании полю `null`',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Card table хранит remembered set в укрупнённом виде.',
      mechanism: 'При записи ссылки барьер помечает соответствующую карту dirty. Young GC пересматривает эти области и находит входящие ссылки из старой части, не обходя всю кучу.',
      trap: 'Присваивание `null` лишь меняет граф; немедленной сборки объекта write barrier не выполняет.',
    },
    section: '2.3. Барьеры',
    tags: ['gc', 'write-barrier', 'card-table', 'generations'],
  }),
  question({
    id: 'jvm-memory-011',
    subtopic: 'GC evolution',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'В чём ключевое отличие CMC от CC в механизме доступа к перемещаемой памяти?',
    options: [
      'CMC опирается на userfaultfd и не требует read barrier при обычном чтении ссылок',
      'CMC использует reference counting вместо tracing',
      'CMC никогда не компактизирует кучу',
      'CMC работает только при полном stop-the-world на весь GC',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'CMC переносит часть координации конкурентного перемещения на механизм page faults ядра.',
      mechanism: 'Защищённая ещё не обработанная страница вызывает fault, который обслуживает GC. Это убирает постоянную стоимость Baker read barrier, но требует поддержки userfaultfd ядром; иначе устройство остаётся на CC.',
      trap: 'Отсутствие read barrier не означает отсутствие синхронизации или компакции.',
    },
    section: '2.3. Барьеры',
    tags: ['cmc', 'cc', 'userfaultfd', 'read-barrier'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-012',
    subtopic: 'GC generations',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Почему кэш, удерживающий множество объектов «ещё несколько сборок», может быть особенно дорогим?',
    options: [
      'Объекты переживают young GC, продвигаются и увеличивают работу последующих сборок',
      'Любой объект кэша немедленно становится GC root',
      'Кэш отключает write barrier для всего процесса',
      'Young generation хранится только на диске и требует I/O',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Краткоживущие объекты дёшевы, а регулярно выживающие создают давление на поколения.',
      mechanism: 'Generational GC использует гипотезу, что большинство объектов быстро умирает. Пережившие сборки постепенно продвигаются; точные пороги — меняющаяся деталь реализации ART.',
      trap: 'Не стоит обещать фиксированное число поколений или конкретный возраст promotion для всех версий Android.',
    },
    section: '2.4. Поколения',
    tags: ['gc', 'generations', 'cache', 'promotion'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-013',
    subtopic: 'GC logs',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Что в строке GC-лога сильнее всего указывает на риск джанка?',
    options: [
      'Частые GC с причиной `Alloc` и заметное поле `paused`',
      'Большое значение `total` при микроскопическом `paused` само по себе',
      'Наличие любого количества освобождённых LOS objects',
      'Сам факт работы `HeapTaskDaemon` в фоне',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`Alloc` означает, что аллокация ждёт GC; джанк определяется остановкой мутаторных потоков.',
      mechanism: '`paused` — время остановки приложения, `total` — полная конкурентная работа. Частые Alloc GC показывают, что сборщик не успевает за allocation rate, и аллоцирующий поток может собирать сам.',
      verification: 'Сопоставьте причины GC, `paused`, частоту строк и трассу кадров, а не оценивайте одну строку изолированно.',
    },
    section: '2.5. Чтение GC-логов',
    tags: ['gc', 'logcat', 'jank', 'allocation'],
  }),
  question({
    id: 'jvm-memory-014',
    subtopic: 'GC logs',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Что означает `45MB/64MB` в типичной строке GC-лога ART?',
    options: [
      'Текущее использование кучи и её целевой footprint',
      'USS и RSS процесса',
      'Размер young и old generation, всегда в таком порядке',
      'Объём Java heap и Graphics memory',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Пара отражает heap usage относительно target footprint, а не системные метрики процесса.',
      mechanism: 'Рядом лог сообщает освобождённые AllocSpace/LOS objects, долю свободного, паузу и общую длительность. LOS содержит крупные объекты, а его порог зависит от реализации и версии.',
      trap: 'Target footprint — рабочая цель роста heap, не обязательно абсолютный growth limit приложения.',
    },
    section: '2.5. Чтение GC-логов',
    tags: ['gc', 'logs', 'footprint', 'los'],
  }),
  question({
    id: 'jvm-memory-015',
    subtopic: 'GC control',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Когда вызов `System.gc()` в Android-коде наиболее обоснован?',
    options: [
      'В диагностическом инструменте перед проверкой WeakReference/ReferenceQueue на удержание',
      'После каждого закрытия Activity для гарантированного удаления утечек',
      'Перед каждой аллокацией Bitmap для отключения LMK',
      'В каждом кадре Compose для уменьшения RSS',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`System.gc()` — подсказка рантайму, а не лечение достижимых объектов.',
      mechanism: 'Явная сборка может нарушить эвристики поколений, преждевременно продвинуть объекты и вызвать паузу. Инструменты вроде LeakCanary используют её как контролируемый этап проверки.',
      trap: 'Если до объекта остаётся путь от root, никакая сборка его не освободит.',
    },
    section: '2.6. `System.gc()`',
    tags: ['gc', 'system-gc', 'leakcanary'],
  }),
  question({
    id: 'jvm-memory-016',
    subtopic: 'Reference types',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Какое описание типов ссылок корректно?',
    options: [
      'WeakReference очищается при GC без strong/soft reachability, а PhantomReference.get() всегда возвращает null',
      'SoftReference гарантированно живёт до завершения процесса',
      'PhantomReference позволяет безопасно получить объект после его смерти',
      'Strong reference собирается при первом young GC, даже если достижима от root',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Сила ссылки определяет достижимость, а phantom не предоставляет доступ к referent.',
      mechanism: 'Strong удерживает объект; soft очищается по решению рантайма при давлении; weak — при отсутствии более сильной достижимости; phantom сигнализирует через очередь после признания объекта недостижимым.',
      trap: 'PhantomReference — не способ «воскресить» объект: `get()` всегда null.',
    },
    section: '3.1. Четыре силы',
    tags: ['references', 'weak', 'phantom', 'soft'],
  }),
  question({
    id: 'jvm-memory-017',
    subtopic: 'Reference types',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой кэш изображений предпочтительнее на Android?',
    options: [
      '`LruCache` с явным лимитом и `sizeOf` по байтам изображения',
      'Неограниченный `HashMap`, обёрнутый в `SoftReference` целиком',
      'Набор `PhantomReference`, из которых UI читает Bitmap через `get()`',
      '`WeakHashMap<Bitmap, Bitmap>`, где value ссылается на key',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Граница кэша должна быть явной продуктовой политикой.',
      mechanism: 'ART может агрессивно и непредсказуемо очистить SoftReference, не зная ценности элементов. LruCache даёт детерминированный бюджет и стратегию вытеснения.',
      trap: 'В WeakHashMap слаб только key; если value сильно ссылается на key, запись сама себя удерживает.',
    },
    section: '3.2. Почему `SoftReference` — плохой кэш на Android',
    tags: ['references', 'soft-reference', 'lrucache'],
  }),
  question({
    id: 'jvm-memory-018',
    subtopic: 'ReferenceQueue',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: '`queue.remove()` в эксперименте с PhantomReference никогда не возвращается. Какая вероятная ошибка?',
    options: [
      'Referent всё ещё удерживается strong reference, например локальной переменной ожидающего метода',
      'PhantomReference нужно читать через `get()` до ожидания очереди',
      'ReferenceQueue работает только для SoftReference',
      'Объект обязан быть static, иначе очередь его игнорирует',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'В очередь попадёт сама reference только после недостижимости referent.',
      mechanism: 'Даже локальная переменная может сохранить сильную достижимость до конца метода. Создание referent следует вынести так, чтобы перед блокирующим ожиданием сильной ссылки уже не было.',
      trap: '`PhantomReference.get()` всегда null и не помогает проверить состояние объекта.',
    },
    section: '3.4. `ReferenceQueue` и `PhantomReference`',
    tags: ['reference-queue', 'phantom-reference', 'gc'],
  }),
  question({
    id: 'jvm-memory-019',
    subtopic: 'Resource cleanup',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Какой подход надёжнее всего для освобождения внешнего ресурса приложением?',
    options: [
      'Явный `close()` с `AutoCloseable`/`use`, при необходимости с освобождением на стороне NDK',
      'Тяжёлый `finalize()`, который блокируется до завершения I/O',
      'Прямой вызов скрытого `libcore.util.NativeAllocationRegistry` из обычного приложения',
      'Ожидание случайного GC без явного контракта владения',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Детерминированное освобождение не зависит от момента запуска GC.',
      mechanism: '`finalize()` недетерминирован и может привести к TimeoutException от FinalizerWatchdogDaemon. Cleaner доступен лишь с API 33, а NativeAllocationRegistry — непубличный API фреймворка.',
      trap: 'Знать, как фреймворк учитывает native memory, не означает, что приложение может использовать внутренний API.',
    },
    section: '3.5. `finalize()`, `Cleaner`, `NativeAllocationRegistry`',
    tags: ['finalize', 'cleaner', 'close', 'native'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-020',
    subtopic: 'Code traps',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Что именно захватывает listener во втором вызове?',
    code: {
      language: 'kotlin',
      value: 'val vm = viewModel\nview.setOnClickListener { vm.onClick() }',
    },
    options: [
      'Локальную ссылку `vm`, но не внешний `this` только ради доступа к свойству',
      'Всегда всю Activity, потому что любая Kotlin-лямбда неявно захватывает `this`',
      'Ничего: любая лямбда компилируется в stateless singleton',
      'Только объект View, даже если он не упомянут в теле',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Захватывается путь доступа к значению.',
      mechanism: 'Если написать `{ viewModel.onClick() }` для свойства Activity, доступ идёт через `this.getViewModel()` и захватывает Activity. Предварительная локальная переменная позволяет захватить только ссылку на ViewModel.',
      trap: 'Лямбда без захвата может быть singleton; лямбда с захватом создаёт состояние и удерживает захваченные значения.',
    },
    section: '3.6. Кто кого держит',
    tags: ['lambda', 'capture', 'activity', 'code-trap'],
  }),
  question({
    id: 'jvm-memory-021',
    subtopic: 'Memory leaks',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Что точнее всего называется утечкой Activity?',
    options: [
      'Activity пережила свой lifecycle и осталась достижима от GC root',
      'Activity временно создала много короткоживущих объектов',
      'GC переместил Activity при компакции',
      'RSS процесса включает shared code pages',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Утечка — несоответствие фактической достижимости ожидаемому времени жизни.',
      mechanism: 'Удержанная Activity обычно тянет View-иерархию, ресурсы и изображения, поэтому одна ссылка может удерживать мегабайты.',
      trap: 'Высокий allocation rate и утечка — разные проблемы, хотя обе способны приводить к memory pressure.',
    },
    section: '4.1. Что такое утечка на Android',
    tags: ['leak', 'activity', 'lifecycle'],
  }),
  question({
    id: 'jvm-memory-022',
    subtopic: 'Memory leaks',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Почему следующий `postDelayed` нельзя надёжно отменить простым новым вызовом `removeCallbacks { updateUi() }`?',
    code: {
      language: 'kotlin',
      value: 'handler.postDelayed({ updateUi() }, 60_000)',
    },
    options: [
      '`removeCallbacks` требует тот же экземпляр Runnable, а исходный экземпляр не сохранён',
      '`removeCallbacks` принимает только Java-анонимные классы, но не Kotlin-лямбды',
      'Любой Runnable после постановки становится GC root навсегда',
      'Main Looper запрещает удалять отложенные сообщения',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Для отмены необходимо сохранить идентичный Runnable.',
      mechanism: 'Очередь Handler удерживает Runnable, а захватывающая лямбда — Activity. Сохраните Runnable и удалите его в onDestroy либо используйте lifecycleScope, который отменится автоматически.',
      trap: 'Новая синтаксически одинаковая лямбда — другой объект и не совпадёт с записью в очереди.',
    },
    section: '4.2. Таксономия типовых утечек',
    tags: ['handler', 'runnable', 'leak', 'code-trap'],
  }),
  question({
    id: 'jvm-memory-023',
    subtopic: 'Memory leaks',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой случай почти гарантированно удержит старую Activity после конфигурационного пересоздания?',
    options: [
      'ViewModel хранит Activity в поле конструктора',
      'Activity передаёт applicationContext в краткоживущую функцию',
      'Fragment обнуляет binding в `onDestroyView()`',
      'Lifecycle-bound coroutine отменяется при уничтожении владельца',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'ViewModel живёт дольше экземпляра Activity и не должна хранить UI-владельца.',
      mechanism: 'После recreation ViewModel сохраняется, а поле продолжает вести к старой Activity и её View tree. Обычно Context не нужен; если нужен application-level сервис, используют applicationContext.',
      trap: 'Подмена Activity на WeakReference маскирует неправильное владение, но не исправляет архитектуру задачи.',
    },
    section: '4.2. Таксономия типовых утечек',
    tags: ['viewmodel', 'activity', 'leak', 'lifecycle'],
  }),
  question({
    id: 'jvm-memory-024',
    subtopic: 'Memory leaks',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Почему значение `ThreadLocal` в executor pool требует особого внимания?',
    options: [
      'Поток пула может жить весь процесс и удерживать значение до явного `remove()`',
      'ThreadLocal автоматически превращает значение в PhantomReference',
      'GC всегда очищает ThreadLocal после каждой задачи',
      'ThreadLocal хранится только в стеке вызывающего Activity',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Время жизни ThreadLocal связано с потоком, а не с одной выполненной задачей.',
      mechanism: 'Worker thread переиспользуется, поэтому значение может пережить запрос, экран и все связанные объекты. Очистку следует делать в finally.',
      example: 'После установки контекста задачи используйте `try { ... } finally { local.remove() }`.',
    },
    section: '4.2. Таксономия типовых утечек',
    tags: ['threadlocal', 'thread-pool', 'leak'],
  }),
  question({
    id: 'jvm-memory-025',
    subtopic: 'LeakCanary',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Какая последовательность описывает LeakCanary корректно?',
    options: [
      'WeakReference + ReferenceQueue → GC-проверка retained → HPROF → Shark ищет кратчайший strong path до root',
      'PhantomReference.get() → анализ RSS → G1 heap dump → поиск самого длинного пути',
      'Подсчёт ссылок в байткоде → убийство процесса → сравнение PSS',
      'Перехват каждой аллокации NDK → поиск double free → очистка Java heap',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'LeakCanary сначала доказывает удержание, затем анализирует граф heap dump.',
      mechanism: 'ObjectWatcher регистрирует KeyedWeakReference в очереди. Если после задержки и GC reference не enqueued, объект retained; при достижении порога снимается HPROF, а Shark строит кратчайшую цепочку strong references до GC root.',
      trap: 'Попадание reference в очередь означает, что объект собран и утечки нет.',
    },
    section: '4.3. Как работает LeakCanary',
    tags: ['leakcanary', 'shark', 'hprof', 'reference-queue'],
  }),
  question({
    id: 'jvm-memory-026',
    subtopic: 'Heap dump',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какое определение retained size верно?',
    options: [
      'Объём памяти, который станет освобождаемым при удалении объекта, включая объекты, достижимые только через него',
      'Только байты полей самого объекта без ссылочных графов',
      'Размер всех объектов того же класса во всех процессах',
      'Разница между RSS и PSS в момент heap dump',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Retained size оценивает влияние объекта на удерживаемый подграф.',
      mechanism: 'Shallow size — размер самого экземпляра. Dominator — узел, через который проходят все пути к группе объектов; его retained size включает доминируемый граф.',
      verification: 'Сортируйте по retained size, проверяйте лишние экземпляры своих классов и затем путь до GC root.',
    },
    section: '4.4. Чтение heap dump руками',
    tags: ['heap-dump', 'retained-size', 'dominator'],
  }),
  question({
    id: 'jvm-memory-027',
    subtopic: 'Leak diagnostics',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Что LeakCanary принципиально не диагностирует напрямую?',
    options: [
      'Утечку malloc в сторонней `.so` в native heap',
      'Activity, удержанную static listener из Java heap',
      'Fragment View, удержанную забытым binding',
      'ViewModel, удерживающую старую Activity',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'LeakCanary анализирует managed heap graph, а не нативные malloc-аллокации.',
      mechanism: 'Для native growth нужны разбивка meminfo и профилирование heapprofd; LeakCanary также не докажет проблему растущего «легального» кэша только по факту достижимости.',
      trap: 'Первый шаг диагностики — определить область роста, иначе выбранный инструмент может не видеть проблему.',
    },
    section: '4.5. Чего LeakCanary не найдёт',
    tags: ['leakcanary', 'native', 'heapprofd'],
  }),
  question({
    id: 'jvm-memory-028',
    subtopic: 'Bitmap memory',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Где находятся пиксели обычного Bitmap на современных версиях Android?',
    options: [
      'С API 26 — в native heap, а их стоимость связывается с Java-объектом через механизм NativeAllocationRegistry',
      'Всегда в PermGen вместе с метаданными класса',
      'С API 26 — только в Java stack текущего потока',
      'Всегда только в GPU memory независимо от Bitmap.Config',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Начиная с Android 8 пиксельные данные обычного Bitmap вынесены в native heap.',
      mechanism: 'Фреймворк сообщает ART нативную стоимость объекта через внутренний NativeAllocationRegistry. До Android 8 пиксели находились в Java heap; HARDWARE bitmap использует графическую память.',
      trap: 'NativeAllocationRegistry — внутренний libcore API, не публичный инструмент приложения.',
    },
    section: '5.1. Bitmap',
    tags: ['bitmap', 'native-memory', 'api-26'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-029',
    subtopic: 'Bitmap memory',
    difficulty: 'basic',
    kind: 'scenario',
    prompt: 'Сколько примерно памяти требует несжатый Bitmap 4000×3000 в `ARGB_8888`?',
    options: ['48 МБ', '12 МБ', '24 МБ', '192 МБ'],
    correctOptionId: 'a',
    explanation: {
      summary: '`ARGB_8888` использует четыре байта на пиксель.',
      mechanism: '4000 × 3000 × 4 = 48 000 000 байт, то есть около 48 МБ в десятичном представлении. Размер JPEG-файла на диске к этому расчёту не относится.',
      example: 'Для маленькой ImageView декодируйте сразу под target size через Coil/Glide, ImageDecoder или sampling.',
    },
    section: '5.1. Bitmap',
    tags: ['bitmap', 'argb8888', 'allocation'],
  }),
  question({
    id: 'jvm-memory-030',
    subtopic: 'Bitmap memory',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Нужно показать фрагменты 100-мегапиксельного скана без хранения изображения целиком. Что выбрать?',
    options: [
      '`BitmapRegionDecoder` и декодирование только видимой области',
      '`Bitmap.Config.HARDWARE` и обязательный `getPixel()` для каждого пикселя',
      '`SoftReference` на полноразмерный Bitmap без лимита',
      '`System.gc()` после декодирования полного изображения',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Region decoding ограничивает рабочий набор нужными тайлами.',
      mechanism: 'Полное декодирование создаёт огромный пиксельный буфер. BitmapRegionDecoder позволяет читать участок; для обычного масштабирования современный ImageDecoder умеет задавать целевой размер.',
      trap: 'HARDWARE bitmap хорош для отображения, но его пиксели нельзя читать и в него нельзя рисовать Canvas.',
    },
    section: '5.1. Bitmap',
    tags: ['bitmap', 'region-decoder', 'image-decoder'],
  }),
  question({
    id: 'jvm-memory-031',
    subtopic: 'Native tools',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Какой инструмент даст стеки нативных аллокаций для расследования роста malloc?',
    options: [
      'Perfetto с `heapprofd`',
      'LeakCanary ObjectWatcher',
      'Kotlin compiler allocation checker',
      'Только `Debug.dumpHprofData()`',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`heapprofd` профилирует native allocation call stacks.',
      mechanism: '`dumpsys meminfo` сначала локализует рост по областям, а Perfetto/heapprofd показывает, кто и сколько аллоцировал. malloc_debug, GWP-ASan и MTE нацелены также на corruption, use-after-free и похожие ошибки.',
      trap: 'HPROF описывает managed heap и не заменяет профилировщик malloc.',
    },
    section: '5.2. Инструменты для native',
    tags: ['perfetto', 'heapprofd', 'native', 'tools'],
  }),
  question({
    id: 'jvm-memory-032',
    subtopic: 'OOM',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'В OOM-сообщении `until OOM` велик, но крупную аллокацию выполнить не удалось. Какова вероятная гипотеза?',
    options: [
      'Нет достаточно большого непрерывного блока, возможна фрагментация или проблема Large Object Space',
      'Growth limit уже обязательно равен нулю',
      'LMK выбрал другой процесс той же группы',
      'PSS всегда меньше запрошенного массива',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Общий доступный бюджет не гарантирует наличие непрерывного блока нужного размера.',
      mechanism: 'Сопоставляют requested allocation, free bytes, until OOM, target footprint и growth limit. Если target достиг growth limit — heap исчерпан; если запас велик, исследуют contiguous allocation и LOS.',
      trap: 'По одному `free bytes` нельзя узнать размер крупнейшего непрерывного блока.',
    },
    section: '6.1. `OutOfMemoryError`',
    tags: ['oom', 'fragmentation', 'los'],
  }),
  question({
    id: 'jvm-memory-033',
    subtopic: 'LMK',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Как lmkd в общем случае выбирает жертву при нехватке памяти?',
    options: [
      'Сначала по приоритетной группе `oom_score_adj`, затем среди сопоставимых процессов — более крупный',
      'Всегда убивает foreground-процесс с минимальным Java heap',
      'Выбирает процесс только по количеству Java-потоков',
      'Сначала вызывает OOM в каждом процессе, затем выбирает первый crash',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Важность процесса первична, размер влияет внутри подходящей группы.',
      mechanism: 'Foreground, visible, perceptible, service и cached/background имеют разные приоритеты. Большой heap не меняет важность, но делает процесс более привлекательной жертвой среди равных.',
      trap: 'Фоновое убийство — штатный process death; приложение обязано восстановить состояние.',
    },
    section: '6.2. Low memory killer и приоритеты',
    tags: ['lmk', 'lmkd', 'process-death'],
  }),
  question({
    id: 'jvm-memory-034',
    subtopic: 'Process death',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Как в проде отличить low-memory kill от ANR или native crash?',
    options: [
      'С API 30 запросить `ActivityManager.getHistoricalProcessExitReasons()` и изучить `ApplicationExitInfo.reason`',
      'Проверить только наличие Java `OutOfMemoryError` в текущем процессе',
      'Сравнить `memoryClass` и `largeMemoryClass` после перезапуска',
      'Всегда читать `/data/anr/traces.txt` без системных API',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'ApplicationExitInfo хранит системно классифицированную причину прошлого завершения.',
      mechanism: 'API различает REASON_LOW_MEMORY, ANR, native crash, signal, user requested и другие причины; также предоставляет pss/rss, описание и для ANR trace stream.',
      trap: 'LMK обычно не оставляет Java exception, поэтому отсутствие OOM stacktrace ничего не доказывает.',
    },
    section: '6.2. Low memory killer и приоритеты',
    tags: ['application-exit-info', 'lmk', 'anr', 'api-30'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-035',
    subtopic: 'Memory callbacks',
    difficulty: 'expert',
    kind: 'code',
    prompt: 'Что не так с этим кодом на актуальных версиях Android?',
    code: {
      language: 'kotlin',
      value: 'override fun onTrimMemory(level: Int) {\n    if (level == ComponentCallbacks2.TRIM_MEMORY_RUNNING_LOW) clearCaches()\n}',
    },
    options: [
      '`TRIM_MEMORY_RUNNING_LOW` не доставляется приложениям начиная с API 34, поэтому ветка мёртвая',
      '`onTrimMemory` разрешено переопределять только в Activity, но не в Application',
      'Уровни можно сравнивать только как строки',
      '`clearCaches()` обязательно должен вызываться при любом значении без условия',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Большая часть старых trim-level больше не приходит приложению.',
      mechanism: 'Актуальными остаются UI_HIDDEN и BACKGROUND; onLowMemory deprecated в API 35 и не вызывается с API 34. Реакцию строят вокруг реально доставляемых сигналов и lifecycle.',
      trap: 'Числа всех исторических констант не образуют общую шкалу срочности; `>=` безопасно применять лишь с пониманием оставшихся уровней и порядка ветвей.',
    },
    section: '6.3. `onTrimMemory`',
    tags: ['onTrimMemory', 'api-34', 'code-trap'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-036',
    subtopic: 'JIT/AOT',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Как ART исполняет приложение при гибридной модели?',
    options: [
      'Некомпилированное интерпретирует, горячее JIT-компилирует, а профильный код AOT-компилирует при install/background dexopt',
      'Всегда AOT-компилирует весь DEX при каждой установке независимо от профилей',
      'Использует только JIT и никогда не создаёт AOT-артефакты',
      'Передаёт DEX в HotSpot C2 при каждом старте',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Современный ART сочетает интерпретатор, JIT и profile-guided AOT.',
      mechanism: 'Без install profile фильтр может остаться `verify`; горячие методы попадают в JIT code cache и локальный профиль. Фоновый dexopt затем применяет `speed-profile`; `speed` означает AOT всего кода.',
      trap: 'AOT не является бинарным режимом «всё приложение заранее» — объём определяется compilation filter и профилем.',
    },
    section: '7.1. Гибридная модель',
    tags: ['art', 'jit', 'aot', 'dexopt'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-037',
    subtopic: 'Profiles',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Зачем нужен Baseline Profile, если Google Play формирует Cloud Profile?',
    options: [
      'Baseline доступен при установке первым пользователям новой версии, пока cloud-профиль ещё не агрегирован',
      'Baseline нужен только для debug и запрещён в release',
      'Cloud Profile работает исключительно офлайн и никогда не обновляется',
      'Baseline полностью отключает JIT и интерпретатор для всего приложения',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Baseline закрывает период cold start новой версии до появления статистики пользователей.',
      mechanism: 'Локальный профиль отражает конкретное устройство, cloud агрегируется Play со временем, baseline создаёт команда и поставляет в артефакте. Все они могут участвовать в profile-guided compilation.',
      trap: 'Профиль перечисляет важный код, но не означает AOT-компиляцию абсолютно всех методов.',
    },
    section: '7.2. Откуда берутся профили',
    tags: ['baseline-profile', 'cloud-profile', 'aot'],
  }),
  question({
    id: 'jvm-memory-038',
    subtopic: 'Dexopt verification',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'После установки статус приложения остаётся `verify`, а не `speed-profile`. Какой вывод наиболее обоснован?',
    options: [
      'Профиль не применился; нужно проверить dexopt state и причину установки на реальном устройстве',
      'Профиль применился идеально, потому что `verify` означает AOT всего кода',
      'JIT навсегда отключён для приложения',
      'R8 не создал DEX вообще',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`verify` указывает на отсутствие ожидаемой profile-guided AOT-компиляции.',
      mechanism: '`dumpsys package dexopt` показывает status/reason, а на Android 14+ полезен `pm art dump`. `install-dm` подтверждает профиль из установочного артефакта, `bg-dexopt` — позднюю фоновую компиляцию.',
      verification: 'Проверяйте полный вывод на устройстве: точные поля и команды менялись между версиями.',
    },
    section: '7.3. Проверка на устройстве',
    tags: ['dexopt', 'speed-profile', 'baseline-profile', 'tools'],
    version: currentVersion,
  }),
  question({
    id: 'jvm-memory-039',
    subtopic: 'Tools',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой процесс лучше всего доказывает устранение утечки managed heap?',
    options: [
      'Снять baseline heap dump, повторить сценарий N раз, снять второй и сравнить instance counts/retained paths',
      'Один раз посмотреть общий RSS после случайного запуска',
      'Включить largeHeap и считать отсутствие немедленного OOM доказательством',
      'Вызвать System.gc() и проверить только свободное место на диске',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Сравнимый повторяемый эксперимент отличает накопление от шума.',
      mechanism: 'Memory Profiler или HPROF показывает managed instances и retained graph; LeakCanary автоматизирует поиск путей. Для CI утечки можно превращать в падение instrumentation test.',
      verification: 'Зафиксируйте начальное состояние, число повторов и ожидаемое количество живых Activity/Fragment до и после исправления.',
    },
    section: '8. Инструменты',
    tags: ['heap-dump', 'memory-profiler', 'ci', 'methodology'],
  }),
  question({
    id: 'jvm-memory-040',
    subtopic: 'Code traps',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Какова главная проблема этого кода?',
    code: {
      language: 'kotlin',
      value: 'class Cache {\n    companion object {\n        private val map = HashMap<String, Bitmap>()\n    }\n}',
    },
    options: [
      'Статическая неограниченная коллекция живёт весь процесс и удерживает Bitmap до OOM',
      'HashMap хранит значения только через weak references и слишком рано их удалит',
      'Companion object автоматически очищается после каждого Activity.onStop()',
      'Bitmap нельзя хранить ни в одной коллекции даже с ограничением размера',
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Время жизни и ёмкость кэша не ограничены.',
      mechanism: 'Companion object достижим через загруженный класс, поэтому map и все значения остаются живыми. Нужен LruCache с байтовым бюджетом и декодирование под целевой размер.',
      trap: 'Формально это может быть «полезный» кэш, но неограниченный рост практически эквивалентен утечке и приводит к OOM.',
    },
    section: '9.1',
    tags: ['cache', 'bitmap', 'static', 'code-trap'],
  }),
]
