import type { Question } from '../domain/models'

const sourceFile = 'Kotlin_Senior_Android_Guide.markdown'

export const kotlinQuestions: Question[] = [
  {
    id: 'kotlin-001',
    topicId: 'kotlin',
    subtopic: 'Базовые типы',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Почему выражение `repository.find(id) ?: return` корректно типизируется в Kotlin?',
    options: [
      { id: 'a', text: '`return` имеет тип `Unit`, совместимый с любым nullable-типом' },
      { id: 'b', text: '`return` имеет тип `Nothing`, который является нижним типом' },
      { id: 'c', text: 'Elvis всегда преобразует правую ветку в тип левой' },
      { id: 'd', text: '`return` не участвует в проверке типов' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`return` не производит обычного значения и имеет тип `Nothing`, поэтому может быть правой веткой Elvis.',
      mechanism: '`Nothing` не имеет значений и является подтипом любого типа. Если левая часть равна `null`, управление покидает функцию; после выражения компилятор знает, что результат слева non-null.',
      trap: '`Unit` — настоящий тип с единственным значением, а не тип незавершающегося вычисления.',
    },
    source: { file: sourceFile, section: '2.5. Что делает Elvis с return или throw?' },
    tags: ['nothing', 'elvis', 'null-safety'],
  },
  {
    id: 'kotlin-002',
    topicId: 'kotlin',
    subtopic: 'Изменяемость',
    difficulty: 'basic',
    kind: 'code',
    prompt: 'Что произойдёт при выполнении кода?',
    code: { language: 'kotlin', value: 'val users = mutableListOf("Ann")\nusers += "Bob"\nprintln(users)' },
    options: [
      { id: 'a', text: 'Ошибка компиляции: `val` запрещает любое изменение объекта' },
      { id: 'b', text: 'Будет напечатано только `[Ann]`' },
      { id: 'c', text: 'Будет напечатано `[Ann, Bob]`' },
      { id: 'd', text: 'Код упадёт с `UnsupportedOperationException`' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: '`val` запрещает переназначение ссылки, но не делает объект неизменяемым.',
      mechanism: 'Переменная хранит тот же `MutableList`; операция `+=` вызывает изменяющую операцию списка. Для настоящей immutable-модели нужны неизменяемые данные и отсутствие доступных mutable-ссылок.',
      trap: 'Read-only ссылка и неизменяемый объект — разные гарантии.',
    },
    source: { file: sourceFile, section: '1.3. Чем val отличается от неизменяемого объекта?' },
    tags: ['val', 'mutability', 'collections'],
  },
  {
    id: 'kotlin-003',
    topicId: 'kotlin',
    subtopic: 'Константы и ABI',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Библиотека изменила публичный `const val API_VERSION = 1` на `2`, но приложение не перекомпилировали. Какое значение вероятнее всего использует уже собранный клиент?',
    options: [
      { id: 'a', text: '`2`, потому что значение всегда читается из поля библиотеки' },
      { id: 'b', text: '`1`, потому что compile-time константа могла быть встроена в bytecode клиента' },
      { id: 'c', text: '`null`, пока библиотека не пересоберёт клиента' },
      { id: 'd', text: 'Загрузка класса обязательно завершится `LinkageError`' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Публичный `const val` может быть встроен в call site, поэтому старый клиент продолжит видеть старое значение.',
      mechanism: 'Константа известна компилятору и копируется в bytecode потребителя. Замена значения в библиотеке не переписывает уже собранный клиент; требуется его перекомпиляция.',
      trap: 'Изменяемые настройки и feature flags не должны публиковаться как compile-time constants.',
      verification: 'Поведение можно подтвердить, декомпилировав bytecode клиента до и после его перекомпиляции.',
    },
    source: { file: sourceFile, section: '1.4. Чем const val отличается от val?' },
    tags: ['const', 'binary-compatibility', 'jvm'],
  },
  {
    id: 'kotlin-004',
    topicId: 'kotlin',
    subtopic: 'Null safety',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Почему компилятор обычно не разрешает smart cast свойства `session.user` после проверки `if (session.user != null)`?',
    options: [
      { id: 'a', text: 'Smart cast работает только для числовых типов' },
      { id: 'b', text: 'Свойство может измениться или иметь нестабильный getter между чтениями' },
      { id: 'c', text: 'Любое свойство другого объекта имеет platform type' },
      { id: 'd', text: 'Проверка `!= null` не поддерживает smart cast' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Smart cast возможен только для стабильного значения, неизменность которого между проверкой и использованием доказана.',
      mechanism: 'Изменяемое, `open`-свойство или custom getter могут вернуть другое значение при следующем чтении. Надёжное решение — один раз прочитать значение в локальный `val` и проверять этот snapshot.',
      example: 'Правильно: `val user = session.user; if (user != null) render(user)`.',
    },
    source: { file: sourceFile, section: '2.2. Что такое smart cast и когда он не работает?' },
    tags: ['smart-cast', 'null-safety', 'properties'],
  },
  {
    id: 'kotlin-005',
    topicId: 'kotlin',
    subtopic: 'Java interop',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Java-метод без nullability-аннотаций возвращает `String`. Как безопаснее спроектировать Kotlin-границу?',
    options: [
      { id: 'a', text: 'Сразу распространить значение как `String` по всем слоям' },
      { id: 'b', text: 'Всегда применять `!!`, чтобы ошибка возникла раньше' },
      { id: 'c', text: 'Нормализовать platform type в явно `String?` или проверенный `String` на границе' },
      { id: 'd', text: 'Привести значение к `Any`, чтобы отключить null safety' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Platform type переносит ответственность за nullability на вызывающий Kotlin-код, поэтому риск нужно локализовать на границе.',
      mechanism: 'Без распознанных аннотаций компилятор видит условный `String!` и разрешает как nullable, так и non-null использование. Явная проверка или честный nullable-тип не дают неопределённости проникнуть в доменный код.',
      trap: '`!!` лишь превращает неопределённость в runtime-исключение.',
    },
    source: { file: sourceFile, section: '2.3. Что такое platform type?' },
    tags: ['platform-types', 'null-safety', 'java-interop'],
  },
  {
    id: 'kotlin-006',
    topicId: 'kotlin',
    subtopic: 'Generics и nullability',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Что выражает ограничение `fun <T : Any> store(value: T)` по сравнению с обычным `<T>`?',
    options: [
      { id: 'a', text: '`T` обязан быть ровно типом `Any`' },
      { id: 'b', text: '`T` не может быть nullable, потому что верхняя граница изменена с `Any?` на `Any`' },
      { id: 'c', text: '`T` обязан быть JVM reference type и не может быть `Int`' },
      { id: 'd', text: 'Ограничение влияет только на Java-код, но не на Kotlin' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'По умолчанию generic-параметр ограничен `Any?`; граница `Any` запрещает nullable type arguments.',
      mechanism: 'Вызов с `String?` не удовлетворяет `T : Any`, тогда как обычный `<T>` допускает его. Это способ выразить требование настоящего non-null значения в generic API.',
      trap: 'Граница задаёт множество допустимых подтипов, а не требует точного типа `Any`.',
    },
    source: { file: sourceFile, section: '2.6. Что такое definitely non-nullable type T & Any?' },
    tags: ['generics', 'nullability', 'type-bounds'],
  },
  {
    id: 'kotlin-007',
    topicId: 'kotlin',
    subtopic: 'Инициализация классов',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Почему вызов `open`-метода из `init` базового класса опасен?',
    options: [
      { id: 'a', text: 'В Kotlin виртуальные вызовы запрещены во время создания объекта' },
      { id: 'b', text: 'Override наследника может выполниться до инициализации его полей и увидеть JVM default values' },
      { id: 'c', text: 'Такой вызов всегда создаёт второй экземпляр наследника' },
      { id: 'd', text: 'Метод автоматически выполняется в другом потоке' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Базовая часть объекта инициализируется раньше состояния наследника, но виртуальная диспетчеризация уже может вызвать override.',
      mechanism: 'Инициализация идёт от base к derived и внутри класса — в текстовом порядке. Override способен прочитать поле наследника до его initializer и получить `null`, `0` или другое default JVM-значение.',
      trap: 'Final-by-default снижает риск таких вызовов, но `open` нужно проектировать с учётом жизненного цикла объекта.',
    },
    source: { file: sourceFile, section: '3.2. Порядок инициализации класса' },
    tags: ['initialization', 'inheritance', 'virtual-dispatch'],
  },
  {
    id: 'kotlin-008',
    topicId: 'kotlin',
    subtopic: 'Data classes',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Какие свойства участвуют в автоматически сгенерированных `equals`, `hashCode`, `componentN` и `copy` у data class?',
    options: [
      { id: 'a', text: 'Все свойства, включая вычисляемые и унаследованные' },
      { id: 'b', text: 'Только свойства, объявленные в primary constructor' },
      { id: 'c', text: 'Только изменяемые свойства `var`' },
      { id: 'd', text: 'Только свойства с backing field' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Сгенерированная value-семантика data class основана на свойствах primary constructor.',
      mechanism: 'Свойства из тела класса не входят в автоматически созданные equality, destructuring и `copy`. Поэтому значимое для идентичности состояние следует помещать в primary constructor либо сравнивать явно.',
      trap: 'Наличие backing field само по себе не включает свойство в генерацию data class.',
    },
    source: { file: sourceFile, section: '3.4. Что генерирует data class?' },
    tags: ['data-class', 'equality', 'copy'],
  },
  {
    id: 'kotlin-009',
    topicId: 'kotlin',
    subtopic: 'Копирование',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Каков результат изменения `second.values`?',
    code: { language: 'kotlin', value: 'data class Box(val values: MutableList<Int>)\nval first = Box(mutableListOf(1))\nval second = first.copy()\nsecond.values += 2' },
    options: [
      { id: 'a', text: '`first.values` остаётся `[1]`, потому что `copy()` глубокий' },
      { id: 'b', text: '`first.values` становится `[1, 2]`, потому что список разделяется' },
      { id: 'c', text: 'Ошибка компиляции из-за `val values`' },
      { id: 'd', text: '`copy()` возвращает тот же объект `Box`' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`data class.copy()` создаёт новый внешний объект, но копирует ссылки на вложенные объекты поверхностно.',
      mechanism: '`first` и `second` — разные `Box`, однако оба содержат одну ссылку на `MutableList`. Изменение списка наблюдается через оба объекта и ломает независимость snapshots.',
      example: 'Для независимого списка нужно явно передать копию, например `first.copy(values = first.values.toMutableList())`.',
    },
    source: { file: sourceFile, section: '18.6. Что произойдёт с data class.copy()?' },
    tags: ['data-class', 'shallow-copy', 'mutability', 'code-trap'],
  },
  {
    id: 'kotlin-010',
    topicId: 'kotlin',
    subtopic: 'Закрытые иерархии',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Когда `sealed`-иерархия точнее моделирует состояние, чем `enum class`?',
    options: [
      { id: 'a', text: 'Когда каждый вариант должен иметь собственную форму данных и поведение' },
      { id: 'b', text: 'Только когда вариантов больше 32' },
      { id: 'c', text: 'Когда набор вариантов должен расширяться любым внешним модулем' },
      { id: 'd', text: 'Когда все варианты обязаны быть экземплярами одного класса с одинаковым состоянием' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`sealed` задаёт закрытый набор разных подтипов, каждый из которых может нести собственные данные.',
      mechanism: '`enum` фиксирует экземпляры одной формы, а sealed-модель позволяет, например, `Content(items)` и `Error(cause)`. `when` по закрытой иерархии может быть исчерпывающим без `else`.',
      trap: 'Sealed-иерархия специально ограничивает прямых наследников, а не открывает расширение всем модулям.',
    },
    source: { file: sourceFile, section: '3.5. Чем sealed class отличается от enum class?' },
    tags: ['sealed', 'enum', 'modeling'],
  },
  {
    id: 'kotlin-011',
    topicId: 'kotlin',
    subtopic: 'Value classes',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'В каком случае `@JvmInline value class UserId(val value: String)` наиболее вероятно будет boxed?',
    options: [
      { id: 'a', text: 'При любом локальном присваивании `val id = UserId("42")`' },
      { id: 'b', text: 'При использовании как nullable-значения или generic-аргумента' },
      { id: 'c', text: 'Только если underlying type является `String`' },
      { id: 'd', text: 'Value class никогда не boxing-ится' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Value class часто представляется underlying-значением, но nullable, generic и interface-контексты могут потребовать wrapper.',
      mechanism: 'JVM-сигнатура должна различать отсутствие значения, стирать generic-тип или представить объект через интерфейс, поэтому компилятор использует boxed-форму. Отсутствие аллокации не является безусловной гарантией value class.',
      verification: 'Для критичного API следует проверить bytecode и измерить release-сборку, а не судить только по исходнику.',
    },
    source: { file: sourceFile, section: '3.7. Что такое value class?' },
    tags: ['value-class', 'boxing', 'performance'],
  },
  {
    id: 'kotlin-012',
    topicId: 'kotlin',
    subtopic: 'Равенство',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Что напечатает код?',
    code: { language: 'kotlin', value: 'data class User(val name: String) {\n    var selected: Boolean = false\n}\nval a = User("Ann").apply { selected = false }\nval b = User("Ann").apply { selected = true }\nprintln(a == b)' },
    options: [
      { id: 'a', text: '`true`' },
      { id: 'b', text: '`false`' },
      { id: 'c', text: 'Ошибка компиляции: data class не может иметь свойства в теле' },
      { id: 'd', text: 'Результат зависит от JVM' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Будет `true`: `selected` находится вне primary constructor и не участвует в сгенерированном `equals`.',
      mechanism: 'Оба объекта имеют одинаковое единственное equality-свойство `name`. Различие их дополнительного mutable-состояния автоматически сгенерированный метод не рассматривает.',
      trap: 'Это может неожиданно влиять на UI diffing, множества и кеши.',
    },
    source: { file: sourceFile, section: '18.8. Что выведет equality?' },
    tags: ['equality', 'data-class', 'code-trap'],
  },
  {
    id: 'kotlin-013',
    topicId: 'kotlin',
    subtopic: 'Hash collections',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Что может произойти, если изменить поле ключа, участвующее в `equals/hashCode`, после помещения ключа в `HashMap`?',
    options: [
      { id: 'a', text: 'Map автоматически переместит ключ в новую bucket' },
      { id: 'b', text: 'Ключ может перестать находиться, потому что остался в bucket старого hash' },
      { id: 'c', text: 'Изменение будет запрещено JVM' },
      { id: 'd', text: 'Изменится только порядок итерации, но поиск останется корректным' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Изменяемый hash ключа нарушает внутреннюю адресацию hash-коллекции.',
      mechanism: 'При вставке bucket выбирается по прежнему `hashCode`; последующий поиск вычисляет уже новый hash и смотрит в другое место. Коллекция не наблюдает изменения полей и не выполняет автоматическое rehash.',
      trap: 'Равные объекты обязаны иметь одинаковый hash, но одного этого недостаточно: hash ключа должен оставаться стабильным во время хранения.',
    },
    source: { file: sourceFile, section: '4.2. Контракт equals и hashCode' },
    tags: ['equals', 'hashcode', 'hashmap', 'mutability'],
  },
  {
    id: 'kotlin-014',
    topicId: 'kotlin',
    subtopic: 'Destructuring',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему перестановка параметров primary constructor data class может тихо сломать destructuring-код?',
    options: [
      { id: 'a', text: 'Destructuring вызывает `componentN` по позиции, а не читает свойства по имени' },
      { id: 'b', text: 'Destructuring всегда использует Java reflection' },
      { id: 'c', text: 'Компилятор сортирует свойства по алфавиту' },
      { id: 'd', text: 'После перестановки data class теряет методы `componentN`' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Destructuring — синтаксический сахар над позиционными вызовами `component1`, `component2` и далее.',
      mechanism: 'Имена локальных переменных слева не связываются с именами свойств. Если типы совместимы, перестановка constructor properties может скомпилироваться, но изменить смысл присваиваний.',
      trap: 'Особенно опасны соседние свойства одного типа.',
    },
    source: { file: sourceFile, section: '4.3. Как работает destructuring?' },
    tags: ['destructuring', 'componentN', 'api-design'],
  },
  {
    id: 'kotlin-015',
    topicId: 'kotlin',
    subtopic: 'Лямбды и замыкания',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Process-wide singleton хранит callback, а лямбда callback обращается к `Activity.title`. Каков основной риск?',
    options: [
      { id: 'a', text: 'Лямбда перестаёт быть вызываемой после `onStop`' },
      { id: 'b', text: 'Singleton удерживает лямбду, а она — Activity, вызывая утечку' },
      { id: 'c', text: 'Компилятор копирует Activity при захвате' },
      { id: 'd', text: 'Захват автоматически становится weak reference' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Долгоживущая лямбда удерживает захваченный receiver сильной ссылкой.',
      mechanism: 'Callback хранится столько же, сколько singleton; объект лямбды содержит ссылку на Activity, поэтому уничтоженный экран остаётся достижимым для GC. Lifecycle UI и process lifetime нельзя связывать такой ссылкой.',
      verification: 'Цепочку удержания можно увидеть в heap dump; архитектурно лучше передавать данные через lifecycle-aware наблюдение.',
    },
    source: { file: sourceFile, section: '18.10. Есть ли утечка?' },
    tags: ['closure', 'memory-leak', 'android'],
  },
  {
    id: 'kotlin-016',
    topicId: 'kotlin',
    subtopic: 'Inline-функции',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какой компромисс наиболее точно описывает `inline`?',
    options: [
      { id: 'a', text: 'Всегда уменьшает DEX и гарантированно устраняет все аллокации' },
      { id: 'b', text: 'Может убрать overhead лямбды и вызова, но увеличить bytecode и бинарный контракт' },
      { id: 'c', text: 'Работает только для функций без functional-параметров' },
      { id: 'd', text: 'Переносит выполнение функции в отдельный поток' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Inlining обменивает потенциальное устранение вызовов и объектов лямбд на копирование тела в call sites.',
      mechanism: 'Рост bytecode может ухудшить размер DEX и instruction cache; публичное inline-тело также попадает в скомпилированных клиентов. Компилятор и R8 не обязаны устранить абсолютно все аллокации.',
      trap: '`inline` — инструмент с измеримой ценой, а не универсальная performance-аннотация.',
    },
    source: { file: sourceFile, section: '5.3. Что делает inline?' },
    tags: ['inline', 'lambdas', 'performance', 'binary-compatibility'],
  },
  {
    id: 'kotlin-017',
    topicId: 'kotlin',
    subtopic: 'Inline-функции',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Зачем параметр лямбды помечают `crossinline`?',
    options: [
      { id: 'a', text: 'Чтобы разрешить хранить лямбду в поле' },
      { id: 'b', text: 'Чтобы запретить non-local `return`, сохранив возможность встраивания' },
      { id: 'c', text: 'Чтобы сделать лямбду потокобезопасной' },
      { id: 'd', text: 'Чтобы тип параметра стал reified' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`crossinline` нужен, когда inline-лямбда вызывается в контексте, где выход из внешней функции невозможен.',
      mechanism: 'Например, функция помещает вызов лямбды внутрь другого callback или объекта. Компилятор запрещает простой non-local `return`, который нельзя корректно реализовать из такого места, но саму лямбду всё ещё может встроить.',
      trap: 'Для хранения или передачи лямбды как значения используется `noinline`.',
    },
    source: { file: sourceFile, section: '5.4. noinline и crossinline' },
    tags: ['crossinline', 'inline', 'non-local-return'],
  },
  {
    id: 'kotlin-018',
    topicId: 'kotlin',
    subtopic: 'Reified и erasure',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Что `reified T` в inline-функции всё ещё не позволяет надёжно проверить на JVM?',
    options: [
      { id: 'a', text: '`value is String` при `T = String`' },
      { id: 'b', text: 'Вложенный аргумент типа в проверке `value is List<String>`' },
      { id: 'c', text: '`T::class`' },
      { id: 'd', text: 'Safe cast `value as? T`' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`reified` подставляет внешний тип в call site, но не отменяет JVM erasure вложенных generic-аргументов.',
      mechanism: 'Runtime способен проверить, что объект является `List`, но обычно не знает, содержал ли исходный тип аргумент `String`. Поэтому проверка структуры контейнера не доказывает тип каждого его элемента.',
      trap: 'Reification решает часть erasure для самого `T`, а не материализует полное runtime-описание произвольного generic-графа.',
    },
    source: { file: sourceFile, section: '5.6. reified type parameter' },
    tags: ['reified', 'type-erasure', 'generics'],
  },
  {
    id: 'kotlin-019',
    topicId: 'kotlin',
    subtopic: 'Extensions',
    difficulty: 'senior',
    kind: 'code',
    prompt: 'Что напечатает код?',
    code: { language: 'kotlin', value: 'open class Parent\nclass Child : Parent()\nfun Parent.label() = "parent"\nfun Child.label() = "child"\nval x: Parent = Child()\nprintln(x.label())' },
    options: [
      { id: 'a', text: '`child`, из-за virtual dispatch' },
      { id: 'b', text: '`parent`, потому что extension разрешается по compile-time типу receiver' },
      { id: 'c', text: 'Ошибка: нельзя перегружать extension по receiver' },
      { id: 'd', text: 'Результат зависит от фактического JVM-класса' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Extensions разрешаются статически, поэтому выбирается `Parent.label()`.',
      mechanism: 'Extension не добавляет виртуальный member в класс. Выбор функции выполняется компилятором по объявленному типу `x`, хотя runtime-объект является `Child`.',
      trap: 'Если у типа есть member с подходящей сигнатурой, member имеет приоритет над extension.',
    },
    source: { file: sourceFile, section: '18.1. Что выведет код с extension?' },
    tags: ['extensions', 'static-dispatch', 'code-trap'],
  },
  {
    id: 'kotlin-020',
    topicId: 'kotlin',
    subtopic: 'DSL',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какую проблему решает `@DslMarker` в DSL с несколькими вложенными receiver?',
    options: [
      { id: 'a', text: 'Автоматически валидирует все бизнес-инварианты builder' },
      { id: 'b', text: 'Ограничивает неявный доступ к внешнему receiver того же DSL' },
      { id: 'c', text: 'Делает DSL доступным из Java без адаптеров' },
      { id: 'd', text: 'Кеширует созданные builder-объекты' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`@DslMarker` защищает compile-time область неявных receiver от случайного обращения не к тому builder.',
      mechanism: 'Когда вложенные receiver помечены одним marker, внешний receiver перестаёт быть неявно доступным в глубоком блоке. Это уменьшает неоднозначность, но явный квалифицированный доступ и некорректные данные всё ещё нужно контролировать отдельно.',
      trap: 'Marker управляет scope, а не заменяет runtime-валидацию обязательных полей.',
    },
    source: { file: sourceFile, section: '15.1. Из чего строится Kotlin DSL?' },
    tags: ['dsl', 'dsl-marker', 'receiver'],
  },
  {
    id: 'kotlin-021',
    topicId: 'kotlin',
    subtopic: 'Scope functions',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Какая scope function предоставляет receiver как `this` и возвращает сам receiver?',
    options: [
      { id: 'a', text: '`let`' },
      { id: 'b', text: '`run`' },
      { id: 'c', text: '`apply`' },
      { id: 'd', text: '`with`' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: '`apply` использует `this` внутри блока и возвращает исходный receiver.',
      mechanism: 'Эта комбинация удобна для настройки объекта с последующим продолжением цепочки. `run` и `with` возвращают результат лямбды, а `let` использует `it`.',
      trap: '`apply` не делает последовательность изменений атомарной или потокобезопасной.',
    },
    source: { file: sourceFile, section: '6.1. Разница между let, run, with, apply, also' },
    tags: ['scope-functions', 'apply', 'receiver'],
  },
  {
    id: 'kotlin-022',
    topicId: 'kotlin',
    subtopic: 'Scope functions',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Какой семантический недостаток есть у `receiver?.run { nullableResult() }`, если два вида отсутствия имеют разный бизнес-смысл?',
    options: [
      { id: 'a', text: 'Блок выполняется дважды при non-null receiver' },
      { id: 'b', text: 'Результат не различает отсутствующий receiver и `null`, возвращённый блоком' },
      { id: 'c', text: '`run` превращает nullable result в исключение' },
      { id: 'd', text: 'Safe call всегда возвращает `Unit?`' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Оба пути схлопываются в одно значение `null`, хотя могут означать разные состояния домена.',
      mechanism: 'Safe call возвращает `null`, если receiver отсутствует; выполненный блок также может легитимно вернуть `null`. Если caller должен отличать эти случаи, нужна явная ветка или отдельный result/sealed type.',
      trap: 'Краткая nullable-chain может потерять информацию, а не только улучшить читаемость.',
    },
    source: { file: sourceFile, section: '6. Scope functions' },
    tags: ['scope-functions', 'nullability', 'domain-modeling'],
  },
  {
    id: 'kotlin-023',
    topicId: 'kotlin',
    subtopic: 'Variance',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Почему `MutableList<Dog>` нельзя использовать как `MutableList<Animal>`?',
    options: [
      { id: 'a', text: 'Потому что generic-типы JVM всегда ковариантны' },
      { id: 'b', text: 'Иначе через ссылку `MutableList<Animal>` можно было бы добавить `Cat` в список собак' },
      { id: 'c', text: 'Потому что `Dog` не является подтипом `Animal` внутри коллекций' },
      { id: 'd', text: 'Только потому, что `MutableList` не поддерживает чтение' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Mutable-контейнер и производит, и потребляет `T`, поэтому безопасно оставить его инвариантным.',
      mechanism: 'Ковариантный взгляд разрешил бы запись любого `Animal` в фактический список `Dog`, нарушив тип его элементов. Read-only `List<out E>` может быть ковариантным, потому что не предоставляет добавление.',
      trap: 'Variance описывает безопасные операции, а не отменяет отношение подтипов `Dog : Animal`.',
    },
    source: { file: sourceFile, section: '7.1. Почему MutableList<Dog> не является MutableList<Animal>?' },
    tags: ['generics', 'variance', 'mutability'],
  },
  {
    id: 'kotlin-024',
    topicId: 'kotlin',
    subtopic: 'Star projection',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Что безопасно делать со значением типа `MutableList<*>`?',
    options: [
      { id: 'a', text: 'Читать элементы как `Any?`, но не добавлять произвольное non-null значение' },
      { id: 'b', text: 'Добавлять любой `Any?`, потому что `*` эквивалентно `Any?`' },
      { id: 'c', text: 'Читать элементы только как `Nothing`' },
      { id: 'd', text: 'Изменять runtime-тип underlying списка на `MutableList<Any?>`' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Star projection означает неизвестный аргумент типа, а не `Any?`.',
      mechanism: 'Любой элемент неизвестного списка можно безопасно рассматривать как `Any?`, но запись конкретного значения небезопасна: фактическим типом может быть `MutableList<String>`, `MutableList<Int>` и т. п. Проекция ограничивает compile-time операции.',
      trap: 'Underlying объект не становится read-only и не меняет свой runtime-тип.',
    },
    source: { file: sourceFile, section: '7.4. Что такое star projection Foo<*>?' },
    tags: ['star-projection', 'generics', 'type-safety'],
  },
  {
    id: 'kotlin-025',
    topicId: 'kotlin',
    subtopic: 'Type erasure',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Почему на JVM нельзя объявить две функции, отличающиеся только параметрами `List<String>` и `List<Int>`?',
    options: [
      { id: 'a', text: 'Kotlin запрещает любую перегрузку generic-функций' },
      { id: 'b', text: 'После erasure обе имеют одинаковую JVM signature с параметром `List`' },
      { id: 'c', text: '`String` и `Int` имеют одинаковый Kotlin type id' },
      { id: 'd', text: 'Потому что `List` объявлен ковариантным' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'JVM method descriptor обычно не содержит generic-аргументы, поэтому сигнатуры конфликтуют.',
      mechanism: 'Обе декларации компилируются к методу с одним параметром `java.util.List`; runtime не может выбрать overload по `String` или `Int`. Нужно изменить API либо применить подходящий `@JvmName` там, где это допустимо.',
      trap: 'Причина — erasure JVM signature, а не variance коллекции.',
    },
    source: { file: sourceFile, section: '11.7. Почему overload по List<String> и List<Int> невозможен?' },
    tags: ['type-erasure', 'jvm-signature', 'overloading'],
  },
  {
    id: 'kotlin-026',
    topicId: 'kotlin',
    subtopic: 'Коллекции',
    difficulty: 'basic',
    kind: 'code',
    prompt: 'Что напечатает код?',
    code: { language: 'kotlin', value: 'val mutable = mutableListOf(1)\nval readOnly: List<Int> = mutable\nmutable += 2\nprintln(readOnly)' },
    options: [
      { id: 'a', text: '`[1]`, потому что `List` является immutable snapshot' },
      { id: 'b', text: '`[1, 2]`, потому что обе ссылки указывают на один mutable-объект' },
      { id: 'c', text: 'Ошибка присваивания `MutableList` в `List`' },
      { id: 'd', text: 'Исключение при изменении `mutable`' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Kotlin `List` — read-only интерфейс, а не гарантия immutable underlying объекта.',
      mechanism: 'Ссылка `readOnly` не предоставляет mutating API, но исходная mutable-ссылка всё ещё изменяет тот же список. Для независимого snapshot нужен defensive copy или persistent immutable collection.',
      trap: 'Тип view ограничивает операции конкретного владельца ссылки, но не контролирует aliasing.',
    },
    source: { file: sourceFile, section: '8.1. Read-only коллекция — это immutable коллекция?' },
    tags: ['collections', 'read-only', 'immutability', 'code-trap'],
  },
  {
    id: 'kotlin-027',
    topicId: 'kotlin',
    subtopic: 'Sequence',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Когда переход с eager-цепочки коллекций на `Sequence` наиболее обоснован?',
    options: [
      { id: 'a', text: 'Всегда, даже для двух элементов и одной операции' },
      { id: 'b', text: 'Для большой/длинной цепочки с early termination после измерения критичного пути' },
      { id: 'c', text: 'Когда внутри pipeline нужны suspend-вызовы' },
      { id: 'd', text: 'Когда требуется гарантированная параллельная обработка' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`Sequence` может убрать промежуточные коллекции и остановиться раньше, но имеет собственный iterator/call overhead.',
      mechanism: 'Он обрабатывает элементы лениво через pipeline; это полезно на больших входах и при `first`/`take`. На маленьких коллекциях eager-код может быть быстрее, поэтому решение подтверждают benchmark или profile.',
      trap: '`Sequence` синхронен и не предназначен для suspend-операций.',
    },
    source: { file: sourceFile, section: '8.3. Iterable против Sequence' },
    tags: ['sequence', 'collections', 'performance'],
  },
  {
    id: 'kotlin-028',
    topicId: 'kotlin',
    subtopic: 'Массивы',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Какое утверждение об `Array<Int>` и `IntArray` на JVM верно?',
    options: [
      { id: 'a', text: 'Оба всегда представлены `int[]`' },
      { id: 'b', text: '`Array<Int>` обычно содержит boxed `Integer`, а `IntArray` представлен `int[]`' },
      { id: 'c', text: '`IntArray` хранит nullable `Int?` без boxing' },
      { id: 'd', text: '`Array<Int>` использует меньше памяти в hot path' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Специализированный `IntArray` избегает boxing элементов и соответствует примитивному JVM-массиву.',
      mechanism: 'Generic `Array<Int>` требует reference-представления элементов, тогда как `IntArray` хранит примитивы непосредственно. На больших массивах это влияет на память и GC.',
      trap: 'Содержимое массивов сравнивают через `contentEquals`, а обычное `==` не даёт ожидаемой value-семантики элементов.',
    },
    source: { file: sourceFile, section: '8.6. Массивы и примитивные массивы' },
    tags: ['arrays', 'boxing', 'performance'],
  },
  {
    id: 'kotlin-029',
    topicId: 'kotlin',
    subtopic: 'Делегирование класса',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Обёртка реализует `Repository by delegate` и override-ит `save()` для логирования. Что произойдёт, если метод `delegate.sync()` внутри самого delegate вызывает свой `save()`?',
    options: [
      { id: 'a', text: 'Вызов обязательно пройдёт через override `save()` обёртки' },
      { id: 'b', text: 'Вызов обычно останется внутри delegate и обойдёт override обёртки' },
      { id: 'c', text: 'Компилятор запретит внутренние вызовы между методами delegate' },
      { id: 'd', text: 'Будут вызваны оба `save()` в неопределённом порядке' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Делегирование через `by` генерирует forwarding внешних вызовов, но не переписывает self-calls внутри delegate.',
      mechanism: '`sync()` исполняется на объекте delegate, и его вызов собственного `save()` разрешается на том же объекте. Поэтому `by` не является полным interception/decorator-механизмом для всех внутренних операций.',
      trap: 'Логирование или контроль доступа, требующие перехвата каждого вызова, нельзя считать гарантированными только из-за delegation.',
    },
    source: { file: sourceFile, section: '9.1. Делегирование класса через by' },
    tags: ['delegation', 'decorator', 'dispatch'],
  },
  {
    id: 'kotlin-030',
    topicId: 'kotlin',
    subtopic: 'Lazy',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Как ведёт себя `lazy(LazyThreadSafetyMode.PUBLICATION)` при конкурентном первом доступе?',
    options: [
      { id: 'a', text: 'Initializer гарантированно запускается ровно один раз под одним monitor' },
      { id: 'b', text: 'Initializer может выполниться несколько раз, но опубликовано будет одно значение' },
      { id: 'c', text: 'Значение публикуется без каких-либо гарантий видимости' },
      { id: 'd', text: 'Первый конкурентный доступ всегда бросает исключение' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`PUBLICATION` допускает несколько конкурентных вычислений, выбирая одно опубликованное значение.',
      mechanism: 'Режим уменьшает сериализацию initializer по сравнению с `SYNCHRONIZED`, но требует, чтобы повторный запуск был безопасен. Побочный эффект initializer может произойти более одного раза.',
      trap: 'Если нужна строгая однократность вычисления, стандартный `SYNCHRONIZED` соответствует контракту лучше.',
    },
    source: { file: sourceFile, section: '9.3. lazy и его режимы' },
    tags: ['lazy', 'thread-safety', 'publication'],
  },
  {
    id: 'kotlin-031',
    topicId: 'kotlin',
    subtopic: 'Инициализация свойств',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Что происходит при чтении `lateinit var dependency: Repository` до присваивания?',
    options: [
      { id: 'a', text: 'Возвращается `null`' },
      { id: 'b', text: 'Создаётся Repository через default constructor' },
      { id: 'c', text: 'Возникает `UninitializedPropertyAccessException`' },
      { id: 'd', text: 'Возникает ошибка компиляции во всех случаях' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: '`lateinit` откладывает обязательную инициализацию, но сохраняет объявленный non-null тип.',
      mechanism: 'Getter проверяет специальное неинициализированное состояние и бросает `UninitializedPropertyAccessException`. Если отсутствие значения является нормальным состоянием модели, честное nullable-свойство обычно точнее.',
      trap: '`lateinit` не подходит для `val`, nullable-типа и обычных примитивных properties.',
    },
    source: { file: sourceFile, section: '9.4. lateinit против nullable и lazy' },
    tags: ['lateinit', 'properties', 'initialization'],
  },
  {
    id: 'kotlin-032',
    topicId: 'kotlin',
    subtopic: 'Свойства JVM',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Когда Kotlin-свойство с getter не нуждается в backing field?',
    options: [
      { id: 'a', text: 'Когда getter вычисляет значение и не обращается к `field`' },
      { id: 'b', text: 'Только когда свойство объявлено `lateinit`' },
      { id: 'c', text: 'Любое `val` всегда имеет backing field' },
      { id: 'd', text: 'Только у top-level `const val`' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: 'Property — языковая декларация и не обязана соответствовать JVM-полю.',
      mechanism: 'Если getter каждый раз вычисляет результат и хранить состояние не требуется, компилятор может сгенерировать только метод доступа. Идентификатор `field` доступен в accessor лишь когда свойству действительно нужно хранилище.',
      example: '`val fullName get() = "$firstName $lastName"` не требует отдельного поля `fullName`.',
    },
    source: { file: sourceFile, section: '9.5. Backing field и custom accessor' },
    tags: ['properties', 'backing-field', 'jvm'],
  },
  {
    id: 'kotlin-033',
    topicId: 'kotlin',
    subtopic: 'Исключения и ресурсы',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Почему `use` обычно предпочтительнее ручного `finally` при закрытии ресурса?',
    options: [
      { id: 'a', text: '`use` подавляет основную ошибку и оставляет только ошибку `close`' },
      { id: 'b', text: '`use` сохраняет основную ошибку, а ошибку закрытия может добавить как suppressed' },
      { id: 'c', text: '`use` никогда не вызывает `close`, если блок упал' },
      { id: 'd', text: '`use` делает I/O неблокирующим' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: '`use` реализует корректную политику закрытия при нескольких исключениях.',
      mechanism: 'Если основная операция уже бросила исключение, ошибка `close` не должна уничтожить исходную диагностическую причину; она добавляется как suppressed. Наивный `finally` легко заменить исходное исключение ошибкой закрытия.',
      trap: '`use` управляет ресурсом и исключениями, но не меняет blocking-характер операции.',
    },
    source: { file: sourceFile, section: '10. Исключения, Result и контракты' },
    tags: ['exceptions', 'resources', 'use'],
  },
  {
    id: 'kotlin-034',
    topicId: 'kotlin',
    subtopic: 'Инварианты',
    difficulty: 'basic',
    kind: 'theory',
    prompt: 'Как правильно различить `require` и `check`?',
    options: [
      { id: 'a', text: '`require` проверяет аргумент и бросает `IllegalArgumentException`; `check` проверяет состояние и бросает `IllegalStateException`' },
      { id: 'b', text: '`require` бросает checked exception, а `check` — unchecked' },
      { id: 'c', text: '`check` работает только в debug-сборках' },
      { id: 'd', text: 'Обе функции возвращают `Result<Boolean>`' },
    ],
    correctOptionId: 'a',
    explanation: {
      summary: '`require` выражает нарушение требования caller, а `check` — недопустимое состояние объекта или вычисления.',
      mechanism: 'Разные exception types помогают зафиксировать источник programming error. Эти функции не предназначены для штатных бизнес-исходов вроде неверного пароля.',
      trap: 'Проверки выполняются и в release; это не аналог отключаемого JVM `assert`.',
    },
    source: { file: sourceFile, section: '10.2. require, check, error' },
    tags: ['require', 'check', 'exceptions', 'contracts'],
  },
  {
    id: 'kotlin-035',
    topicId: 'kotlin',
    subtopic: 'Result',
    difficulty: 'senior',
    kind: 'theory',
    prompt: 'Чем `Result.mapCatching` отличается от `Result.map`?',
    options: [
      { id: 'a', text: '`mapCatching` запускает transform только для failure' },
      { id: 'b', text: '`mapCatching` упаковывает исключение transform в failure, а `map` не предназначен для такого поглощения' },
      { id: 'c', text: '`map` всегда меняет failure на success' },
      { id: 'd', text: 'Различие существует только в JavaScript target' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Catching-вариант явно включает ошибки преобразования в `Result`, обычный `map` лишь преобразует success.',
      mechanism: 'Это различие задаёт политику ошибки API: следует решить, является ли exception transform ожидаемым failure или programming error. Бездумное catching скрывает дефекты и стирает taxonomy ошибок.',
      trap: 'Не каждое `Throwable` следует превращать в штатный результат.',
    },
    source: { file: sourceFile, section: '10. Исключения, Result и контракты' },
    tags: ['result', 'exceptions', 'map-catching'],
  },
  {
    id: 'kotlin-036',
    topicId: 'kotlin',
    subtopic: 'Contracts',
    difficulty: 'expert',
    kind: 'theory',
    prompt: 'Какую пользу и риск несёт пользовательский Kotlin contract?',
    options: [
      { id: 'a', text: 'Он синхронизирует доступ к данным, но может вызвать deadlock' },
      { id: 'b', text: 'Он сообщает компилятору факты для анализа, но неверный contract может сделать выводы компилятора небезопасными' },
      { id: 'c', text: 'Он проверяет REST-контракт во время выполнения' },
      { id: 'd', text: 'Он заменяет generic constraints в JVM bytecode' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Contracts уточняют control/data-flow для smart casts и definite assignment, не выполняя runtime-проверку сами по себе.',
      mechanism: 'Декларация может обещать, что `true` означает non-null аргумент или что лямбда вызывается ровно один раз. Если реализация нарушает обещание, компилятор строит неверные предположения, поэтому API требует осторожности и местами opt-in.',
      trap: 'Contract описывает поведение функции, но не обеспечивает его автоматически.',
    },
    source: { file: sourceFile, section: '10.4. Что такое contracts?' },
    tags: ['contracts', 'smart-cast', 'compiler'],
  },
  {
    id: 'kotlin-037',
    topicId: 'kotlin',
    subtopic: 'Java API',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Kotlin-функция имеет три параметра с default values и должна быть удобно вызываема из Java. Что делает `@JvmOverloads`?',
    options: [
      { id: 'a', text: 'Даёт Java синтаксис именованных аргументов' },
      { id: 'b', text: 'Генерирует overloads, последовательно убирая параметры с конца' },
      { id: 'c', text: 'Создаёт один Java-метод с nullable-параметрами' },
      { id: 'd', text: 'Меняет все параметры на vararg' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Java не понимает Kotlin default arguments напрямую; `@JvmOverloads` материализует часть вариантов как JVM-методы.',
      mechanism: 'Overloads строятся удалением default-параметров справа налево. Для сложного публичного API явные factory, builder или осмысленные overloads могут дать более устойчивый контракт.',
      trap: 'Аннотация не создаёт комбинацию для любого произвольного пропуска параметра в середине.',
    },
    source: { file: sourceFile, section: '11.1. Как default arguments видны из Java?' },
    tags: ['jvm-overloads', 'java-interop', 'api-design'],
  },
  {
    id: 'kotlin-038',
    topicId: 'kotlin',
    subtopic: 'Аннотации',
    difficulty: 'expert',
    kind: 'scenario',
    prompt: 'Java framework ищет validation-аннотацию непосредственно на backing field Kotlin-свойства. Какой use-site target нужен?',
    options: [
      { id: 'a', text: '`@get:`' },
      { id: 'b', text: '`@param:`' },
      { id: 'c', text: '`@field:`' },
      { id: 'd', text: '`@receiver:`' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: '`@field:` направляет аннотацию на JVM backing field, который инспектирует framework.',
      mechanism: 'Одно Kotlin property может соответствовать constructor parameter, field, getter и setter. Без явной цели аннотация может оказаться не на том JVM-элементе, который сканирует Java-библиотека.',
      verification: 'Место аннотации можно проверить декомпиляцией класса или Java reflection по конкретному field/getter.',
    },
    source: { file: sourceFile, section: '15. DSL, annotations и reflection' },
    tags: ['annotations', 'use-site-target', 'java-interop'],
  },
  {
    id: 'kotlin-039',
    topicId: 'kotlin',
    subtopic: 'Reflection и shrinking',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Что следует учесть при активном использовании Kotlin reflection в Android-приложении?',
    options: [
      { id: 'a', text: 'Она гарантированно удаляется R8 без настройки и не влияет на startup' },
      { id: 'b', text: 'Нужны соответствующая библиотека, оценка размера/startup и корректные shrinker rules' },
      { id: 'c', text: '`KClass` существует только во время компиляции' },
      { id: 'd', text: 'Reflection автоматически заменяется KSP на generated code' },
    ],
    correctOptionId: 'b',
    explanation: {
      summary: 'Runtime reflection имеет стоимость и зависит от сохранения инспектируемой metadata после shrinking.',
      mechanism: 'Kotlin reflection может увеличить APK и startup work, а R8 способен переименовать или удалить динамически обнаруживаемые элементы. Keep rules должны быть точечными и проверенными на release-сборке.',
      trap: 'Глобальный `-keep class ** { *; }` скрывает проблему ценой почти полного отключения shrinking.',
    },
    source: { file: sourceFile, section: '15.3. KClass и Java Class' },
    tags: ['reflection', 'r8', 'android-performance'],
  },
  {
    id: 'kotlin-040',
    topicId: 'kotlin',
    subtopic: 'Архитектурное моделирование',
    difficulty: 'senior',
    kind: 'scenario',
    prompt: 'Как лучше смоделировать результат login с вариантами success, неверные credentials и заблокированный аккаунт?',
    options: [
      { id: 'a', text: 'Вернуть `Boolean` и передать детали через глобальную переменную' },
      { id: 'b', text: 'Вернуть nullable `User?`, считая оба отказа одним отсутствием' },
      { id: 'c', text: 'Использовать sealed result с отдельным subtype для каждого осмысленного исхода' },
      { id: 'd', text: 'Бросать `NullPointerException` для каждого отказа' },
    ],
    correctOptionId: 'c',
    explanation: {
      summary: 'Закрытая алгебраическая модель сохраняет различия бизнес-исходов и заставляет caller обрабатывать их исчерпывающе.',
      mechanism: 'Например, `Success(user)`, `InvalidCredentials` и `AccountLocked` имеют разные формы и смысл. `when` без `else` даст compile-time напоминание при добавлении нового исхода, а инфраструктурные exceptions можно преобразовать на границе repository.',
      trap: 'Nullable подходит только когда отсутствие — единственная ожидаемая альтернатива; `Boolean` создаёт boolean blindness.',
    },
    source: { file: sourceFile, section: '17.1. Как моделировать результат операции?' },
    tags: ['architecture', 'sealed', 'domain-modeling', 'exhaustiveness'],
  },
]
